

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.input_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.act1_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.act2_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.act3_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_RD_IN_fu_104"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_RD_IN_fu_104.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123.mul_26s_26s_52_1_1_U9"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_B_fu_143"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_B_fu_143.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162.mul_26s_26s_52_1_1_U28"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_B_fu_182"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_B_fu_182.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201.mul_26s_26s_52_1_1_U46"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_B_fu_221"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_B_fu_221.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240.mul_26s_26s_52_1_1_U64"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_B_fu_261"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_B_fu_261.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_WR_OUT_fu_281"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_WR_OUT_fu_281.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.ctrl_s_axi_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_data_V_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_keep_V_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_strb_V_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_user_V_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_last_V_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_id_V_U"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_dest_V_U"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_data_V_U"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_keep_V_U"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_strb_V_U"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_user_V_U"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_last_V_U"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_id_V_U"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_dest_V_U"}]}
set DependenceCheckSize 0
