

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "7", "10", "12", "15", "17", "20", "22", "25", "27", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43"],
		"CDFG" : "bnn_top",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "148860", "EstimateLatencyMax" : "148860",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_data_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_keep_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_strb_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_user_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_last_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_id_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"SubConnect" : [
					{"ID" : "5", "SubInstance" : "grp_bnn_top_Pipeline_RD_IN_fu_104", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "2", "Inst_end_state" : "3"},
					{"ID" : "7", "SubInstance" : "grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "4", "Inst_end_state" : "5"},
					{"ID" : "10", "SubInstance" : "grp_bnn_top_Pipeline_L1_B_fu_143", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "6", "Inst_end_state" : "7"},
					{"ID" : "12", "SubInstance" : "grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "8", "Inst_end_state" : "9"},
					{"ID" : "15", "SubInstance" : "grp_bnn_top_Pipeline_L2_B_fu_182", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "10", "Inst_end_state" : "11"},
					{"ID" : "17", "SubInstance" : "grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "12", "Inst_end_state" : "13"},
					{"ID" : "20", "SubInstance" : "grp_bnn_top_Pipeline_L3_B_fu_221", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "14", "Inst_end_state" : "15"},
					{"ID" : "22", "SubInstance" : "grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "16", "Inst_end_state" : "17"},
					{"ID" : "25", "SubInstance" : "grp_bnn_top_Pipeline_L4_B_fu_261", "Port" : "s_axis_input_V_dest_V", "Inst_start_state" : "18", "Inst_end_state" : "19"}]},
			{"Name" : "m_axis_output_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_data_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "m_axis_output_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_keep_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "m_axis_output_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_strb_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "m_axis_output_V_user_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_user_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "m_axis_output_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_last_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "m_axis_output_V_id_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_id_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]},
			{"Name" : "m_axis_output_V_dest_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"SubConnect" : [
					{"ID" : "27", "SubInstance" : "grp_bnn_top_Pipeline_WR_OUT_fu_281", "Port" : "m_axis_output_V_dest_V", "Inst_start_state" : "20", "Inst_end_state" : "21"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.input_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.act1_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.act2_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.act3_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_RD_IN_fu_104", "Parent" : "0", "Child" : ["6"],
		"CDFG" : "bnn_top_Pipeline_RD_IN",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "66", "EstimateLatencyMax" : "66",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "RD_IN", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_RD_IN_fu_104.flow_control_loop_pipe_sequential_init_U", "Parent" : "5"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123", "Parent" : "0", "Child" : ["8", "9"],
		"CDFG" : "bnn_top_Pipeline_L1_W_L1_IN",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "16389", "EstimateLatencyMax" : "16389",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "input_r", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "act1", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L1_W_L1_IN", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123.mul_26s_26s_52_1_1_U9", "Parent" : "7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_W_L1_IN_fu_123.flow_control_loop_pipe_sequential_init_U", "Parent" : "7"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_B_fu_143", "Parent" : "0", "Child" : ["11"],
		"CDFG" : "bnn_top_Pipeline_L1_B",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259", "EstimateLatencyMax" : "259",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "act1", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "L1_B", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L1_B_fu_143.flow_control_loop_pipe_sequential_init_U", "Parent" : "10"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162", "Parent" : "0", "Child" : ["13", "14"],
		"CDFG" : "bnn_top_Pipeline_L2_W_L2_IN",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65541", "EstimateLatencyMax" : "65541",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "act1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "act2", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L2_W_L2_IN", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162.mul_26s_26s_52_1_1_U28", "Parent" : "12"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_W_L2_IN_fu_162.flow_control_loop_pipe_sequential_init_U", "Parent" : "12"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_B_fu_182", "Parent" : "0", "Child" : ["16"],
		"CDFG" : "bnn_top_Pipeline_L2_B",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259", "EstimateLatencyMax" : "259",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "act2", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "L2_B", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L2_B_fu_182.flow_control_loop_pipe_sequential_init_U", "Parent" : "15"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201", "Parent" : "0", "Child" : ["18", "19"],
		"CDFG" : "bnn_top_Pipeline_L3_W_L3_IN",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65541", "EstimateLatencyMax" : "65541",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "act2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "act3", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L3_W_L3_IN", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter4", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter4", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201.mul_26s_26s_52_1_1_U46", "Parent" : "17"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_W_L3_IN_fu_201.flow_control_loop_pipe_sequential_init_U", "Parent" : "17"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_B_fu_221", "Parent" : "0", "Child" : ["21"],
		"CDFG" : "bnn_top_Pipeline_L3_B",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259", "EstimateLatencyMax" : "259",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "act3", "Type" : "Memory", "Direction" : "IO"}],
		"Loop" : [
			{"Name" : "L3_B", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L3_B_fu_221.flow_control_loop_pipe_sequential_init_U", "Parent" : "20"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240", "Parent" : "0", "Child" : ["23", "24"],
		"CDFG" : "bnn_top_Pipeline_L4_W_L4_IN",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "516", "EstimateLatencyMax" : "516",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "act4", "Type" : "Vld", "Direction" : "O"},
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "act3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "act4_1", "Type" : "Vld", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "L4_W_L4_IN", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter3", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter3", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240.mul_26s_26s_52_1_1_U64", "Parent" : "22"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_W_L4_IN_fu_240.flow_control_loop_pipe_sequential_init_U", "Parent" : "22"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_B_fu_261", "Parent" : "0", "Child" : ["26"],
		"CDFG" : "bnn_top_Pipeline_L4_B",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "5", "EstimateLatencyMax" : "5",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "act4", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "act4_1", "Type" : "OVld", "Direction" : "IO"},
			{"Name" : "s_axis_input_V_data_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input",
				"BlockSignal" : [
					{"Name" : "s_axis_input_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "s_axis_input_V_keep_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_strb_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_user_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_last_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_id_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"},
			{"Name" : "s_axis_input_V_dest_V", "Type" : "Axis", "Direction" : "I", "BaseName" : "s_axis_input"}],
		"Loop" : [
			{"Name" : "L4_B", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_L4_B_fu_261.flow_control_loop_pipe_sequential_init_U", "Parent" : "25"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_WR_OUT_fu_281", "Parent" : "0", "Child" : ["28"],
		"CDFG" : "bnn_top_Pipeline_WR_OUT",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4", "EstimateLatencyMax" : "4",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "act4_1_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "act4_load", "Type" : "None", "Direction" : "I"},
			{"Name" : "m_axis_output_V_data_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output",
				"BlockSignal" : [
					{"Name" : "m_axis_output_TDATA_blk_n", "Type" : "RtlSignal"}]},
			{"Name" : "m_axis_output_V_keep_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output"},
			{"Name" : "m_axis_output_V_strb_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output"},
			{"Name" : "m_axis_output_V_user_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output"},
			{"Name" : "m_axis_output_V_last_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output"},
			{"Name" : "m_axis_output_V_id_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output"},
			{"Name" : "m_axis_output_V_dest_V", "Type" : "Axis", "Direction" : "O", "BaseName" : "m_axis_output"}],
		"Loop" : [
			{"Name" : "WR_OUT", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_bnn_top_Pipeline_WR_OUT_fu_281.flow_control_loop_pipe_sequential_init_U", "Parent" : "27"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.ctrl_s_axi_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_data_V_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_keep_V_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_strb_V_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_user_V_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_last_V_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_id_V_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_s_axis_input_V_dest_V_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_data_V_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_keep_V_U", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_strb_V_U", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_user_V_U", "Parent" : "0"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_last_V_U", "Parent" : "0"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_id_V_U", "Parent" : "0"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.regslice_both_m_axis_output_V_dest_V_U", "Parent" : "0"}]}
