#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axis_input_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("s_axis_input_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("s_axis_input_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("s_axis_input_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("s_axis_input_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("s_axis_input_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("s_axis_input_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("s_axis_input_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("s_axis_input_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("m_axis_output_TDATA", 32, hls_out, 7, "axis", "out_data", 1),
	Port_Property("m_axis_output_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("m_axis_output_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("m_axis_output_TKEEP", 4, hls_out, 8, "axis", "out_data", 1),
	Port_Property("m_axis_output_TSTRB", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("m_axis_output_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("m_axis_output_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("m_axis_output_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("m_axis_output_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("s_axi_ctrl_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_ctrl_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_ctrl_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "bnn_top";
