-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1 (win64) Build 6140274 Thu May 22 00:12:29 MDT 2025
-- Date        : Sun Apr 19 23:16:55 2026
-- Host        : DESKTOP-G7LOJLI running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode synth_stub
--               c:/Users/Akshay/OneDrive/Desktop/FGPA-Based-Hardware-Accelerator/CNN/fpga/vivado/proj_mnist_cnn/mnist_cnn.gen/sources_1/bd/cnn_system/ip/cnn_system_cnn_top_0_0/cnn_system_cnn_top_0_0_stub.vhdl
-- Design      : cnn_system_cnn_top_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity cnn_system_cnn_top_0_0 is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 6 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    s_axi_ctrl_ARADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_ctrl_ARREADY : out STD_LOGIC;
    s_axi_ctrl_ARVALID : in STD_LOGIC;
    s_axi_ctrl_AWADDR : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_ctrl_AWREADY : out STD_LOGIC;
    s_axi_ctrl_AWVALID : in STD_LOGIC;
    s_axi_ctrl_BREADY : in STD_LOGIC;
    s_axi_ctrl_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_ctrl_BVALID : out STD_LOGIC;
    s_axi_ctrl_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_ctrl_RREADY : in STD_LOGIC;
    s_axi_ctrl_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_ctrl_RVALID : out STD_LOGIC;
    s_axi_ctrl_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_ctrl_WREADY : out STD_LOGIC;
    s_axi_ctrl_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_ctrl_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_weights_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_weights_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_weights_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_weights_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_weights_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_weights_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_weights_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_ARREADY : in STD_LOGIC;
    m_axi_weights_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_weights_ARVALID : out STD_LOGIC;
    m_axi_weights_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_weights_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_weights_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_weights_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_weights_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_weights_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_weights_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_AWREADY : in STD_LOGIC;
    m_axi_weights_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_weights_AWVALID : out STD_LOGIC;
    m_axi_weights_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_weights_BREADY : out STD_LOGIC;
    m_axi_weights_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_weights_BVALID : in STD_LOGIC;
    m_axi_weights_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_weights_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_weights_RLAST : in STD_LOGIC;
    m_axi_weights_RREADY : out STD_LOGIC;
    m_axi_weights_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_weights_RVALID : in STD_LOGIC;
    m_axi_weights_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_weights_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_weights_WLAST : out STD_LOGIC;
    m_axi_weights_WREADY : in STD_LOGIC;
    m_axi_weights_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_weights_WVALID : out STD_LOGIC;
    s_axis_input_TDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axis_input_TDEST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_input_TID : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_input_TKEEP : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_input_TLAST : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_input_TREADY : out STD_LOGIC;
    s_axis_input_TSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axis_input_TUSER : in STD_LOGIC_VECTOR ( 0 to 0 );
    s_axis_input_TVALID : in STD_LOGIC;
    m_axis_output_TDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axis_output_TDEST : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_output_TID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_output_TKEEP : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_output_TLAST : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_output_TREADY : in STD_LOGIC;
    m_axis_output_TSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axis_output_TUSER : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axis_output_TVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of cnn_system_cnn_top_0_0 : entity is "cnn_system_cnn_top_0_0,cnn_top,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of cnn_system_cnn_top_0_0 : entity is "cnn_system_cnn_top_0_0,cnn_top,{x_ipProduct=Vivado 2025.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=cnn_top,x_ipVersion=1.0,x_ipCoreRevision=2114573109,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=7,C_S_AXI_CONTROL_DATA_WIDTH=32,C_S_AXI_CTRL_ADDR_WIDTH=4,C_S_AXI_CTRL_DATA_WIDTH=32,C_M_AXI_WEIGHTS_ID_WIDTH=1,C_M_AXI_WEIGHTS_ADDR_WIDTH=64,C_M_AXI_WEIGHTS_DATA_WIDTH=32,C_M_AXI_WEIGHTS_AWUSER_WIDTH=1,C_M_AXI_WEIGHTS_ARUSER_WIDTH=1,C_M_AXI_WEIGHTS_WUSER_WIDTH=1,C_M_AXI_WEIGHTS_RUSER_WIDTH=1,C_M_AXI_WEIGHTS_BUSER_WIDTH=1,C_M_AXI_WEIGHTS_USER_VALUE=0x00000000,C_M_AXI_WEIGHTS_PROT_VALUE=000,C_M_AXI_WEIGHTS_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of cnn_system_cnn_top_0_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of cnn_system_cnn_top_0_0 : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of cnn_system_cnn_top_0_0 : entity is "yes";
end cnn_system_cnn_top_0_0;

architecture stub of cnn_system_cnn_top_0_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[6:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[6:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,s_axi_ctrl_ARADDR[3:0],s_axi_ctrl_ARREADY,s_axi_ctrl_ARVALID,s_axi_ctrl_AWADDR[3:0],s_axi_ctrl_AWREADY,s_axi_ctrl_AWVALID,s_axi_ctrl_BREADY,s_axi_ctrl_BRESP[1:0],s_axi_ctrl_BVALID,s_axi_ctrl_RDATA[31:0],s_axi_ctrl_RREADY,s_axi_ctrl_RRESP[1:0],s_axi_ctrl_RVALID,s_axi_ctrl_WDATA[31:0],s_axi_ctrl_WREADY,s_axi_ctrl_WSTRB[3:0],s_axi_ctrl_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_weights_ARADDR[63:0],m_axi_weights_ARBURST[1:0],m_axi_weights_ARCACHE[3:0],m_axi_weights_ARID[0:0],m_axi_weights_ARLEN[7:0],m_axi_weights_ARLOCK[1:0],m_axi_weights_ARPROT[2:0],m_axi_weights_ARQOS[3:0],m_axi_weights_ARREADY,m_axi_weights_ARREGION[3:0],m_axi_weights_ARSIZE[2:0],m_axi_weights_ARVALID,m_axi_weights_AWADDR[63:0],m_axi_weights_AWBURST[1:0],m_axi_weights_AWCACHE[3:0],m_axi_weights_AWID[0:0],m_axi_weights_AWLEN[7:0],m_axi_weights_AWLOCK[1:0],m_axi_weights_AWPROT[2:0],m_axi_weights_AWQOS[3:0],m_axi_weights_AWREADY,m_axi_weights_AWREGION[3:0],m_axi_weights_AWSIZE[2:0],m_axi_weights_AWVALID,m_axi_weights_BID[0:0],m_axi_weights_BREADY,m_axi_weights_BRESP[1:0],m_axi_weights_BVALID,m_axi_weights_RDATA[31:0],m_axi_weights_RID[0:0],m_axi_weights_RLAST,m_axi_weights_RREADY,m_axi_weights_RRESP[1:0],m_axi_weights_RVALID,m_axi_weights_WDATA[31:0],m_axi_weights_WID[0:0],m_axi_weights_WLAST,m_axi_weights_WREADY,m_axi_weights_WSTRB[3:0],m_axi_weights_WVALID,s_axis_input_TDATA[31:0],s_axis_input_TDEST[0:0],s_axis_input_TID[0:0],s_axis_input_TKEEP[3:0],s_axis_input_TLAST[0:0],s_axis_input_TREADY,s_axis_input_TSTRB[3:0],s_axis_input_TUSER[0:0],s_axis_input_TVALID,m_axis_output_TDATA[31:0],m_axis_output_TDEST[0:0],m_axis_output_TID[0:0],m_axis_output_TKEEP[3:0],m_axis_output_TLAST[0:0],m_axis_output_TREADY,m_axis_output_TSTRB[3:0],m_axis_output_TUSER[0:0],m_axis_output_TVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 7, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cnn_system_ps7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl ARADDR";
  attribute X_INTERFACE_MODE of s_axi_ctrl_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axi_ctrl_ARADDR : signal is "XIL_INTERFACENAME s_axi_ctrl, ADDR_WIDTH 4, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN cnn_system_ps7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_ctrl_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl ARREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl ARVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl AWADDR";
  attribute X_INTERFACE_INFO of s_axi_ctrl_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl AWREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl AWVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl BREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl BRESP";
  attribute X_INTERFACE_INFO of s_axi_ctrl_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl BVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RDATA";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RRESP";
  attribute X_INTERFACE_INFO of s_axi_ctrl_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl RVALID";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WDATA";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WREADY";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WSTRB";
  attribute X_INTERFACE_INFO of s_axi_ctrl_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_ctrl WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:s_axi_ctrl:m_axi_weights:s_axis_input:m_axis_output, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN cnn_system_ps7_0_FCLK_CLK0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_weights_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARADDR";
  attribute X_INTERFACE_MODE of m_axi_weights_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_weights_ARADDR : signal is "XIL_INTERFACENAME m_axi_weights, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN cnn_system_ps7_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_weights_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARBURST";
  attribute X_INTERFACE_INFO of m_axi_weights_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_weights_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARID";
  attribute X_INTERFACE_INFO of m_axi_weights_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARLEN";
  attribute X_INTERFACE_INFO of m_axi_weights_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_weights_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARPROT";
  attribute X_INTERFACE_INFO of m_axi_weights_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARQOS";
  attribute X_INTERFACE_INFO of m_axi_weights_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARREADY";
  attribute X_INTERFACE_INFO of m_axi_weights_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARREGION";
  attribute X_INTERFACE_INFO of m_axi_weights_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_weights_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights ARVALID";
  attribute X_INTERFACE_INFO of m_axi_weights_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWADDR";
  attribute X_INTERFACE_INFO of m_axi_weights_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWBURST";
  attribute X_INTERFACE_INFO of m_axi_weights_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_weights_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWID";
  attribute X_INTERFACE_INFO of m_axi_weights_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWLEN";
  attribute X_INTERFACE_INFO of m_axi_weights_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_weights_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWPROT";
  attribute X_INTERFACE_INFO of m_axi_weights_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWQOS";
  attribute X_INTERFACE_INFO of m_axi_weights_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWREADY";
  attribute X_INTERFACE_INFO of m_axi_weights_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWREGION";
  attribute X_INTERFACE_INFO of m_axi_weights_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_weights_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights AWVALID";
  attribute X_INTERFACE_INFO of m_axi_weights_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights BID";
  attribute X_INTERFACE_INFO of m_axi_weights_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights BREADY";
  attribute X_INTERFACE_INFO of m_axi_weights_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights BRESP";
  attribute X_INTERFACE_INFO of m_axi_weights_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights BVALID";
  attribute X_INTERFACE_INFO of m_axi_weights_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights RDATA";
  attribute X_INTERFACE_INFO of m_axi_weights_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights RID";
  attribute X_INTERFACE_INFO of m_axi_weights_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights RLAST";
  attribute X_INTERFACE_INFO of m_axi_weights_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights RREADY";
  attribute X_INTERFACE_INFO of m_axi_weights_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights RRESP";
  attribute X_INTERFACE_INFO of m_axi_weights_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights RVALID";
  attribute X_INTERFACE_INFO of m_axi_weights_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights WDATA";
  attribute X_INTERFACE_INFO of m_axi_weights_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights WID";
  attribute X_INTERFACE_INFO of m_axi_weights_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights WLAST";
  attribute X_INTERFACE_INFO of m_axi_weights_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights WREADY";
  attribute X_INTERFACE_INFO of m_axi_weights_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights WSTRB";
  attribute X_INTERFACE_INFO of m_axi_weights_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_weights WVALID";
  attribute X_INTERFACE_INFO of s_axis_input_TDATA : signal is "xilinx.com:interface:axis:1.0 s_axis_input TDATA";
  attribute X_INTERFACE_MODE of s_axis_input_TDATA : signal is "slave";
  attribute X_INTERFACE_PARAMETER of s_axis_input_TDATA : signal is "XIL_INTERFACENAME s_axis_input, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN cnn_system_ps7_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axis_input_TDEST : signal is "xilinx.com:interface:axis:1.0 s_axis_input TDEST";
  attribute X_INTERFACE_INFO of s_axis_input_TID : signal is "xilinx.com:interface:axis:1.0 s_axis_input TID";
  attribute X_INTERFACE_INFO of s_axis_input_TKEEP : signal is "xilinx.com:interface:axis:1.0 s_axis_input TKEEP";
  attribute X_INTERFACE_INFO of s_axis_input_TLAST : signal is "xilinx.com:interface:axis:1.0 s_axis_input TLAST";
  attribute X_INTERFACE_INFO of s_axis_input_TREADY : signal is "xilinx.com:interface:axis:1.0 s_axis_input TREADY";
  attribute X_INTERFACE_INFO of s_axis_input_TSTRB : signal is "xilinx.com:interface:axis:1.0 s_axis_input TSTRB";
  attribute X_INTERFACE_INFO of s_axis_input_TUSER : signal is "xilinx.com:interface:axis:1.0 s_axis_input TUSER";
  attribute X_INTERFACE_INFO of s_axis_input_TVALID : signal is "xilinx.com:interface:axis:1.0 s_axis_input TVALID";
  attribute X_INTERFACE_INFO of m_axis_output_TDATA : signal is "xilinx.com:interface:axis:1.0 m_axis_output TDATA";
  attribute X_INTERFACE_MODE of m_axis_output_TDATA : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axis_output_TDATA : signal is "XIL_INTERFACENAME m_axis_output, TUSER_WIDTH 1, TDATA_NUM_BYTES 4, TDEST_WIDTH 1, TID_WIDTH 1, HAS_TREADY 1, HAS_TSTRB 1, HAS_TKEEP 1, HAS_TLAST 1, FREQ_HZ 100000000, PHASE 0.0, CLK_DOMAIN cnn_system_ps7_0_FCLK_CLK0, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axis_output_TDEST : signal is "xilinx.com:interface:axis:1.0 m_axis_output TDEST";
  attribute X_INTERFACE_INFO of m_axis_output_TID : signal is "xilinx.com:interface:axis:1.0 m_axis_output TID";
  attribute X_INTERFACE_INFO of m_axis_output_TKEEP : signal is "xilinx.com:interface:axis:1.0 m_axis_output TKEEP";
  attribute X_INTERFACE_INFO of m_axis_output_TLAST : signal is "xilinx.com:interface:axis:1.0 m_axis_output TLAST";
  attribute X_INTERFACE_INFO of m_axis_output_TREADY : signal is "xilinx.com:interface:axis:1.0 m_axis_output TREADY";
  attribute X_INTERFACE_INFO of m_axis_output_TSTRB : signal is "xilinx.com:interface:axis:1.0 m_axis_output TSTRB";
  attribute X_INTERFACE_INFO of m_axis_output_TUSER : signal is "xilinx.com:interface:axis:1.0 m_axis_output TUSER";
  attribute X_INTERFACE_INFO of m_axis_output_TVALID : signal is "xilinx.com:interface:axis:1.0 m_axis_output TVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "cnn_top,Vivado 2025.1";
begin
end;
