# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.srcs/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bnn_accelerator_design_axi_smc_0.xci
# IP: The module: 'bnn_accelerator_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/bd_aed6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_0/bd_aed6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_1/bd_aed6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_2/bd_aed6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_3/bd_aed6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_4/bd_aed6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_5/bd_aed6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_6/bd_aed6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_7/bd_aed6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_8/bd_aed6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_9/bd_aed6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_10/bd_aed6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_11/bd_aed6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_12/bd_aed6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_1/bd_aed6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_1/bd_aed6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_5/bd_aed6_s00a2s_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_6/bd_aed6_sarn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_7/bd_aed6_srn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_8/bd_aed6_sawn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_9/bd_aed6_swn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_10/bd_aed6_sbn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_11/bd_aed6_m00s2a_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_accelerator_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_accelerator_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.srcs/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bnn_accelerator_design_axi_smc_0.xci
# IP: The module: 'bnn_accelerator_design_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/bd_aed6.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_0/bd_aed6_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_1/bd_aed6_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_2/bd_aed6_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_3/bd_aed6_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_4/bd_aed6_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_5/bd_aed6_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_6/bd_aed6_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_7/bd_aed6_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_8/bd_aed6_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_9/bd_aed6_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_10/bd_aed6_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_11/bd_aed6_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_12/bd_aed6_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_1/bd_aed6_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_1/bd_aed6_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_5/bd_aed6_s00a2s_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_6/bd_aed6_sarn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_7/bd_aed6_srn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_8/bd_aed6_sawn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_9/bd_aed6_swn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_10/bd_aed6_sbn_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/bd_0/ip/ip_11/bd_aed6_m00s2a_0_ooc.xdc

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_accelerator_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/bnn_accelerator/bnn_accelerator.gen/sources_1/bd/bnn_accelerator_design/ip/bnn_accelerator_design_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'bnn_accelerator_design_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
