#!/usr/bin/env python3
"""
generate_weights.py -- Extract siren MLP weights from best_model.pt,
                       quantise to Q4.12 int16, write C++ header for HLS.

Run BEFORE run_hls.tcl:
    python generate_weights.py

Input  : best_model.pt  (see DEFAULT_CKPT constant below, or --ckpt flag)
Output : mlp_weights_data.h   (C static const int16_t arrays)

Requires: torch  (pip install torch)
"""

import os
import sys
import argparse

SCALE   = 4096          # Q4.12
N_IN    = 41
L1_SIZE = 4
N_OUT   = 2

DEFAULT_CKPT = r"C:/Users/TA17084/Downloads/archive/sounds/ambulance/artifacts/best_model.pt"


def find_ckpt(provided=None):
    candidates = []
    if provided:
        candidates.append(provided)
    candidates.append(DEFAULT_CKPT)
    candidates.append(DEFAULT_CKPT.replace("/", "\\"))
    script_dir = os.path.dirname(os.path.abspath(__file__))
    candidates += [
        os.path.join(script_dir, "best_model.pt"),
        os.path.normpath(os.path.join(script_dir, "..", "..", "training", "best_model.pt")),
    ]
    for p in candidates:
        if os.path.exists(p):
            return p
    return None


def quantise(tensor, scale=SCALE):
    """Float tensor -> list of int16 Q4.12 values."""
    import torch
    vals = tensor.detach().float().flatten().tolist()
    out = []
    for v in vals:
        q = int(round(v * scale))
        q = max(-32768, min(32767, q))
        out.append(q)
    return out


def write_1d(f, name, values):
    n = len(values)
    f.write(f"static const int16_t {name}[{n}] = {{\n")
    per = 16
    for i in range(0, n, per):
        chunk = values[i:i + per]
        f.write("    " + ", ".join(f"{v:6d}" for v in chunk) + ",\n")
    f.write("};\n\n")


def write_2d(f, name, values, rows, cols):
    assert len(values) == rows * cols, f"{name}: expected {rows*cols}, got {len(values)}"
    f.write(f"static const int16_t {name}[{rows}][{cols}] = {{\n")
    for r in range(rows):
        row = values[r * cols:(r + 1) * cols]
        f.write("    { " + ", ".join(f"{v:6d}" for v in row) + " },\n")
    f.write("};\n\n")


def main():
    ap = argparse.ArgumentParser(description="Generate HLS weight header from best_model.pt")
    ap.add_argument("--ckpt", default=None, help="Path to best_model.pt")
    args = ap.parse_args()

    ckpt_path = find_ckpt(args.ckpt)
    if ckpt_path is None:
        sys.exit(
            "ERROR: best_model.pt not found.\n"
            f"  Tried: {DEFAULT_CKPT}\n"
            "  Provide path with --ckpt <path>"
        )

    print(f"Loading checkpoint: {ckpt_path}")
    try:
        import torch
    except ImportError:
        sys.exit("ERROR: torch not installed. Run: pip install torch")

    ckpt = torch.load(ckpt_path, weights_only=False, map_location="cpu")
    sd   = ckpt["model_state_dict"]

    # Extract and verify shapes
    W1 = sd["network.0.weight"]  # (4, 41)
    b1 = sd["network.0.bias"]    # (4,)
    W2 = sd["network.2.weight"]  # (2, 4)
    b2 = sd["network.2.bias"]    # (2,)

    assert W1.shape == (L1_SIZE, N_IN),   f"W1 shape mismatch: {W1.shape}"
    assert b1.shape == (L1_SIZE,),        f"b1 shape mismatch: {b1.shape}"
    assert W2.shape == (N_OUT, L1_SIZE),  f"W2 shape mismatch: {W2.shape}"
    assert b2.shape == (N_OUT,),          f"b2 shape mismatch: {b2.shape}"

    W1q = quantise(W1)
    b1q = quantise(b1)
    W2q = quantise(W2)
    b2q = quantise(b2)

    total = len(W1q) + len(b1q) + len(W2q) + len(b2q)
    print(f"  Parameters: {total}  (expected 178)")
    print(f"  W1 range: [{min(W1q)}, {max(W1q)}]")
    print(f"  W2 range: [{min(W2q)}, {max(W2q)}]")

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mlp_weights_data.h")
    print(f"Writing: {out_path}")

    with open(out_path, "w", encoding="ascii") as f:
        f.write("// mlp_weights_data.h  -- AUTO-GENERATED by generate_weights.py\n")
        f.write("// DO NOT EDIT BY HAND.  Re-run generate_weights.py to update.\n")
        f.write("// Model  : Siren classifier  41->4->2  (ambulance vs firetruck)\n")
        f.write("// Source : best_model.pt\n")
        f.write("// Fixed-point: Q4.12  (SCALE = 4096)\n")
        f.write("#ifndef MLP_WEIGHTS_DATA_H\n")
        f.write("#define MLP_WEIGHTS_DATA_H\n")
        f.write("#include <stdint.h>\n\n")
        write_2d(f, "siren_W1", W1q, L1_SIZE, N_IN)
        write_1d(f, "siren_b1", b1q)
        write_2d(f, "siren_W2", W2q, N_OUT, L1_SIZE)
        write_1d(f, "siren_b2", b2q)
        f.write("#endif // MLP_WEIGHTS_DATA_H\n")

    kb = os.path.getsize(out_path) / 1024
    print(f"Done.  {out_path}  ({kb:.1f} KB)")
    print()
    print("Next step:  vitis_hls -f run_hls.tcl")


if __name__ == "__main__":
    main()
