#ifndef MLP_TOP_H
#define MLP_TOP_H

// -------------------------------------------------------------------------
// mlp_top.h -- AXI-Stream MLP accelerator for Vitis HLS
//
// Architecture : 2-layer MLP  41->4->2  (Siren: ambulance vs firetruck)
// Fixed-point  : Q4.12  (data_t = ap_fixed<16,4>)
// Weights      : Stored in on-chip LUTRAM from mlp_weights_data.h
//                (generated by generate_weights.py from best_model.pt)
//
// Stream IN  : 41 int16 words (one per AXI-Stream 32-bit word, bits[15:0])
//              Q4.12 encoded features (standardised with checkpoint stats)
// Stream OUT : 1 uint32 word  -- argmax class (0=ambulance, 1=firetruck)
//              TLAST asserted on that single output word.
//
// ap_ctrl_none: free-running streaming pipeline, no AXI-Lite control port.
// DMA usage:    sendchannel -> recvchannel -> wait x2.
// -------------------------------------------------------------------------

#include "ap_fixed.h"
#include "hls_stream.h"
#include "ap_axi_sdata.h"

typedef ap_fixed<16, 4, AP_RND_ZERO, AP_SAT> data_t;   // Q4.12  -- data/weights
typedef ap_fixed<32, 8, AP_RND_ZERO, AP_SAT> accum_t;  // Q8.24  -- accumulator
typedef ap_axiu<32, 1, 1, 1>                 axis_t;   // 32-bit AXI-Stream word

#define N_IN    41
#define L1_SIZE  4
#define N_OUT    2

void mlp_top(
    hls::stream<axis_t>& s_axis_input,
    hls::stream<axis_t>& m_axis_output
);

#endif // MLP_TOP_H
