/*
 * mlp_tb.cpp — HLS C-Simulation Testbench
 * Uses the quantised weights from mlp_weights.h (generated by 01_export_weights_colab.py)
 * Tests a single MNIST sample and checks argmax of output matches ground truth.
 *
 * Run in Vitis HLS: C Simulation → check console for PASS/FAIL
 */

#include <iostream>
#include <cmath>
#include "mlp_top.h"
#include "mlp_weights.h"   // auto-generated: W1,B1 … W4,B4 as const short[]

// ── A hard-coded test sample (MNIST digit "7", normalised float) ──────────────
// Replace with actual pixel values exported from your dataset if needed.
// These are approximations for simulation purposes.
static float test_image_float[784] = {
    // 28×28 pixels for digit "7" (placeholder — all zeros except a stripe)
    // In real use, generate this from 01_export_weights_colab.py
    0
};
static int ground_truth_label = 7;

// ── Utility: float → ap_fixed<16,6> ─────────────────────────────────────────
static data_t float_to_fixed(float v) {
    return (data_t)v;
}

// ── Main testbench ────────────────────────────────────────────────────────────
int main() {
    // Build AXI-Stream input
    hls::stream<pkt_t> s_in("s_in");
    hls::stream<pkt_t> s_out("s_out");

    for (int i = 0; i < L0; i++) {
        pkt_t p;
        p.data = float_to_fixed(test_image_float[i]);
        p.last = (i == L0 - 1) ? 1 : 0;
        s_in.write(p);
    }

    // Cast stored short arrays to data_t arrays for the DUT
    // In HLS C-sim the pointers are treated as local arrays
    const data_t* w1 = reinterpret_cast<const data_t*>(W1);
    const data_t* b1 = reinterpret_cast<const data_t*>(B1);
    const data_t* w2 = reinterpret_cast<const data_t*>(W2);
    const data_t* b2 = reinterpret_cast<const data_t*>(B2);
    const data_t* w3 = reinterpret_cast<const data_t*>(W3);
    const data_t* b3 = reinterpret_cast<const data_t*>(B3);
    const data_t* w4 = reinterpret_cast<const data_t*>(W4);
    const data_t* b4 = reinterpret_cast<const data_t*>(B4);

    // Call DUT
    mlp_top(s_in, s_out, w1, b1, w2, b2, w3, b3, w4, b4);

    // Read and check output
    float logits[L4];
    int predicted = 0;
    float max_val = -1e9f;

    std::cout << "Output logits: ";
    for (int o = 0; o < L4; o++) {
        pkt_t p = s_out.read();
        logits[o] = (float)p.data;
        std::cout << logits[o] << " ";
        if (logits[o] > max_val) { max_val = logits[o]; predicted = o; }
    }
    std::cout << std::endl;

    std::cout << "Predicted: " << predicted
              << "  Ground truth: " << ground_truth_label << std::endl;

    if (predicted == ground_truth_label) {
        std::cout << "TESTBENCH PASSED" << std::endl;
        return 0;
    } else {
        std::cout << "TESTBENCH FAILED (placeholder image — replace with real data)" << std::endl;
        return 1;  // non-zero exit flags failure in Vitis HLS
    }
}
