# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cnn_accelerator_design/cnn_accelerator_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design || ORIG_REF_NAME==cnn_accelerator_design} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_processing_system7_0_0/cnn_accelerator_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_processing_system7_0_0 || ORIG_REF_NAME==cnn_accelerator_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_dma_0_0/cnn_accelerator_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_dma_0_0 || ORIG_REF_NAME==cnn_accelerator_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_cnn_accelerator_0_0/cnn_accelerator_design_cnn_accelerator_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_cnn_accelerator_0_0 || ORIG_REF_NAME==cnn_accelerator_design_cnn_accelerator_0_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_smc_0/cnn_accelerator_design_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_smc_0 || ORIG_REF_NAME==cnn_accelerator_design_axi_smc_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_rst_ps7_0_50M_0/cnn_accelerator_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==cnn_accelerator_design_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_mem_intercon_imp_xbar_0/cnn_accelerator_design_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_mem_intercon_0/cnn_accelerator_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_mem_intercon_0 || ORIG_REF_NAME==cnn_accelerator_design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_mem_intercon_imp_auto_us_0/cnn_accelerator_design_axi_mem_intercon_imp_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_auto_us_0 || ORIG_REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_auto_us_0} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_mem_intercon_imp_auto_us_1/cnn_accelerator_design_axi_mem_intercon_imp_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_auto_us_1 || ORIG_REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_auto_us_1} -quiet] -quiet

# IP: bd/cnn_accelerator_design/ip/cnn_accelerator_design_axi_mem_intercon_imp_auto_pc_0/cnn_accelerator_design_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==cnn_accelerator_design_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/Chappidi Sai Sudheer/Desktop/cnn_accelerator/cnn_accelerator.gen/sources_1/bd/cnn_accelerator_design/cnn_accelerator_design_ooc.xdc
