-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mlp_top_dense_relu_512_256_Pipeline_INNER is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln20 : IN STD_LOGIC_VECTOR (21 downto 0);
    o : IN STD_LOGIC_VECTOR (7 downto 0);
    in_act_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_0_ce0 : OUT STD_LOGIC;
    in_act_0_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_0_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_0_ce1 : OUT STD_LOGIC;
    in_act_0_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_1_ce0 : OUT STD_LOGIC;
    in_act_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_1_ce1 : OUT STD_LOGIC;
    in_act_1_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_2_ce0 : OUT STD_LOGIC;
    in_act_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_2_ce1 : OUT STD_LOGIC;
    in_act_2_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_3_ce0 : OUT STD_LOGIC;
    in_act_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    in_act_3_ce1 : OUT STD_LOGIC;
    in_act_3_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    acc_01_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    acc_01_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of mlp_top_dense_relu_512_256_Pipeline_INNER is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv10_8 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_const_lv20_0 : STD_LOGIC_VECTOR (19 downto 0) := "00000000000000000000";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_33 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal tmp_fu_346_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal p_ZL2w2_0_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_0_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_0_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_0_q1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_1_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_1_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_1_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_1_q1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_2_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_2_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_2_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_2_q1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_3_address0 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_3_q0 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_ZL2w2_3_address1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_ZL2w2_3_q1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_reg_2121 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln20_fu_364_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_reg_2125 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_s_fu_386_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_reg_2161 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln26_fu_449_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_reg_2186 : STD_LOGIC_VECTOR (43 downto 0);
    signal weight_8_reg_2192 : STD_LOGIC_VECTOR (8 downto 0);
    signal in_act_1_load_reg_2197 : STD_LOGIC_VECTOR (14 downto 0);
    signal weight_9_reg_2202 : STD_LOGIC_VECTOR (8 downto 0);
    signal weight_10_reg_2212 : STD_LOGIC_VECTOR (8 downto 0);
    signal weight_11_reg_2222 : STD_LOGIC_VECTOR (8 downto 0);
    signal weight_12_reg_2232 : STD_LOGIC_VECTOR (8 downto 0);
    signal weight_13_reg_2242 : STD_LOGIC_VECTOR (8 downto 0);
    signal weight_14_reg_2252 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln25_fu_378_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln25_2_fu_406_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln20_4_fu_462_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_01_fu_102 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal acc_33_fu_2089_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln20_cast_fu_329_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal i_fu_106 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln23_fu_414_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal p_ZL2w2_0_ce1_local : STD_LOGIC;
    signal p_ZL2w2_0_ce0_local : STD_LOGIC;
    signal in_act_0_ce1_local : STD_LOGIC;
    signal in_act_0_ce0_local : STD_LOGIC;
    signal p_ZL2w2_1_ce1_local : STD_LOGIC;
    signal p_ZL2w2_1_ce0_local : STD_LOGIC;
    signal in_act_1_ce1_local : STD_LOGIC;
    signal in_act_1_ce0_local : STD_LOGIC;
    signal p_ZL2w2_2_ce1_local : STD_LOGIC;
    signal p_ZL2w2_2_ce0_local : STD_LOGIC;
    signal p_ZL2w2_3_ce1_local : STD_LOGIC;
    signal p_ZL2w2_3_ce0_local : STD_LOGIC;
    signal in_act_2_ce1_local : STD_LOGIC;
    signal in_act_2_ce0_local : STD_LOGIC;
    signal in_act_3_ce1_local : STD_LOGIC;
    signal in_act_3_ce0_local : STD_LOGIC;
    signal lshr_ln_fu_354_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln_fu_370_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln25_2_fu_396_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal shl_ln_fu_425_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_s_fu_433_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_fu_449_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal or_ln_fu_455_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal shl_ln26_s_fu_476_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_32_fu_484_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_33_fu_488_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_fu_491_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_16_fu_473_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_34_fu_497_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_515_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_fu_531_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_fu_505_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_fu_537_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_18_fu_541_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_37_fu_547_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_fu_523_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_fu_555_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_49_fu_567_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_51_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_50_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_24_fu_597_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_48_fu_579_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_32_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_32_fu_609_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_52_fu_615_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_33_fu_603_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_34_fu_621_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_23_fu_633_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_1_fu_640_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_8_fu_655_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_8_fu_655_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_25_fu_627_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_fu_665_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_16_fu_673_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_24_fu_681_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_35_fu_689_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_36_fu_693_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_17_fu_697_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_18_fu_661_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_38_fu_703_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_721_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_35_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_19_fu_711_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_8_fu_743_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_20_fu_747_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_41_fu_753_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_729_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_53_fu_761_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_55_fu_773_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_35_fu_779_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_57_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_56_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_27_fu_803_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_54_fu_785_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_36_fu_767_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_38_fu_815_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_58_fu_821_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_37_fu_809_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_38_fu_827_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_25_fu_839_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_2_fu_846_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_9_fu_862_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_9_fu_862_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_28_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_17_fu_872_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_18_fu_880_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_26_fu_888_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_38_fu_896_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_39_fu_900_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_19_fu_904_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_20_fu_868_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_42_fu_910_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_928_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_39_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_21_fu_918_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_9_fu_950_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_22_fu_954_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_45_fu_960_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_44_fu_936_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_59_fu_968_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_61_fu_980_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_41_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_63_fu_998_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_62_fu_1004_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_30_fu_1010_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_60_fu_992_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_40_fu_974_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_44_fu_1022_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_64_fu_1028_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_41_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_42_fu_1034_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_27_fu_1046_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_3_fu_1053_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_10_fu_1069_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_10_fu_1069_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_31_fu_1040_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_19_fu_1079_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_20_fu_1087_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_28_fu_1095_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_41_fu_1103_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_42_fu_1107_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_21_fu_1111_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_22_fu_1075_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_46_fu_1117_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_1135_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_43_fu_1151_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_23_fu_1125_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_10_fu_1157_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_24_fu_1161_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_49_fu_1167_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_1143_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_65_fu_1175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_67_fu_1187_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_47_fu_1193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_69_fu_1205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_68_fu_1211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_33_fu_1217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_66_fu_1199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_44_fu_1181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_48_fu_1229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_70_fu_1235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_45_fu_1223_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_46_fu_1241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_29_fu_1253_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_4_fu_1260_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_11_fu_1276_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_11_fu_1276_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_34_fu_1247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_21_fu_1286_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_22_fu_1294_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_30_fu_1302_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_44_fu_1310_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_45_fu_1314_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_23_fu_1318_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_24_fu_1282_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_50_fu_1324_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_1342_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_47_fu_1358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_25_fu_1332_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_11_fu_1364_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_26_fu_1368_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_53_fu_1374_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_fu_1350_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_71_fu_1382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_73_fu_1394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_49_fu_1400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_75_fu_1412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_74_fu_1418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_36_fu_1424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_72_fu_1406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_48_fu_1388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_50_fu_1436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_76_fu_1442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_49_fu_1430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_50_fu_1448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_31_fu_1460_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_5_fu_1467_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_12_fu_1483_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_12_fu_1483_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_37_fu_1454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_23_fu_1493_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_24_fu_1501_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_32_fu_1509_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_47_fu_1517_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_48_fu_1521_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_25_fu_1525_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_26_fu_1489_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_54_fu_1531_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_1549_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_51_fu_1565_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_27_fu_1539_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_12_fu_1571_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_28_fu_1575_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_57_fu_1581_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_1557_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_77_fu_1589_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_79_fu_1601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_51_fu_1607_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_81_fu_1619_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_80_fu_1625_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_39_fu_1631_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_78_fu_1613_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_52_fu_1595_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_52_fu_1643_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_82_fu_1649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_53_fu_1637_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_54_fu_1655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_33_fu_1667_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_6_fu_1674_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_13_fu_1690_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_13_fu_1690_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_40_fu_1661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_25_fu_1700_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_26_fu_1708_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_34_fu_1716_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_50_fu_1724_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_51_fu_1728_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_27_fu_1732_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_28_fu_1696_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_58_fu_1738_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_1756_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_55_fu_1772_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_29_fu_1746_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_13_fu_1778_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_30_fu_1782_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_61_fu_1788_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_1764_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_83_fu_1796_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_85_fu_1808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_53_fu_1814_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_87_fu_1826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_86_fu_1832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_42_fu_1838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_84_fu_1820_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_56_fu_1802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_54_fu_1850_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_88_fu_1856_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_57_fu_1844_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_58_fu_1862_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln26_35_fu_1874_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal sext_ln26_7_fu_1881_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_14_fu_1897_p0 : STD_LOGIC_VECTOR (24 downto 0);
    signal mul_ln26_14_fu_1897_p2 : STD_LOGIC_VECTOR (43 downto 0);
    signal or_ln26_43_fu_1868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_27_fu_1907_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln26_28_fu_1915_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal shl_ln26_36_fu_1923_p3 : STD_LOGIC_VECTOR (51 downto 0);
    signal sext_ln26_53_fu_1931_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal sext_ln26_54_fu_1935_p1 : STD_LOGIC_VECTOR (52 downto 0);
    signal add_ln26_29_fu_1939_p2 : STD_LOGIC_VECTOR (52 downto 0);
    signal zext_ln26_30_fu_1903_p1 : STD_LOGIC_VECTOR (44 downto 0);
    signal tmp_62_fu_1945_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_fu_1963_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_59_fu_1979_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_31_fu_1953_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln26_14_fu_1985_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal acc_32_fu_1989_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_65_fu_1995_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_64_fu_1971_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_89_fu_2003_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_91_fu_2015_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_55_fu_2021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_93_fu_2033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_92_fu_2039_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_45_fu_2045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_90_fu_2027_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_60_fu_2009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_56_fu_2057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln26_94_fu_2063_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_61_fu_2051_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln26_62_fu_2069_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln26_46_fu_2083_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln26_29_fu_2075_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln26_10_fu_1069_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_11_fu_1276_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_12_fu_1483_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_13_fu_1690_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_14_fu_1897_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_8_fu_655_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_9_fu_862_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal mul_ln26_fu_449_p00 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component mlp_top_mul_25ns_19s_44_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (24 downto 0);
        din1 : IN STD_LOGIC_VECTOR (18 downto 0);
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        address1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        address1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        address1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (8 downto 0);
        address1 : IN STD_LOGIC_VECTOR (14 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component mlp_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    p_ZL2w2_0_U : component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_0_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 32768,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL2w2_0_address0,
        ce0 => p_ZL2w2_0_ce0_local,
        q0 => p_ZL2w2_0_q0,
        address1 => p_ZL2w2_0_address1,
        ce1 => p_ZL2w2_0_ce1_local,
        q1 => p_ZL2w2_0_q1);

    p_ZL2w2_1_U : component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_1_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 32768,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL2w2_1_address0,
        ce0 => p_ZL2w2_1_ce0_local,
        q0 => p_ZL2w2_1_q0,
        address1 => p_ZL2w2_1_address1,
        ce1 => p_ZL2w2_1_ce1_local,
        q1 => p_ZL2w2_1_q1);

    p_ZL2w2_2_U : component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_2_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 32768,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL2w2_2_address0,
        ce0 => p_ZL2w2_2_ce0_local,
        q0 => p_ZL2w2_2_q0,
        address1 => p_ZL2w2_2_address1,
        ce1 => p_ZL2w2_2_ce1_local,
        q1 => p_ZL2w2_2_q1);

    p_ZL2w2_3_U : component mlp_top_dense_relu_512_256_Pipeline_INNER_p_ZL2w2_3_ROM_AUTO_1R
    generic map (
        DataWidth => 9,
        AddressRange => 32768,
        AddressWidth => 15)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => p_ZL2w2_3_address0,
        ce0 => p_ZL2w2_3_ce0_local,
        q0 => p_ZL2w2_3_q0,
        address1 => p_ZL2w2_3_address1,
        ce1 => p_ZL2w2_3_ce1_local,
        q1 => p_ZL2w2_3_q1);

    mul_25ns_19s_44_1_1_U41 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_fu_449_p0,
        din1 => shl_ln_fu_425_p3,
        dout => mul_ln26_fu_449_p2);

    mul_25ns_19s_44_1_1_U42 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_8_fu_655_p0,
        din1 => shl_ln26_23_fu_633_p3,
        dout => mul_ln26_8_fu_655_p2);

    mul_25ns_19s_44_1_1_U43 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_9_fu_862_p0,
        din1 => shl_ln26_25_fu_839_p3,
        dout => mul_ln26_9_fu_862_p2);

    mul_25ns_19s_44_1_1_U44 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_10_fu_1069_p0,
        din1 => shl_ln26_27_fu_1046_p3,
        dout => mul_ln26_10_fu_1069_p2);

    mul_25ns_19s_44_1_1_U45 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_11_fu_1276_p0,
        din1 => shl_ln26_29_fu_1253_p3,
        dout => mul_ln26_11_fu_1276_p2);

    mul_25ns_19s_44_1_1_U46 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_12_fu_1483_p0,
        din1 => shl_ln26_31_fu_1460_p3,
        dout => mul_ln26_12_fu_1483_p2);

    mul_25ns_19s_44_1_1_U47 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_13_fu_1690_p0,
        din1 => shl_ln26_33_fu_1667_p3,
        dout => mul_ln26_13_fu_1690_p2);

    mul_25ns_19s_44_1_1_U48 : component mlp_top_mul_25ns_19s_44_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 25,
        din1_WIDTH => 19,
        dout_WIDTH => 44)
    port map (
        din0 => mul_ln26_14_fu_1897_p0,
        din1 => shl_ln26_35_fu_1874_p3,
        dout => mul_ln26_14_fu_1897_p2);

    flow_control_loop_pipe_sequential_init_U : component mlp_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    acc_01_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    acc_01_fu_102 <= sext_ln20_cast_fu_329_p1;
                elsif ((ap_enable_reg_pp0_iter2 = ap_const_logic_1)) then 
                    acc_01_fu_102 <= acc_33_fu_2089_p3;
                end if;
            end if; 
        end if;
    end process;

    i_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((tmp_fu_346_p3 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_106 <= add_ln23_fu_414_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_106 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                mul_ln26_reg_2186 <= mul_ln26_fu_449_p2;
                tmp_reg_2121 <= ap_sig_allocacmp_i_3(9 downto 9);
                tmp_s_reg_2161 <= ap_sig_allocacmp_i_3(8 downto 3);
                    zext_ln20_reg_2125(6 downto 0) <= zext_ln20_fu_364_p1(6 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                in_act_1_load_reg_2197 <= in_act_1_q1;
                weight_10_reg_2212 <= p_ZL2w2_3_q1;
                weight_11_reg_2222 <= p_ZL2w2_0_q0;
                weight_12_reg_2232 <= p_ZL2w2_1_q0;
                weight_13_reg_2242 <= p_ZL2w2_2_q0;
                weight_14_reg_2252 <= p_ZL2w2_3_q0;
                weight_8_reg_2192 <= p_ZL2w2_1_q1;
                weight_9_reg_2202 <= p_ZL2w2_2_q1;
            end if;
        end if;
    end process;
    zext_ln20_reg_2125(63 downto 7) <= "000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    acc_01_out <= acc_01_fu_102;

    acc_01_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, tmp_reg_2121, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (tmp_reg_2121 = ap_const_lv1_1))) then 
            acc_01_out_ap_vld <= ap_const_logic_1;
        else 
            acc_01_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_18_fu_541_p2 <= std_logic_vector(unsigned(acc_fu_505_p4) + unsigned(zext_ln26_fu_537_p1));
    acc_19_fu_711_p4 <= add_ln26_17_fu_697_p2(51 downto 20);
    acc_20_fu_747_p2 <= std_logic_vector(unsigned(acc_19_fu_711_p4) + unsigned(zext_ln26_8_fu_743_p1));
    acc_21_fu_918_p4 <= add_ln26_19_fu_904_p2(51 downto 20);
    acc_22_fu_954_p2 <= std_logic_vector(unsigned(acc_21_fu_918_p4) + unsigned(zext_ln26_9_fu_950_p1));
    acc_23_fu_1125_p4 <= add_ln26_21_fu_1111_p2(51 downto 20);
    acc_24_fu_1161_p2 <= std_logic_vector(unsigned(acc_23_fu_1125_p4) + unsigned(zext_ln26_10_fu_1157_p1));
    acc_25_fu_1332_p4 <= add_ln26_23_fu_1318_p2(51 downto 20);
    acc_26_fu_1368_p2 <= std_logic_vector(unsigned(acc_25_fu_1332_p4) + unsigned(zext_ln26_11_fu_1364_p1));
    acc_27_fu_1539_p4 <= add_ln26_25_fu_1525_p2(51 downto 20);
    acc_28_fu_1575_p2 <= std_logic_vector(unsigned(acc_27_fu_1539_p4) + unsigned(zext_ln26_12_fu_1571_p1));
    acc_29_fu_1746_p4 <= add_ln26_27_fu_1732_p2(51 downto 20);
    acc_30_fu_1782_p2 <= std_logic_vector(unsigned(acc_29_fu_1746_p4) + unsigned(zext_ln26_13_fu_1778_p1));
    acc_31_fu_1953_p4 <= add_ln26_29_fu_1939_p2(51 downto 20);
    acc_32_fu_1989_p2 <= std_logic_vector(unsigned(acc_31_fu_1953_p4) + unsigned(zext_ln26_14_fu_1985_p1));
    acc_33_fu_2089_p3 <= 
        select_ln26_29_fu_2075_p3 when (or_ln26_46_fu_2083_p2(0) = '1') else 
        acc_32_fu_1989_p2;
    acc_fu_505_p4 <= add_ln26_fu_491_p2(51 downto 20);
    add_ln23_fu_414_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv10_8));
    add_ln25_2_fu_396_p4 <= ((o & tmp_s_fu_386_p4) & ap_const_lv1_1);
    add_ln26_17_fu_697_p2 <= std_logic_vector(signed(sext_ln26_35_fu_689_p1) + signed(sext_ln26_36_fu_693_p1));
    add_ln26_19_fu_904_p2 <= std_logic_vector(signed(sext_ln26_38_fu_896_p1) + signed(sext_ln26_39_fu_900_p1));
    add_ln26_21_fu_1111_p2 <= std_logic_vector(signed(sext_ln26_41_fu_1103_p1) + signed(sext_ln26_42_fu_1107_p1));
    add_ln26_23_fu_1318_p2 <= std_logic_vector(signed(sext_ln26_44_fu_1310_p1) + signed(sext_ln26_45_fu_1314_p1));
    add_ln26_25_fu_1525_p2 <= std_logic_vector(signed(sext_ln26_47_fu_1517_p1) + signed(sext_ln26_48_fu_1521_p1));
    add_ln26_27_fu_1732_p2 <= std_logic_vector(signed(sext_ln26_50_fu_1724_p1) + signed(sext_ln26_51_fu_1728_p1));
    add_ln26_29_fu_1939_p2 <= std_logic_vector(signed(sext_ln26_53_fu_1931_p1) + signed(sext_ln26_54_fu_1935_p1));
    add_ln26_fu_491_p2 <= std_logic_vector(signed(sext_ln26_32_fu_484_p1) + signed(sext_ln26_33_fu_488_p1));
    add_ln_fu_370_p3 <= (o & lshr_ln_fu_354_p4);
    and_ln26_32_fu_561_p2 <= (xor_ln26_fu_555_p2 and tmp_36_fu_523_p3);
    and_ln26_33_fu_603_p2 <= (xor_ln26_48_fu_579_p2 and or_ln26_24_fu_597_p2);
    and_ln26_34_fu_621_p2 <= (xor_ln26_52_fu_615_p2 and tmp_34_fu_497_p3);
    and_ln26_35_fu_737_p2 <= (tmp_39_fu_721_p3 and tmp_38_fu_703_p3);
    and_ln26_36_fu_767_p2 <= (xor_ln26_53_fu_761_p2 and tmp_40_fu_729_p3);
    and_ln26_37_fu_809_p2 <= (xor_ln26_54_fu_785_p2 and or_ln26_27_fu_803_p2);
    and_ln26_38_fu_827_p2 <= (xor_ln26_58_fu_821_p2 and tmp_38_fu_703_p3);
    and_ln26_39_fu_944_p2 <= (tmp_43_fu_928_p3 and tmp_42_fu_910_p3);
    and_ln26_40_fu_974_p2 <= (xor_ln26_59_fu_968_p2 and tmp_44_fu_936_p3);
    and_ln26_41_fu_1016_p2 <= (xor_ln26_60_fu_992_p2 and or_ln26_30_fu_1010_p2);
    and_ln26_42_fu_1034_p2 <= (xor_ln26_64_fu_1028_p2 and tmp_42_fu_910_p3);
    and_ln26_43_fu_1151_p2 <= (tmp_47_fu_1135_p3 and tmp_46_fu_1117_p3);
    and_ln26_44_fu_1181_p2 <= (xor_ln26_65_fu_1175_p2 and tmp_48_fu_1143_p3);
    and_ln26_45_fu_1223_p2 <= (xor_ln26_66_fu_1199_p2 and or_ln26_33_fu_1217_p2);
    and_ln26_46_fu_1241_p2 <= (xor_ln26_70_fu_1235_p2 and tmp_46_fu_1117_p3);
    and_ln26_47_fu_1358_p2 <= (tmp_51_fu_1342_p3 and tmp_50_fu_1324_p3);
    and_ln26_48_fu_1388_p2 <= (xor_ln26_71_fu_1382_p2 and tmp_52_fu_1350_p3);
    and_ln26_49_fu_1430_p2 <= (xor_ln26_72_fu_1406_p2 and or_ln26_36_fu_1424_p2);
    and_ln26_50_fu_1448_p2 <= (xor_ln26_76_fu_1442_p2 and tmp_50_fu_1324_p3);
    and_ln26_51_fu_1565_p2 <= (tmp_55_fu_1549_p3 and tmp_54_fu_1531_p3);
    and_ln26_52_fu_1595_p2 <= (xor_ln26_77_fu_1589_p2 and tmp_56_fu_1557_p3);
    and_ln26_53_fu_1637_p2 <= (xor_ln26_78_fu_1613_p2 and or_ln26_39_fu_1631_p2);
    and_ln26_54_fu_1655_p2 <= (xor_ln26_82_fu_1649_p2 and tmp_54_fu_1531_p3);
    and_ln26_55_fu_1772_p2 <= (tmp_59_fu_1756_p3 and tmp_58_fu_1738_p3);
    and_ln26_56_fu_1802_p2 <= (xor_ln26_83_fu_1796_p2 and tmp_60_fu_1764_p3);
    and_ln26_57_fu_1844_p2 <= (xor_ln26_84_fu_1820_p2 and or_ln26_42_fu_1838_p2);
    and_ln26_58_fu_1862_p2 <= (xor_ln26_88_fu_1856_p2 and tmp_58_fu_1738_p3);
    and_ln26_59_fu_1979_p2 <= (tmp_63_fu_1963_p3 and tmp_62_fu_1945_p3);
    and_ln26_60_fu_2009_p2 <= (xor_ln26_89_fu_2003_p2 and tmp_64_fu_1971_p3);
    and_ln26_61_fu_2051_p2 <= (xor_ln26_90_fu_2027_p2 and or_ln26_45_fu_2045_p2);
    and_ln26_62_fu_2069_p2 <= (xor_ln26_94_fu_2063_p2 and tmp_62_fu_1945_p3);
    and_ln26_fu_531_p2 <= (tmp_35_fu_515_p3 and tmp_34_fu_497_p3);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, tmp_fu_346_p3)
    begin
        if (((tmp_fu_346_p3 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg, ap_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_106)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_106;
        end if; 
    end process;

    in_act_0_address0 <= zext_ln20_4_fu_462_p1(7 - 1 downto 0);
    in_act_0_address1 <= zext_ln20_fu_364_p1(7 - 1 downto 0);
    in_act_0_ce0 <= in_act_0_ce0_local;

    in_act_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_0_ce0_local <= ap_const_logic_1;
        else 
            in_act_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_0_ce1 <= in_act_0_ce1_local;

    in_act_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_0_ce1_local <= ap_const_logic_1;
        else 
            in_act_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_1_address0 <= zext_ln20_4_fu_462_p1(7 - 1 downto 0);
    in_act_1_address1 <= zext_ln20_fu_364_p1(7 - 1 downto 0);
    in_act_1_ce0 <= in_act_1_ce0_local;

    in_act_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_1_ce0_local <= ap_const_logic_1;
        else 
            in_act_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_1_ce1 <= in_act_1_ce1_local;

    in_act_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_1_ce1_local <= ap_const_logic_1;
        else 
            in_act_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_2_address0 <= zext_ln20_4_fu_462_p1(7 - 1 downto 0);
    in_act_2_address1 <= zext_ln20_reg_2125(7 - 1 downto 0);
    in_act_2_ce0 <= in_act_2_ce0_local;

    in_act_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_2_ce0_local <= ap_const_logic_1;
        else 
            in_act_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_2_ce1 <= in_act_2_ce1_local;

    in_act_2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_2_ce1_local <= ap_const_logic_1;
        else 
            in_act_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_3_address0 <= zext_ln20_4_fu_462_p1(7 - 1 downto 0);
    in_act_3_address1 <= zext_ln20_reg_2125(7 - 1 downto 0);
    in_act_3_ce0 <= in_act_3_ce0_local;

    in_act_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_3_ce0_local <= ap_const_logic_1;
        else 
            in_act_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    in_act_3_ce1 <= in_act_3_ce1_local;

    in_act_3_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_act_3_ce1_local <= ap_const_logic_1;
        else 
            in_act_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    lshr_ln_fu_354_p4 <= ap_sig_allocacmp_i_3(8 downto 2);
    mul_ln26_10_fu_1069_p0 <= mul_ln26_10_fu_1069_p00(25 - 1 downto 0);
    mul_ln26_10_fu_1069_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_3_fu_1053_p3),44));
    mul_ln26_11_fu_1276_p0 <= mul_ln26_11_fu_1276_p00(25 - 1 downto 0);
    mul_ln26_11_fu_1276_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_4_fu_1260_p3),44));
    mul_ln26_12_fu_1483_p0 <= mul_ln26_12_fu_1483_p00(25 - 1 downto 0);
    mul_ln26_12_fu_1483_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_5_fu_1467_p3),44));
    mul_ln26_13_fu_1690_p0 <= mul_ln26_13_fu_1690_p00(25 - 1 downto 0);
    mul_ln26_13_fu_1690_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_6_fu_1674_p3),44));
    mul_ln26_14_fu_1897_p0 <= mul_ln26_14_fu_1897_p00(25 - 1 downto 0);
    mul_ln26_14_fu_1897_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_7_fu_1881_p3),44));
    mul_ln26_8_fu_655_p0 <= mul_ln26_8_fu_655_p00(25 - 1 downto 0);
    mul_ln26_8_fu_655_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_1_fu_640_p3),44));
    mul_ln26_9_fu_862_p0 <= mul_ln26_9_fu_862_p00(25 - 1 downto 0);
    mul_ln26_9_fu_862_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_2_fu_846_p3),44));
    mul_ln26_fu_449_p0 <= mul_ln26_fu_449_p00(25 - 1 downto 0);
    mul_ln26_fu_449_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln26_s_fu_433_p3),44));
    or_ln26_24_fu_597_p2 <= (xor_ln26_50_fu_591_p2 or tmp_37_fu_547_p3);
    or_ln26_25_fu_627_p2 <= (and_ln26_34_fu_621_p2 or and_ln26_33_fu_603_p2);
    or_ln26_27_fu_803_p2 <= (xor_ln26_56_fu_797_p2 or tmp_41_fu_753_p3);
    or_ln26_28_fu_833_p2 <= (and_ln26_38_fu_827_p2 or and_ln26_37_fu_809_p2);
    or_ln26_30_fu_1010_p2 <= (xor_ln26_62_fu_1004_p2 or tmp_45_fu_960_p3);
    or_ln26_31_fu_1040_p2 <= (and_ln26_42_fu_1034_p2 or and_ln26_41_fu_1016_p2);
    or_ln26_32_fu_609_p2 <= (tmp_37_fu_547_p3 or and_ln26_32_fu_561_p2);
    or_ln26_33_fu_1217_p2 <= (xor_ln26_68_fu_1211_p2 or tmp_49_fu_1167_p3);
    or_ln26_34_fu_1247_p2 <= (and_ln26_46_fu_1241_p2 or and_ln26_45_fu_1223_p2);
    or_ln26_35_fu_779_p2 <= (xor_ln26_55_fu_773_p2 or tmp_41_fu_753_p3);
    or_ln26_36_fu_1424_p2 <= (xor_ln26_74_fu_1418_p2 or tmp_53_fu_1374_p3);
    or_ln26_37_fu_1454_p2 <= (and_ln26_50_fu_1448_p2 or and_ln26_49_fu_1430_p2);
    or_ln26_38_fu_815_p2 <= (tmp_41_fu_753_p3 or and_ln26_36_fu_767_p2);
    or_ln26_39_fu_1631_p2 <= (xor_ln26_80_fu_1625_p2 or tmp_57_fu_1581_p3);
    or_ln26_40_fu_1661_p2 <= (and_ln26_54_fu_1655_p2 or and_ln26_53_fu_1637_p2);
    or_ln26_41_fu_986_p2 <= (xor_ln26_61_fu_980_p2 or tmp_45_fu_960_p3);
    or_ln26_42_fu_1838_p2 <= (xor_ln26_86_fu_1832_p2 or tmp_61_fu_1788_p3);
    or_ln26_43_fu_1868_p2 <= (and_ln26_58_fu_1862_p2 or and_ln26_57_fu_1844_p2);
    or_ln26_44_fu_1022_p2 <= (tmp_45_fu_960_p3 or and_ln26_40_fu_974_p2);
    or_ln26_45_fu_2045_p2 <= (xor_ln26_92_fu_2039_p2 or tmp_65_fu_1995_p3);
    or_ln26_46_fu_2083_p2 <= (and_ln26_62_fu_2069_p2 or and_ln26_61_fu_2051_p2);
    or_ln26_47_fu_1193_p2 <= (xor_ln26_67_fu_1187_p2 or tmp_49_fu_1167_p3);
    or_ln26_48_fu_1229_p2 <= (tmp_49_fu_1167_p3 or and_ln26_44_fu_1181_p2);
    or_ln26_49_fu_1400_p2 <= (xor_ln26_73_fu_1394_p2 or tmp_53_fu_1374_p3);
    or_ln26_50_fu_1436_p2 <= (tmp_53_fu_1374_p3 or and_ln26_48_fu_1388_p2);
    or_ln26_51_fu_1607_p2 <= (xor_ln26_79_fu_1601_p2 or tmp_57_fu_1581_p3);
    or_ln26_52_fu_1643_p2 <= (tmp_57_fu_1581_p3 or and_ln26_52_fu_1595_p2);
    or_ln26_53_fu_1814_p2 <= (xor_ln26_85_fu_1808_p2 or tmp_61_fu_1788_p3);
    or_ln26_54_fu_1850_p2 <= (tmp_61_fu_1788_p3 or and_ln26_56_fu_1802_p2);
    or_ln26_55_fu_2021_p2 <= (xor_ln26_91_fu_2015_p2 or tmp_65_fu_1995_p3);
    or_ln26_56_fu_2057_p2 <= (tmp_65_fu_1995_p3 or and_ln26_60_fu_2009_p2);
    or_ln26_fu_573_p2 <= (xor_ln26_49_fu_567_p2 or tmp_37_fu_547_p3);
    or_ln_fu_455_p3 <= (tmp_s_reg_2161 & ap_const_lv1_1);
    p_ZL2w2_0_address0 <= zext_ln25_2_fu_406_p1(15 - 1 downto 0);
    p_ZL2w2_0_address1 <= zext_ln25_fu_378_p1(15 - 1 downto 0);

    p_ZL2w2_0_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_0_ce0_local <= ap_const_logic_1;
        else 
            p_ZL2w2_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL2w2_0_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_0_ce1_local <= ap_const_logic_1;
        else 
            p_ZL2w2_0_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL2w2_1_address0 <= zext_ln25_2_fu_406_p1(15 - 1 downto 0);
    p_ZL2w2_1_address1 <= zext_ln25_fu_378_p1(15 - 1 downto 0);

    p_ZL2w2_1_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_1_ce0_local <= ap_const_logic_1;
        else 
            p_ZL2w2_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL2w2_1_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_1_ce1_local <= ap_const_logic_1;
        else 
            p_ZL2w2_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL2w2_2_address0 <= zext_ln25_2_fu_406_p1(15 - 1 downto 0);
    p_ZL2w2_2_address1 <= zext_ln25_fu_378_p1(15 - 1 downto 0);

    p_ZL2w2_2_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_2_ce0_local <= ap_const_logic_1;
        else 
            p_ZL2w2_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL2w2_2_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_2_ce1_local <= ap_const_logic_1;
        else 
            p_ZL2w2_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_ZL2w2_3_address0 <= zext_ln25_2_fu_406_p1(15 - 1 downto 0);
    p_ZL2w2_3_address1 <= zext_ln25_fu_378_p1(15 - 1 downto 0);

    p_ZL2w2_3_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_3_ce0_local <= ap_const_logic_1;
        else 
            p_ZL2w2_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    p_ZL2w2_3_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_ZL2w2_3_ce1_local <= ap_const_logic_1;
        else 
            p_ZL2w2_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln26_16_fu_673_p3 <= 
        select_ln26_fu_665_p3 when (or_ln26_25_fu_627_p2(0) = '1') else 
        acc_18_fu_541_p2;
    select_ln26_17_fu_872_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_37_fu_809_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_18_fu_880_p3 <= 
        select_ln26_17_fu_872_p3 when (or_ln26_28_fu_833_p2(0) = '1') else 
        acc_20_fu_747_p2;
    select_ln26_19_fu_1079_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_41_fu_1016_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_20_fu_1087_p3 <= 
        select_ln26_19_fu_1079_p3 when (or_ln26_31_fu_1040_p2(0) = '1') else 
        acc_22_fu_954_p2;
    select_ln26_21_fu_1286_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_45_fu_1223_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_22_fu_1294_p3 <= 
        select_ln26_21_fu_1286_p3 when (or_ln26_34_fu_1247_p2(0) = '1') else 
        acc_24_fu_1161_p2;
    select_ln26_23_fu_1493_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_49_fu_1430_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_24_fu_1501_p3 <= 
        select_ln26_23_fu_1493_p3 when (or_ln26_37_fu_1454_p2(0) = '1') else 
        acc_26_fu_1368_p2;
    select_ln26_25_fu_1700_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_53_fu_1637_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_26_fu_1708_p3 <= 
        select_ln26_25_fu_1700_p3 when (or_ln26_40_fu_1661_p2(0) = '1') else 
        acc_28_fu_1575_p2;
    select_ln26_27_fu_1907_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_57_fu_1844_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_28_fu_1915_p3 <= 
        select_ln26_27_fu_1907_p3 when (or_ln26_43_fu_1868_p2(0) = '1') else 
        acc_30_fu_1782_p2;
    select_ln26_29_fu_2075_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_61_fu_2051_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln26_fu_665_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln26_33_fu_603_p2(0) = '1') else 
        ap_const_lv32_80000000;
        sext_ln20_cast_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln20),32));

    sext_ln26_1_fu_640_p3 <= (in_act_1_load_reg_2197 & ap_const_lv10_0);
    sext_ln26_2_fu_846_p3 <= (in_act_2_q1 & ap_const_lv10_0);
        sext_ln26_32_fu_484_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_s_fu_476_p3),53));

        sext_ln26_33_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_reg_2186),53));

        sext_ln26_35_fu_689_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_24_fu_681_p3),53));

        sext_ln26_36_fu_693_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_8_fu_655_p2),53));

        sext_ln26_38_fu_896_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_26_fu_888_p3),53));

        sext_ln26_39_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_9_fu_862_p2),53));

    sext_ln26_3_fu_1053_p3 <= (in_act_3_q1 & ap_const_lv10_0);
        sext_ln26_41_fu_1103_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_28_fu_1095_p3),53));

        sext_ln26_42_fu_1107_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_10_fu_1069_p2),53));

        sext_ln26_44_fu_1310_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_30_fu_1302_p3),53));

        sext_ln26_45_fu_1314_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_11_fu_1276_p2),53));

        sext_ln26_47_fu_1517_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_32_fu_1509_p3),53));

        sext_ln26_48_fu_1521_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_12_fu_1483_p2),53));

    sext_ln26_4_fu_1260_p3 <= (in_act_0_q0 & ap_const_lv10_0);
        sext_ln26_50_fu_1724_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_34_fu_1716_p3),53));

        sext_ln26_51_fu_1728_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_13_fu_1690_p2),53));

        sext_ln26_53_fu_1931_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln26_36_fu_1923_p3),53));

        sext_ln26_54_fu_1935_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln26_14_fu_1897_p2),53));

    sext_ln26_5_fu_1467_p3 <= (in_act_1_q0 & ap_const_lv10_0);
    sext_ln26_6_fu_1674_p3 <= (in_act_2_q0 & ap_const_lv10_0);
    sext_ln26_7_fu_1881_p3 <= (in_act_3_q0 & ap_const_lv10_0);
    sext_ln26_s_fu_433_p3 <= (in_act_0_q1 & ap_const_lv10_0);
    shl_ln26_23_fu_633_p3 <= (weight_8_reg_2192 & ap_const_lv10_0);
    shl_ln26_24_fu_681_p3 <= (select_ln26_16_fu_673_p3 & ap_const_lv20_0);
    shl_ln26_25_fu_839_p3 <= (weight_9_reg_2202 & ap_const_lv10_0);
    shl_ln26_26_fu_888_p3 <= (select_ln26_18_fu_880_p3 & ap_const_lv20_0);
    shl_ln26_27_fu_1046_p3 <= (weight_10_reg_2212 & ap_const_lv10_0);
    shl_ln26_28_fu_1095_p3 <= (select_ln26_20_fu_1087_p3 & ap_const_lv20_0);
    shl_ln26_29_fu_1253_p3 <= (weight_11_reg_2222 & ap_const_lv10_0);
    shl_ln26_30_fu_1302_p3 <= (select_ln26_22_fu_1294_p3 & ap_const_lv20_0);
    shl_ln26_31_fu_1460_p3 <= (weight_12_reg_2232 & ap_const_lv10_0);
    shl_ln26_32_fu_1509_p3 <= (select_ln26_24_fu_1501_p3 & ap_const_lv20_0);
    shl_ln26_33_fu_1667_p3 <= (weight_13_reg_2242 & ap_const_lv10_0);
    shl_ln26_34_fu_1716_p3 <= (select_ln26_26_fu_1708_p3 & ap_const_lv20_0);
    shl_ln26_35_fu_1874_p3 <= (weight_14_reg_2252 & ap_const_lv10_0);
    shl_ln26_36_fu_1923_p3 <= (select_ln26_28_fu_1915_p3 & ap_const_lv20_0);
    shl_ln26_s_fu_476_p3 <= (acc_01_fu_102 & ap_const_lv20_0);
    shl_ln_fu_425_p3 <= (p_ZL2w2_0_q1 & ap_const_lv10_0);
    tmp_34_fu_497_p3 <= add_ln26_fu_491_p2(52 downto 52);
    tmp_35_fu_515_p3 <= zext_ln26_16_fu_473_p1(19 downto 19);
    tmp_36_fu_523_p3 <= add_ln26_fu_491_p2(51 downto 51);
    tmp_37_fu_547_p3 <= acc_18_fu_541_p2(31 downto 31);
    tmp_38_fu_703_p3 <= add_ln26_17_fu_697_p2(52 downto 52);
    tmp_39_fu_721_p3 <= zext_ln26_18_fu_661_p1(19 downto 19);
    tmp_40_fu_729_p3 <= add_ln26_17_fu_697_p2(51 downto 51);
    tmp_41_fu_753_p3 <= acc_20_fu_747_p2(31 downto 31);
    tmp_42_fu_910_p3 <= add_ln26_19_fu_904_p2(52 downto 52);
    tmp_43_fu_928_p3 <= zext_ln26_20_fu_868_p1(19 downto 19);
    tmp_44_fu_936_p3 <= add_ln26_19_fu_904_p2(51 downto 51);
    tmp_45_fu_960_p3 <= acc_22_fu_954_p2(31 downto 31);
    tmp_46_fu_1117_p3 <= add_ln26_21_fu_1111_p2(52 downto 52);
    tmp_47_fu_1135_p3 <= zext_ln26_22_fu_1075_p1(19 downto 19);
    tmp_48_fu_1143_p3 <= add_ln26_21_fu_1111_p2(51 downto 51);
    tmp_49_fu_1167_p3 <= acc_24_fu_1161_p2(31 downto 31);
    tmp_50_fu_1324_p3 <= add_ln26_23_fu_1318_p2(52 downto 52);
    tmp_51_fu_1342_p3 <= zext_ln26_24_fu_1282_p1(19 downto 19);
    tmp_52_fu_1350_p3 <= add_ln26_23_fu_1318_p2(51 downto 51);
    tmp_53_fu_1374_p3 <= acc_26_fu_1368_p2(31 downto 31);
    tmp_54_fu_1531_p3 <= add_ln26_25_fu_1525_p2(52 downto 52);
    tmp_55_fu_1549_p3 <= zext_ln26_26_fu_1489_p1(19 downto 19);
    tmp_56_fu_1557_p3 <= add_ln26_25_fu_1525_p2(51 downto 51);
    tmp_57_fu_1581_p3 <= acc_28_fu_1575_p2(31 downto 31);
    tmp_58_fu_1738_p3 <= add_ln26_27_fu_1732_p2(52 downto 52);
    tmp_59_fu_1756_p3 <= zext_ln26_28_fu_1696_p1(19 downto 19);
    tmp_60_fu_1764_p3 <= add_ln26_27_fu_1732_p2(51 downto 51);
    tmp_61_fu_1788_p3 <= acc_30_fu_1782_p2(31 downto 31);
    tmp_62_fu_1945_p3 <= add_ln26_29_fu_1939_p2(52 downto 52);
    tmp_63_fu_1963_p3 <= zext_ln26_30_fu_1903_p1(19 downto 19);
    tmp_64_fu_1971_p3 <= add_ln26_29_fu_1939_p2(51 downto 51);
    tmp_65_fu_1995_p3 <= acc_32_fu_1989_p2(31 downto 31);
    tmp_fu_346_p3 <= ap_sig_allocacmp_i_3(9 downto 9);
    tmp_s_fu_386_p4 <= ap_sig_allocacmp_i_3(8 downto 3);
    xor_ln26_48_fu_579_p2 <= (tmp_34_fu_497_p3 xor ap_const_lv1_1);
    xor_ln26_49_fu_567_p2 <= (tmp_36_fu_523_p3 xor ap_const_lv1_1);
    xor_ln26_50_fu_591_p2 <= (xor_ln26_51_fu_585_p2 xor tmp_34_fu_497_p3);
    xor_ln26_51_fu_585_p2 <= (or_ln26_fu_573_p2 xor ap_const_lv1_1);
    xor_ln26_52_fu_615_p2 <= (or_ln26_32_fu_609_p2 xor ap_const_lv1_1);
    xor_ln26_53_fu_761_p2 <= (tmp_41_fu_753_p3 xor ap_const_lv1_1);
    xor_ln26_54_fu_785_p2 <= (tmp_38_fu_703_p3 xor ap_const_lv1_1);
    xor_ln26_55_fu_773_p2 <= (tmp_40_fu_729_p3 xor ap_const_lv1_1);
    xor_ln26_56_fu_797_p2 <= (xor_ln26_57_fu_791_p2 xor tmp_38_fu_703_p3);
    xor_ln26_57_fu_791_p2 <= (or_ln26_35_fu_779_p2 xor ap_const_lv1_1);
    xor_ln26_58_fu_821_p2 <= (or_ln26_38_fu_815_p2 xor ap_const_lv1_1);
    xor_ln26_59_fu_968_p2 <= (tmp_45_fu_960_p3 xor ap_const_lv1_1);
    xor_ln26_60_fu_992_p2 <= (tmp_42_fu_910_p3 xor ap_const_lv1_1);
    xor_ln26_61_fu_980_p2 <= (tmp_44_fu_936_p3 xor ap_const_lv1_1);
    xor_ln26_62_fu_1004_p2 <= (xor_ln26_63_fu_998_p2 xor tmp_42_fu_910_p3);
    xor_ln26_63_fu_998_p2 <= (or_ln26_41_fu_986_p2 xor ap_const_lv1_1);
    xor_ln26_64_fu_1028_p2 <= (or_ln26_44_fu_1022_p2 xor ap_const_lv1_1);
    xor_ln26_65_fu_1175_p2 <= (tmp_49_fu_1167_p3 xor ap_const_lv1_1);
    xor_ln26_66_fu_1199_p2 <= (tmp_46_fu_1117_p3 xor ap_const_lv1_1);
    xor_ln26_67_fu_1187_p2 <= (tmp_48_fu_1143_p3 xor ap_const_lv1_1);
    xor_ln26_68_fu_1211_p2 <= (xor_ln26_69_fu_1205_p2 xor tmp_46_fu_1117_p3);
    xor_ln26_69_fu_1205_p2 <= (or_ln26_47_fu_1193_p2 xor ap_const_lv1_1);
    xor_ln26_70_fu_1235_p2 <= (or_ln26_48_fu_1229_p2 xor ap_const_lv1_1);
    xor_ln26_71_fu_1382_p2 <= (tmp_53_fu_1374_p3 xor ap_const_lv1_1);
    xor_ln26_72_fu_1406_p2 <= (tmp_50_fu_1324_p3 xor ap_const_lv1_1);
    xor_ln26_73_fu_1394_p2 <= (tmp_52_fu_1350_p3 xor ap_const_lv1_1);
    xor_ln26_74_fu_1418_p2 <= (xor_ln26_75_fu_1412_p2 xor tmp_50_fu_1324_p3);
    xor_ln26_75_fu_1412_p2 <= (or_ln26_49_fu_1400_p2 xor ap_const_lv1_1);
    xor_ln26_76_fu_1442_p2 <= (or_ln26_50_fu_1436_p2 xor ap_const_lv1_1);
    xor_ln26_77_fu_1589_p2 <= (tmp_57_fu_1581_p3 xor ap_const_lv1_1);
    xor_ln26_78_fu_1613_p2 <= (tmp_54_fu_1531_p3 xor ap_const_lv1_1);
    xor_ln26_79_fu_1601_p2 <= (tmp_56_fu_1557_p3 xor ap_const_lv1_1);
    xor_ln26_80_fu_1625_p2 <= (xor_ln26_81_fu_1619_p2 xor tmp_54_fu_1531_p3);
    xor_ln26_81_fu_1619_p2 <= (or_ln26_51_fu_1607_p2 xor ap_const_lv1_1);
    xor_ln26_82_fu_1649_p2 <= (or_ln26_52_fu_1643_p2 xor ap_const_lv1_1);
    xor_ln26_83_fu_1796_p2 <= (tmp_61_fu_1788_p3 xor ap_const_lv1_1);
    xor_ln26_84_fu_1820_p2 <= (tmp_58_fu_1738_p3 xor ap_const_lv1_1);
    xor_ln26_85_fu_1808_p2 <= (tmp_60_fu_1764_p3 xor ap_const_lv1_1);
    xor_ln26_86_fu_1832_p2 <= (xor_ln26_87_fu_1826_p2 xor tmp_58_fu_1738_p3);
    xor_ln26_87_fu_1826_p2 <= (or_ln26_53_fu_1814_p2 xor ap_const_lv1_1);
    xor_ln26_88_fu_1856_p2 <= (or_ln26_54_fu_1850_p2 xor ap_const_lv1_1);
    xor_ln26_89_fu_2003_p2 <= (tmp_65_fu_1995_p3 xor ap_const_lv1_1);
    xor_ln26_90_fu_2027_p2 <= (tmp_62_fu_1945_p3 xor ap_const_lv1_1);
    xor_ln26_91_fu_2015_p2 <= (tmp_64_fu_1971_p3 xor ap_const_lv1_1);
    xor_ln26_92_fu_2039_p2 <= (xor_ln26_93_fu_2033_p2 xor tmp_62_fu_1945_p3);
    xor_ln26_93_fu_2033_p2 <= (or_ln26_55_fu_2021_p2 xor ap_const_lv1_1);
    xor_ln26_94_fu_2063_p2 <= (or_ln26_56_fu_2057_p2 xor ap_const_lv1_1);
    xor_ln26_fu_555_p2 <= (tmp_37_fu_547_p3 xor ap_const_lv1_1);
    zext_ln20_4_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_455_p3),64));
    zext_ln20_fu_364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_354_p4),64));
    zext_ln25_2_fu_406_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln25_2_fu_396_p4),64));
    zext_ln25_fu_378_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_370_p3),64));
    zext_ln26_10_fu_1157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_43_fu_1151_p2),32));
    zext_ln26_11_fu_1364_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_47_fu_1358_p2),32));
    zext_ln26_12_fu_1571_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_51_fu_1565_p2),32));
    zext_ln26_13_fu_1778_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_55_fu_1772_p2),32));
    zext_ln26_14_fu_1985_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_59_fu_1979_p2),32));
    zext_ln26_16_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_reg_2186),45));
    zext_ln26_18_fu_661_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_8_fu_655_p2),45));
    zext_ln26_20_fu_868_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_9_fu_862_p2),45));
    zext_ln26_22_fu_1075_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_10_fu_1069_p2),45));
    zext_ln26_24_fu_1282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_11_fu_1276_p2),45));
    zext_ln26_26_fu_1489_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_12_fu_1483_p2),45));
    zext_ln26_28_fu_1696_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_13_fu_1690_p2),45));
    zext_ln26_30_fu_1903_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_ln26_14_fu_1897_p2),45));
    zext_ln26_8_fu_743_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_35_fu_737_p2),32));
    zext_ln26_9_fu_950_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_39_fu_944_p2),32));
    zext_ln26_fu_537_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln26_fu_531_p2),32));
end behav;
