-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mlp_top_dense_relu_128_10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_act_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_0_ce0 : OUT STD_LOGIC;
    in_act_0_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_0_ce1 : OUT STD_LOGIC;
    in_act_0_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_1_ce0 : OUT STD_LOGIC;
    in_act_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_1_ce1 : OUT STD_LOGIC;
    in_act_1_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_2_ce0 : OUT STD_LOGIC;
    in_act_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_2_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_2_ce1 : OUT STD_LOGIC;
    in_act_2_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_3_ce0 : OUT STD_LOGIC;
    in_act_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    in_act_3_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    in_act_3_ce1 : OUT STD_LOGIC;
    in_act_3_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    out_act_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    out_act_ce0 : OUT STD_LOGIC;
    out_act_we0 : OUT STD_LOGIC;
    out_act_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of mlp_top_dense_relu_128_10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal bias_38_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal bias_38_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal o_5_reg_426 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal zext_ln19_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln19_reg_434 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_171_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal acc_reg_444 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln30_fu_243_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln30_reg_449 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal and_ln30_7_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_7_reg_454 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln30_6_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln30_6_reg_459 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_done : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_idle : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_ready : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_ce0 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_ce1 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_ce0 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_ce1 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_ce0 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_ce1 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_ce0 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_address1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_ce1 : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out_ap_vld : STD_LOGIC;
    signal grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln19_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal o_fu_84 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln19_fu_155_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal bias_38_ce0_local : STD_LOGIC;
    signal out_act_we0_local : STD_LOGIC;
    signal select_ln30_3_fu_406_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_act_ce0_local : STD_LOGIC;
    signal trunc_ln30_fu_209_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_183_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_fu_213_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln30_fu_227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_134_fu_201_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_fu_233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_191_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln30_fu_239_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_136_fu_249_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_135_fu_219_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln30_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_fu_277_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_291_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal and_ln30_4_fu_263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_8_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_9_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_137_fu_269_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln30_7_fu_285_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln30_4_fu_319_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_5_fu_325_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln30_fu_311_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln30_5_fu_345_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln30_4_fu_351_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln30_6_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln30_1_fu_331_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_6_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_8_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln30_5_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln30_7_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln30_9_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln30_2_fu_399_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component mlp_top_dense_relu_128_10_Pipeline_INNER IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln20 : IN STD_LOGIC_VECTOR (17 downto 0);
        o : IN STD_LOGIC_VECTOR (3 downto 0);
        in_act_0_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_0_ce0 : OUT STD_LOGIC;
        in_act_0_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_0_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_0_ce1 : OUT STD_LOGIC;
        in_act_0_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_1_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_1_ce0 : OUT STD_LOGIC;
        in_act_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_1_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_1_ce1 : OUT STD_LOGIC;
        in_act_1_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_2_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_2_ce0 : OUT STD_LOGIC;
        in_act_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_2_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_2_ce1 : OUT STD_LOGIC;
        in_act_2_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_3_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_3_ce0 : OUT STD_LOGIC;
        in_act_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        in_act_3_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
        in_act_3_ce1 : OUT STD_LOGIC;
        in_act_3_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
        acc_01_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        acc_01_out_ap_vld : OUT STD_LOGIC );
    end component;


    component mlp_top_dense_relu_128_10_s_bias_38_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    bias_38_U : component mlp_top_dense_relu_128_10_s_bias_38_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 10,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => bias_38_address0,
        ce0 => bias_38_ce0_local,
        q0 => bias_38_q0);

    grp_dense_relu_128_10_Pipeline_INNER_fu_118 : component mlp_top_dense_relu_128_10_Pipeline_INNER
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start,
        ap_done => grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_done,
        ap_idle => grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_idle,
        ap_ready => grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_ready,
        sext_ln20 => acc_reg_444,
        o => o_5_reg_426,
        in_act_0_address0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_address0,
        in_act_0_ce0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_ce0,
        in_act_0_q0 => in_act_0_q0,
        in_act_0_address1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_address1,
        in_act_0_ce1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_ce1,
        in_act_0_q1 => in_act_0_q1,
        in_act_1_address0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_address0,
        in_act_1_ce0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_ce0,
        in_act_1_q0 => in_act_1_q0,
        in_act_1_address1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_address1,
        in_act_1_ce1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_ce1,
        in_act_1_q1 => in_act_1_q1,
        in_act_2_address0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_address0,
        in_act_2_ce0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_ce0,
        in_act_2_q0 => in_act_2_q0,
        in_act_2_address1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_address1,
        in_act_2_ce1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_ce1,
        in_act_2_q1 => in_act_2_q1,
        in_act_3_address0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_address0,
        in_act_3_ce0 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_ce0,
        in_act_3_q0 => in_act_3_q0,
        in_act_3_address1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_address1,
        in_act_3_ce1 => grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_ce1,
        in_act_3_q1 => in_act_3_q1,
        acc_01_out => grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out,
        acc_01_out_ap_vld => grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    o_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                o_fu_84 <= ap_const_lv4_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln19_fu_149_p2 = ap_const_lv1_0))) then 
                o_fu_84 <= add_ln19_fu_155_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    acc_reg_444(17 downto 10) <= acc_fu_171_p3(17 downto 10);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln30_reg_449 <= add_ln30_fu_243_p2;
                and_ln30_7_reg_454 <= and_ln30_7_fu_363_p2;
                or_ln30_6_reg_459 <= or_ln30_6_fu_393_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                o_5_reg_426 <= o_fu_84;
                    zext_ln19_reg_434(3 downto 0) <= zext_ln19_fu_161_p1(3 downto 0);
            end if;
        end if;
    end process;
    zext_ln19_reg_434(63 downto 4) <= "000000000000000000000000000000000000000000000000000000000000";
    acc_reg_444(9 downto 0) <= "0000000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_done, ap_CS_fsm_state4, icmp_ln19_fu_149_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln19_fu_149_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    acc_fu_171_p3 <= (bias_38_q0 & ap_const_lv10_0);
    add_ln19_fu_155_p2 <= std_logic_vector(unsigned(o_fu_84) + unsigned(ap_const_lv4_1));
    add_ln30_fu_243_p2 <= std_logic_vector(unsigned(trunc_ln_fu_191_p4) + unsigned(zext_ln30_fu_239_p1));
    and_ln30_4_fu_263_p2 <= (xor_ln30_fu_257_p2 and tmp_135_fu_219_p3);
    and_ln30_5_fu_325_p2 <= (xor_ln30_4_fu_319_p2 and icmp_ln30_7_fu_285_p2);
    and_ln30_6_fu_339_p2 <= (icmp_ln30_8_fu_299_p2 and and_ln30_4_fu_263_p2);
    and_ln30_7_fu_363_p2 <= (xor_ln30_6_fu_357_p2 and or_ln30_4_fu_351_p2);
    and_ln30_8_fu_369_p2 <= (tmp_136_fu_249_p3 and select_ln30_1_fu_331_p3);
    and_ln30_9_fu_387_p2 <= (xor_ln30_7_fu_381_p2 and tmp_fu_183_p3);
    and_ln30_fu_233_p2 <= (tmp_134_fu_201_p3 and or_ln30_fu_227_p2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_done)
    begin
        if ((grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln19_fu_149_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln19_fu_149_p2 = ap_const_lv1_1)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln19_fu_149_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln19_fu_149_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bias_38_address0 <= zext_ln19_fu_161_p1(4 - 1 downto 0);

    bias_38_ce0_local_assign_proc : process(ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            bias_38_ce0_local <= ap_const_logic_1;
        else 
            bias_38_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_ap_start_reg;
    icmp_ln19_fu_149_p2 <= "1" when (o_fu_84 = ap_const_lv4_A) else "0";
    icmp_ln30_7_fu_285_p2 <= "1" when (tmp_s_fu_277_p3 = ap_const_lv5_1F) else "0";
    icmp_ln30_8_fu_299_p2 <= "1" when (tmp_1_fu_291_p3 = ap_const_lv6_3F) else "0";
    icmp_ln30_9_fu_305_p2 <= "1" when (tmp_1_fu_291_p3 = ap_const_lv6_0) else "0";
    icmp_ln30_fu_213_p2 <= "0" when (trunc_ln30_fu_209_p1 = ap_const_lv9_0) else "1";
    in_act_0_address0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_address0;
    in_act_0_address1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_address1;
    in_act_0_ce0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_ce0;
    in_act_0_ce1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_0_ce1;
    in_act_1_address0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_address0;
    in_act_1_address1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_address1;
    in_act_1_ce0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_ce0;
    in_act_1_ce1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_1_ce1;
    in_act_2_address0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_address0;
    in_act_2_address1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_address1;
    in_act_2_ce0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_ce0;
    in_act_2_ce1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_2_ce1;
    in_act_3_address0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_address0;
    in_act_3_address1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_address1;
    in_act_3_ce0 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_ce0;
    in_act_3_ce1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_in_act_3_ce1;
    or_ln30_4_fu_351_p2 <= (xor_ln30_5_fu_345_p2 or tmp_136_fu_249_p3);
    or_ln30_5_fu_375_p2 <= (and_ln30_8_fu_369_p2 or and_ln30_6_fu_339_p2);
    or_ln30_6_fu_393_p2 <= (and_ln30_9_fu_387_p2 or and_ln30_7_fu_363_p2);
    or_ln30_fu_227_p2 <= (tmp_fu_183_p3 or icmp_ln30_fu_213_p2);
    out_act_address0 <= zext_ln19_reg_434(4 - 1 downto 0);
    out_act_ce0 <= out_act_ce0_local;

    out_act_ce0_local_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_act_ce0_local <= ap_const_logic_1;
        else 
            out_act_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    out_act_d0 <= select_ln30_3_fu_406_p3;
    out_act_we0 <= out_act_we0_local;

    out_act_we0_local_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            out_act_we0_local <= ap_const_logic_1;
        else 
            out_act_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln30_1_fu_331_p3 <= 
        and_ln30_5_fu_325_p2 when (and_ln30_4_fu_263_p2(0) = '1') else 
        icmp_ln30_8_fu_299_p2;
    select_ln30_2_fu_399_p3 <= 
        ap_const_lv16_7FFF when (and_ln30_7_reg_454(0) = '1') else 
        ap_const_lv16_8000;
    select_ln30_3_fu_406_p3 <= 
        select_ln30_2_fu_399_p3 when (or_ln30_6_reg_459(0) = '1') else 
        add_ln30_reg_449;
    select_ln30_fu_311_p3 <= 
        icmp_ln30_8_fu_299_p2 when (and_ln30_4_fu_263_p2(0) = '1') else 
        icmp_ln30_9_fu_305_p2;
    tmp_134_fu_201_p3 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(9 downto 9);
    tmp_135_fu_219_p3 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(25 downto 25);
    tmp_136_fu_249_p3 <= add_ln30_fu_243_p2(15 downto 15);
    tmp_137_fu_269_p3 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(26 downto 26);
    tmp_1_fu_291_p3 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(31 downto 26);
    tmp_fu_183_p3 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(31 downto 31);
    tmp_s_fu_277_p3 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(31 downto 27);
    trunc_ln30_fu_209_p1 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(9 - 1 downto 0);
    trunc_ln_fu_191_p4 <= grp_dense_relu_128_10_Pipeline_INNER_fu_118_acc_01_out(25 downto 10);
    xor_ln30_4_fu_319_p2 <= (tmp_137_fu_269_p3 xor ap_const_lv1_1);
    xor_ln30_5_fu_345_p2 <= (select_ln30_fu_311_p3 xor ap_const_lv1_1);
    xor_ln30_6_fu_357_p2 <= (tmp_fu_183_p3 xor ap_const_lv1_1);
    xor_ln30_7_fu_381_p2 <= (or_ln30_5_fu_375_p2 xor ap_const_lv1_1);
    xor_ln30_fu_257_p2 <= (tmp_136_fu_249_p3 xor ap_const_lv1_1);
    zext_ln19_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(o_fu_84),64));
    zext_ln30_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln30_fu_233_p2),16));
end behav;
