-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_top_cnn_top_Pipeline_POOL1_CH_POOL1_R_POOL1_C is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv1_buf_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_buf_ce0 : OUT STD_LOGIC;
    conv1_buf_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv1_buf_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_buf_ce1 : OUT STD_LOGIC;
    conv1_buf_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv1_buf_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_buf_1_ce0 : OUT STD_LOGIC;
    conv1_buf_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv1_buf_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv1_buf_1_ce1 : OUT STD_LOGIC;
    conv1_buf_1_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    pool1_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    pool1_buf_ce0 : OUT STD_LOGIC;
    pool1_buf_we0 : OUT STD_LOGIC;
    pool1_buf_d0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of cnn_top_cnn_top_Pipeline_POOL1_CH_POOL1_R_POOL1_C is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv11_620 : STD_LOGIC_VECTOR (10 downto 0) := "11000100000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln142_fu_179_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln143_fu_194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln143_reg_612 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln142_1_fu_263_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln142_1_reg_620 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_3_mid2_fu_281_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_3_mid2_reg_626 : STD_LOGIC_VECTOR (3 downto 0);
    signal c_3_mid2_reg_626_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln143_fu_289_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln143_reg_632 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln149_fu_317_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln149_reg_638 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln149_fu_335_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln149_reg_643 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln149_fu_341_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln149_reg_648 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln153_fu_393_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln153_reg_653 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln153_fu_399_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln153_reg_658 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln149_3_fu_488_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln149_3_reg_668 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln153_1_fu_526_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln153_1_reg_688 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln153_1_reg_688_pp0_iter4_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal max_val_5_fu_538_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal max_val_5_reg_693 : STD_LOGIC_VECTOR (14 downto 0);
    signal max_val_7_fu_551_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal max_val_7_reg_699 : STD_LOGIC_VECTOR (14 downto 0);
    signal val_7_reg_705 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln149_7_fu_482_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln149_8_fu_521_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln153_3_fu_558_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_68 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln144_fu_345_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_72 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten39_fu_76 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln143_1_fu_206_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten39_load : STD_LOGIC_VECTOR (7 downto 0);
    signal ch_fu_80 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten52_fu_84 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal add_ln142_1_fu_185_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_sig_allocacmp_indvar_flatten52_load : STD_LOGIC_VECTOR (10 downto 0);
    signal conv1_buf_ce1_local : STD_LOGIC;
    signal conv1_buf_ce0_local : STD_LOGIC;
    signal conv1_buf_1_ce1_local : STD_LOGIC;
    signal conv1_buf_1_ce0_local : STD_LOGIC;
    signal pool1_buf_we0_local : STD_LOGIC;
    signal max_val_8_fu_566_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal pool1_buf_ce0_local : STD_LOGIC;
    signal add_ln143_1_fu_200_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln144_fu_251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln142_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln142_fu_233_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln142_fu_239_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln142_fu_257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_276_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln143_fu_270_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_305_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_297_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln149_fu_313_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_4_fu_323_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln149_1_fu_331_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_6_fu_373_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl2_fu_366_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln153_fu_380_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln153_fu_384_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln153_1_fu_390_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_fu_403_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_10_fu_410_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln149_2_fu_417_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_5_fu_427_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln149_3_fu_434_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln149_1_fu_438_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln149_1_fu_443_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_447_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_12_fu_455_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln149_4_fu_463_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln149_1_fu_421_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln149_6_fu_473_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln149_2_fu_476_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_ln144_fu_467_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_7_fu_494_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_501_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln153_2_fu_508_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln153_1_fu_512_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln149_5_fu_518_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal icmp_ln150_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln150_2_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    c_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_68 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    c_fu_68 <= add_ln144_fu_345_p2;
                end if;
            end if; 
        end if;
    end process;

    ch_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ch_fu_80 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ch_fu_80 <= select_ln142_1_fu_263_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten39_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln142_fu_179_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten39_fu_76 <= select_ln143_1_fu_206_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten39_fu_76 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten52_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln142_fu_179_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten52_fu_84 <= add_ln142_1_fu_185_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten52_fu_84 <= ap_const_lv11_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_72 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    r_fu_72 <= select_ln143_fu_289_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln149_3_reg_668 <= add_ln149_3_fu_488_p2;
                add_ln153_1_reg_688 <= add_ln153_1_fu_526_p2;
                add_ln153_1_reg_688_pp0_iter4_reg <= add_ln153_1_reg_688;
                add_ln153_reg_653 <= add_ln153_fu_393_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                c_3_mid2_reg_626_pp0_iter2_reg <= c_3_mid2_reg_626;
                max_val_5_reg_693 <= max_val_5_fu_538_p3;
                max_val_7_reg_699 <= max_val_7_fu_551_p3;
                trunc_ln153_reg_658 <= trunc_ln153_fu_399_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    add_ln149_reg_643(8 downto 1) <= add_ln149_fu_335_p2(8 downto 1);
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                c_3_mid2_reg_626 <= c_3_mid2_fu_281_p3;
                icmp_ln143_reg_612 <= icmp_ln143_fu_194_p2;
                select_ln142_1_reg_620 <= select_ln142_1_fu_263_p3;
                select_ln143_reg_632 <= select_ln143_fu_289_p3;
                    sub_ln149_reg_638(8 downto 2) <= sub_ln149_fu_317_p2(8 downto 2);
                    trunc_ln149_reg_648(7 downto 1) <= trunc_ln149_fu_341_p1(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                val_7_reg_705 <= conv1_buf_1_q0;
            end if;
        end if;
    end process;
    sub_ln149_reg_638(1 downto 0) <= "00";
    add_ln149_reg_643(0) <= '0';
    trunc_ln149_reg_648(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln142_1_fu_185_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten52_load) + unsigned(ap_const_lv11_1));
    add_ln142_fu_233_p2 <= std_logic_vector(unsigned(ch_fu_80) + unsigned(ap_const_lv4_1));
    add_ln143_1_fu_200_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten39_load) + unsigned(ap_const_lv8_1));
    add_ln143_fu_270_p2 <= std_logic_vector(unsigned(select_ln142_fu_239_p3) + unsigned(ap_const_lv4_1));
    add_ln144_fu_345_p2 <= std_logic_vector(unsigned(c_3_mid2_fu_281_p3) + unsigned(ap_const_lv4_1));
    add_ln149_1_fu_438_p2 <= std_logic_vector(unsigned(sub_ln149_reg_638) + unsigned(zext_ln149_3_fu_434_p1));
    add_ln149_2_fu_476_p2 <= std_logic_vector(unsigned(sub_ln149_1_fu_421_p2) + unsigned(zext_ln149_6_fu_473_p1));
    add_ln149_3_fu_488_p2 <= std_logic_vector(unsigned(sub_ln144_fu_467_p2) + unsigned(zext_ln149_6_fu_473_p1));
    add_ln149_fu_335_p2 <= std_logic_vector(unsigned(sub_ln149_fu_317_p2) + unsigned(zext_ln149_1_fu_331_p1));
    add_ln153_1_fu_526_p2 <= std_logic_vector(unsigned(sub_ln153_1_fu_512_p2) + unsigned(zext_ln149_5_fu_518_p1));
    add_ln153_fu_393_p2 <= std_logic_vector(unsigned(sub_ln153_fu_384_p2) + unsigned(zext_ln153_1_fu_390_p1));
    and_ln142_fu_257_p2 <= (xor_ln142_fu_246_p2 and icmp_ln144_fu_251_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln142_fu_179_p2)
    begin
        if (((icmp_ln142_fu_179_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten39_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten39_fu_76)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten39_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten39_load <= indvar_flatten39_fu_76;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten52_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten52_fu_84)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten52_load <= ap_const_lv11_0;
        else 
            ap_sig_allocacmp_indvar_flatten52_load <= indvar_flatten52_fu_84;
        end if; 
    end process;

    c_3_mid2_fu_281_p3 <= 
        ap_const_lv4_0 when (empty_fu_276_p2(0) = '1') else 
        c_fu_68;
    conv1_buf_1_address0 <= zext_ln149_8_fu_521_p1(12 - 1 downto 0);
    conv1_buf_1_address1 <= zext_ln149_7_fu_482_p1(12 - 1 downto 0);
    conv1_buf_1_ce0 <= conv1_buf_1_ce0_local;

    conv1_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv1_buf_1_ce0_local <= ap_const_logic_1;
        else 
            conv1_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_buf_1_ce1 <= conv1_buf_1_ce1_local;

    conv1_buf_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv1_buf_1_ce1_local <= ap_const_logic_1;
        else 
            conv1_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_buf_address0 <= zext_ln149_8_fu_521_p1(12 - 1 downto 0);
    conv1_buf_address1 <= zext_ln149_7_fu_482_p1(12 - 1 downto 0);
    conv1_buf_ce0 <= conv1_buf_ce0_local;

    conv1_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv1_buf_ce0_local <= ap_const_logic_1;
        else 
            conv1_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv1_buf_ce1 <= conv1_buf_ce1_local;

    conv1_buf_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv1_buf_ce1_local <= ap_const_logic_1;
        else 
            conv1_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_276_p2 <= (icmp_ln143_reg_612 or and_ln142_fu_257_p2);
    icmp_ln142_fu_179_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten52_load = ap_const_lv11_620) else "0";
    icmp_ln143_fu_194_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten39_load = ap_const_lv8_C4) else "0";
    icmp_ln144_fu_251_p2 <= "1" when (c_fu_68 = ap_const_lv4_E) else "0";
    icmp_ln150_1_fu_546_p2 <= "1" when (unsigned(conv1_buf_q0) > unsigned(max_val_5_reg_693)) else "0";
    icmp_ln150_2_fu_562_p2 <= "1" when (unsigned(val_7_reg_705) > unsigned(max_val_7_reg_699)) else "0";
    icmp_ln150_fu_532_p2 <= "1" when (unsigned(conv1_buf_1_q1) > unsigned(conv1_buf_q1)) else "0";
    max_val_5_fu_538_p3 <= 
        conv1_buf_1_q1 when (icmp_ln150_fu_532_p2(0) = '1') else 
        conv1_buf_q1;
    max_val_7_fu_551_p3 <= 
        conv1_buf_q0 when (icmp_ln150_1_fu_546_p2(0) = '1') else 
        max_val_5_reg_693;
    max_val_8_fu_566_p3 <= 
        val_7_reg_705 when (icmp_ln150_2_fu_562_p2(0) = '1') else 
        max_val_7_reg_699;
    p_shl2_fu_366_p3 <= (select_ln142_1_reg_620 & ap_const_lv4_0);
    p_shl_fu_297_p3 <= (select_ln142_1_fu_263_p3 & ap_const_lv5_0);
    pool1_buf_address0 <= zext_ln153_3_fu_558_p1(11 - 1 downto 0);
    pool1_buf_ce0 <= pool1_buf_ce0_local;

    pool1_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pool1_buf_ce0_local <= ap_const_logic_1;
        else 
            pool1_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool1_buf_d0 <= max_val_8_fu_566_p3;
    pool1_buf_we0 <= pool1_buf_we0_local;

    pool1_buf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pool1_buf_we0_local <= ap_const_logic_1;
        else 
            pool1_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln142_1_fu_263_p3 <= 
        add_ln142_fu_233_p2 when (icmp_ln143_reg_612(0) = '1') else 
        ch_fu_80;
    select_ln142_fu_239_p3 <= 
        ap_const_lv4_0 when (icmp_ln143_reg_612(0) = '1') else 
        r_fu_72;
    select_ln143_1_fu_206_p3 <= 
        ap_const_lv8_1 when (icmp_ln143_fu_194_p2(0) = '1') else 
        add_ln143_1_fu_200_p2;
    select_ln143_fu_289_p3 <= 
        add_ln143_fu_270_p2 when (and_ln142_fu_257_p2(0) = '1') else 
        select_ln142_fu_239_p3;
    sub_ln144_fu_467_p2 <= std_logic_vector(unsigned(tmp_12_fu_455_p3) - unsigned(zext_ln149_4_fu_463_p1));
    sub_ln149_1_fu_421_p2 <= std_logic_vector(unsigned(tmp_10_fu_410_p3) - unsigned(zext_ln149_2_fu_417_p1));
    sub_ln149_fu_317_p2 <= std_logic_vector(unsigned(p_shl_fu_297_p3) - unsigned(zext_ln149_fu_313_p1));
    sub_ln153_1_fu_512_p2 <= std_logic_vector(unsigned(tmp_8_fu_501_p3) - unsigned(zext_ln153_2_fu_508_p1));
    sub_ln153_fu_384_p2 <= std_logic_vector(unsigned(p_shl2_fu_366_p3) - unsigned(zext_ln153_fu_380_p1));
    tmp_10_fu_410_p3 <= (trunc_ln149_reg_648 & ap_const_lv4_0);
    tmp_11_fu_447_p3 <= (add_ln149_1_fu_438_p2 & ap_const_lv1_0);
    tmp_12_fu_455_p3 <= (trunc_ln149_1_fu_443_p1 & ap_const_lv4_0);
    tmp_4_fu_323_p3 <= (select_ln143_fu_289_p3 & ap_const_lv1_0);
    tmp_5_fu_427_p3 <= (select_ln143_reg_632 & ap_const_lv1_1);
    tmp_6_fu_373_p3 <= (select_ln142_1_reg_620 & ap_const_lv1_0);
    tmp_7_fu_494_p3 <= (add_ln153_reg_653 & ap_const_lv1_0);
    tmp_8_fu_501_p3 <= (trunc_ln153_reg_658 & ap_const_lv4_0);
    tmp_9_fu_403_p3 <= (add_ln149_reg_643 & ap_const_lv1_0);
    tmp_fu_305_p3 <= (select_ln142_1_fu_263_p3 & ap_const_lv2_0);
    trunc_ln149_1_fu_443_p1 <= add_ln149_1_fu_438_p2(8 - 1 downto 0);
    trunc_ln149_fu_341_p1 <= add_ln149_fu_335_p2(8 - 1 downto 0);
    trunc_ln153_fu_399_p1 <= add_ln153_fu_393_p2(7 - 1 downto 0);
    xor_ln142_fu_246_p2 <= (icmp_ln143_reg_612 xor ap_const_lv1_1);
    zext_ln149_1_fu_331_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_323_p3),9));
    zext_ln149_2_fu_417_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_fu_403_p3),12));
    zext_ln149_3_fu_434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_427_p3),9));
    zext_ln149_4_fu_463_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_11_fu_447_p3),12));
    zext_ln149_5_fu_518_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_3_mid2_reg_626_pp0_iter2_reg),11));
    zext_ln149_6_fu_473_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_3_mid2_reg_626),12));
    zext_ln149_7_fu_482_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln149_2_fu_476_p2),64));
    zext_ln149_8_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln149_3_reg_668),64));
    zext_ln149_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_305_p3),9));
    zext_ln153_1_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln143_reg_632),8));
    zext_ln153_2_fu_508_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_fu_494_p3),11));
    zext_ln153_3_fu_558_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln153_1_reg_688_pp0_iter4_reg),64));
    zext_ln153_fu_380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_6_fu_373_p3),8));
end behav;
