-- ==============================================================
-- Generated by Vitis HLS v2025.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_top_cnn_top_Pipeline_POOL2_CH_POOL2_R_POOL2_C is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    conv2_buf_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_buf_ce0 : OUT STD_LOGIC;
    conv2_buf_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_buf_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_buf_ce1 : OUT STD_LOGIC;
    conv2_buf_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_buf_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_buf_1_ce0 : OUT STD_LOGIC;
    conv2_buf_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
    conv2_buf_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    conv2_buf_1_ce1 : OUT STD_LOGIC;
    conv2_buf_1_q1 : IN STD_LOGIC_VECTOR (14 downto 0);
    pool2_buf_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    pool2_buf_ce0 : OUT STD_LOGIC;
    pool2_buf_we0 : OUT STD_LOGIC;
    pool2_buf_d0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
end;


architecture behav of cnn_top_cnn_top_Pipeline_POOL2_CH_POOL2_R_POOL2_C is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_310 : STD_LOGIC_VECTOR (9 downto 0) := "1100010000";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_31 : STD_LOGIC_VECTOR (5 downto 0) := "110001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln187_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln187_1_fu_244_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln187_1_reg_582 : STD_LOGIC_VECTOR (4 downto 0);
    signal c_4_mid2_fu_264_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_4_mid2_reg_588 : STD_LOGIC_VECTOR (2 downto 0);
    signal c_4_mid2_reg_588_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln188_fu_272_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln188_reg_594 : STD_LOGIC_VECTOR (2 downto 0);
    signal sub_ln194_fu_300_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal sub_ln194_reg_600 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln194_fu_318_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln194_reg_605 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln194_fu_324_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln194_reg_610 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln198_fu_387_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln198_reg_615 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln198_fu_393_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln198_reg_620 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln194_3_fu_466_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln194_3_reg_630 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln198_1_fu_496_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln198_1_reg_650 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln198_1_reg_650_pp0_iter4_reg : STD_LOGIC_VECTOR (9 downto 0);
    signal max_val_1_fu_508_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal max_val_1_reg_655 : STD_LOGIC_VECTOR (14 downto 0);
    signal max_val_3_fu_521_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal max_val_3_reg_661 : STD_LOGIC_VECTOR (14 downto 0);
    signal val_2_reg_667 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln194_8_fu_460_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln194_9_fu_491_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln198_2_fu_528_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal c_fu_66 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln189_fu_328_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal r_fu_70 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal indvar_flatten81_fu_74 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal select_ln188_1_fu_340_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ch_fu_78 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal indvar_flatten94_fu_82 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal add_ln187_1_fu_183_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_sig_allocacmp_indvar_flatten94_load : STD_LOGIC_VECTOR (9 downto 0);
    signal conv2_buf_ce1_local : STD_LOGIC;
    signal conv2_buf_ce0_local : STD_LOGIC;
    signal conv2_buf_1_ce1_local : STD_LOGIC;
    signal conv2_buf_1_ce0_local : STD_LOGIC;
    signal pool2_buf_we0_local : STD_LOGIC;
    signal max_val_4_fu_536_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal pool2_buf_ce0_local : STD_LOGIC;
    signal icmp_ln188_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln189_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln187_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln187_fu_206_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln187_fu_218_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal and_ln187_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln188_fu_252_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_288_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_280_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln194_1_fu_296_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_s_fu_306_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln194_2_fu_314_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln188_1_fu_334_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl1_fu_371_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln194_fu_368_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln198_fu_378_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln198_fu_384_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_397_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln194_3_fu_404_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_3_fu_413_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln194_4_fu_420_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln194_1_fu_424_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln194_1_fu_429_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_433_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln194_5_fu_441_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln194_1_fu_407_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln194_7_fu_451_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln194_2_fu_454_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln189_fu_445_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_1_fu_472_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln198_1_fu_479_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal sub_ln198_1_fu_482_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln194_6_fu_488_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln195_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_1_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln195_2_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_top_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component cnn_top_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    c_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_66 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    c_fu_66 <= add_ln189_fu_328_p2;
                end if;
            end if; 
        end if;
    end process;

    ch_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ch_fu_78 <= ap_const_lv5_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ch_fu_78 <= select_ln187_1_fu_244_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten81_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten81_fu_74 <= ap_const_lv6_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    indvar_flatten81_fu_74 <= select_ln188_1_fu_340_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten94_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln187_fu_177_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten94_fu_82 <= add_ln187_1_fu_183_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten94_fu_82 <= ap_const_lv10_0;
                end if;
            end if; 
        end if;
    end process;

    r_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    r_fu_70 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    r_fu_70 <= select_ln188_fu_272_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln194_3_reg_630 <= add_ln194_3_fu_466_p2;
                add_ln198_1_reg_650 <= add_ln198_1_fu_496_p2;
                add_ln198_1_reg_650_pp0_iter4_reg <= add_ln198_1_reg_650;
                add_ln198_reg_615 <= add_ln198_fu_387_p2;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                c_4_mid2_reg_588_pp0_iter2_reg <= c_4_mid2_reg_588;
                max_val_1_reg_655 <= max_val_1_fu_508_p3;
                max_val_3_reg_661 <= max_val_3_fu_521_p3;
                trunc_ln198_reg_620 <= trunc_ln198_fu_393_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                    add_ln194_reg_605(8 downto 1) <= add_ln194_fu_318_p2(8 downto 1);
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                c_4_mid2_reg_588 <= c_4_mid2_fu_264_p3;
                select_ln187_1_reg_582 <= select_ln187_1_fu_244_p3;
                select_ln188_reg_594 <= select_ln188_fu_272_p3;
                    sub_ln194_reg_600(8 downto 1) <= sub_ln194_fu_300_p2(8 downto 1);
                    trunc_ln194_reg_610(7 downto 1) <= trunc_ln194_fu_324_p1(7 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                val_2_reg_667 <= conv2_buf_1_q0;
            end if;
        end if;
    end process;
    sub_ln194_reg_600(0) <= '0';
    add_ln194_reg_605(0) <= '0';
    trunc_ln194_reg_610(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln187_1_fu_183_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten94_load) + unsigned(ap_const_lv10_1));
    add_ln187_fu_206_p2 <= std_logic_vector(unsigned(ch_fu_78) + unsigned(ap_const_lv5_1));
    add_ln188_1_fu_334_p2 <= std_logic_vector(unsigned(indvar_flatten81_fu_74) + unsigned(ap_const_lv6_1));
    add_ln188_fu_252_p2 <= std_logic_vector(unsigned(select_ln187_fu_218_p3) + unsigned(ap_const_lv3_1));
    add_ln189_fu_328_p2 <= std_logic_vector(unsigned(c_4_mid2_fu_264_p3) + unsigned(ap_const_lv3_1));
    add_ln194_1_fu_424_p2 <= std_logic_vector(unsigned(sub_ln194_reg_600) + unsigned(zext_ln194_4_fu_420_p1));
    add_ln194_2_fu_454_p2 <= std_logic_vector(unsigned(sub_ln194_1_fu_407_p2) + unsigned(zext_ln194_7_fu_451_p1));
    add_ln194_3_fu_466_p2 <= std_logic_vector(unsigned(sub_ln189_fu_445_p2) + unsigned(zext_ln194_7_fu_451_p1));
    add_ln194_fu_318_p2 <= std_logic_vector(unsigned(sub_ln194_fu_300_p2) + unsigned(zext_ln194_2_fu_314_p1));
    add_ln198_1_fu_496_p2 <= std_logic_vector(unsigned(sub_ln198_1_fu_482_p2) + unsigned(zext_ln194_6_fu_488_p1));
    add_ln198_fu_387_p2 <= std_logic_vector(unsigned(sub_ln198_fu_378_p2) + unsigned(zext_ln198_fu_384_p1));
    and_ln187_fu_238_p2 <= (xor_ln187_fu_226_p2 and icmp_ln189_fu_232_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln187_fu_177_p2)
    begin
        if (((icmp_ln187_fu_177_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter4_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter4_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten94_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten94_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_indvar_flatten94_load <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_indvar_flatten94_load <= indvar_flatten94_fu_82;
        end if; 
    end process;

    c_4_mid2_fu_264_p3 <= 
        ap_const_lv3_0 when (empty_fu_258_p2(0) = '1') else 
        c_fu_66;
    conv2_buf_1_address0 <= zext_ln194_9_fu_491_p1(11 - 1 downto 0);
    conv2_buf_1_address1 <= zext_ln194_8_fu_460_p1(11 - 1 downto 0);
    conv2_buf_1_ce0 <= conv2_buf_1_ce0_local;

    conv2_buf_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_buf_1_ce0_local <= ap_const_logic_1;
        else 
            conv2_buf_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_buf_1_ce1 <= conv2_buf_1_ce1_local;

    conv2_buf_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv2_buf_1_ce1_local <= ap_const_logic_1;
        else 
            conv2_buf_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_buf_address0 <= zext_ln194_9_fu_491_p1(11 - 1 downto 0);
    conv2_buf_address1 <= zext_ln194_8_fu_460_p1(11 - 1 downto 0);
    conv2_buf_ce0 <= conv2_buf_ce0_local;

    conv2_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then 
            conv2_buf_ce0_local <= ap_const_logic_1;
        else 
            conv2_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_buf_ce1 <= conv2_buf_ce1_local;

    conv2_buf_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            conv2_buf_ce1_local <= ap_const_logic_1;
        else 
            conv2_buf_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_fu_258_p2 <= (icmp_ln188_fu_212_p2 or and_ln187_fu_238_p2);
    icmp_ln187_fu_177_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten94_load = ap_const_lv10_310) else "0";
    icmp_ln188_fu_212_p2 <= "1" when (indvar_flatten81_fu_74 = ap_const_lv6_31) else "0";
    icmp_ln189_fu_232_p2 <= "1" when (c_fu_66 = ap_const_lv3_7) else "0";
    icmp_ln195_1_fu_516_p2 <= "1" when (unsigned(conv2_buf_q0) > unsigned(max_val_1_reg_655)) else "0";
    icmp_ln195_2_fu_532_p2 <= "1" when (unsigned(val_2_reg_667) > unsigned(max_val_3_reg_661)) else "0";
    icmp_ln195_fu_502_p2 <= "1" when (unsigned(conv2_buf_1_q1) > unsigned(conv2_buf_q1)) else "0";
    max_val_1_fu_508_p3 <= 
        conv2_buf_1_q1 when (icmp_ln195_fu_502_p2(0) = '1') else 
        conv2_buf_q1;
    max_val_3_fu_521_p3 <= 
        conv2_buf_q0 when (icmp_ln195_1_fu_516_p2(0) = '1') else 
        max_val_1_reg_655;
    max_val_4_fu_536_p3 <= 
        val_2_reg_667 when (icmp_ln195_2_fu_532_p2(0) = '1') else 
        max_val_3_reg_661;
    p_shl1_fu_371_p3 <= (select_ln187_1_reg_582 & ap_const_lv3_0);
    p_shl_fu_280_p3 <= (select_ln187_1_fu_244_p3 & ap_const_lv4_0);
    pool2_buf_address0 <= zext_ln198_2_fu_528_p1(10 - 1 downto 0);
    pool2_buf_ce0 <= pool2_buf_ce0_local;

    pool2_buf_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pool2_buf_ce0_local <= ap_const_logic_1;
        else 
            pool2_buf_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_buf_d0 <= max_val_4_fu_536_p3;
    pool2_buf_we0 <= pool2_buf_we0_local;

    pool2_buf_we0_local_assign_proc : process(ap_enable_reg_pp0_iter5, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            pool2_buf_we0_local <= ap_const_logic_1;
        else 
            pool2_buf_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln187_1_fu_244_p3 <= 
        add_ln187_fu_206_p2 when (icmp_ln188_fu_212_p2(0) = '1') else 
        ch_fu_78;
    select_ln187_fu_218_p3 <= 
        ap_const_lv3_0 when (icmp_ln188_fu_212_p2(0) = '1') else 
        r_fu_70;
    select_ln188_1_fu_340_p3 <= 
        ap_const_lv6_1 when (icmp_ln188_fu_212_p2(0) = '1') else 
        add_ln188_1_fu_334_p2;
    select_ln188_fu_272_p3 <= 
        add_ln188_fu_252_p2 when (and_ln187_fu_238_p2(0) = '1') else 
        select_ln187_fu_218_p3;
    sub_ln189_fu_445_p2 <= std_logic_vector(unsigned(tmp_4_fu_433_p3) - unsigned(zext_ln194_5_fu_441_p1));
    sub_ln194_1_fu_407_p2 <= std_logic_vector(unsigned(tmp_2_fu_397_p3) - unsigned(zext_ln194_3_fu_404_p1));
    sub_ln194_fu_300_p2 <= std_logic_vector(unsigned(p_shl_fu_280_p3) - unsigned(zext_ln194_1_fu_296_p1));
    sub_ln198_1_fu_482_p2 <= std_logic_vector(unsigned(tmp_1_fu_472_p3) - unsigned(zext_ln198_1_fu_479_p1));
    sub_ln198_fu_378_p2 <= std_logic_vector(unsigned(p_shl1_fu_371_p3) - unsigned(zext_ln194_fu_368_p1));
    tmp_1_fu_472_p3 <= (trunc_ln198_reg_620 & ap_const_lv3_0);
    tmp_2_fu_397_p3 <= (trunc_ln194_reg_610 & ap_const_lv3_0);
    tmp_3_fu_413_p3 <= (select_ln188_reg_594 & ap_const_lv1_1);
    tmp_4_fu_433_p3 <= (trunc_ln194_1_fu_429_p1 & ap_const_lv3_0);
    tmp_fu_288_p3 <= (select_ln187_1_fu_244_p3 & ap_const_lv1_0);
    tmp_s_fu_306_p3 <= (select_ln188_fu_272_p3 & ap_const_lv1_0);
    trunc_ln194_1_fu_429_p1 <= add_ln194_1_fu_424_p2(8 - 1 downto 0);
    trunc_ln194_fu_324_p1 <= add_ln194_fu_318_p2(8 - 1 downto 0);
    trunc_ln198_fu_393_p1 <= add_ln198_fu_387_p2(7 - 1 downto 0);
    xor_ln187_fu_226_p2 <= (icmp_ln188_fu_212_p2 xor ap_const_lv1_1);
    zext_ln194_1_fu_296_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_288_p3),9));
    zext_ln194_2_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_306_p3),9));
    zext_ln194_3_fu_404_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln194_reg_605),11));
    zext_ln194_4_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_413_p3),9));
    zext_ln194_5_fu_441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln194_1_fu_424_p2),11));
    zext_ln194_6_fu_488_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_4_mid2_reg_588_pp0_iter2_reg),10));
    zext_ln194_7_fu_451_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_4_mid2_reg_588),11));
    zext_ln194_8_fu_460_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln194_2_fu_454_p2),64));
    zext_ln194_9_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln194_3_reg_630),64));
    zext_ln194_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln187_1_reg_582),8));
    zext_ln198_1_fu_479_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln198_reg_615),10));
    zext_ln198_2_fu_528_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln198_1_reg_650_pp0_iter4_reg),64));
    zext_ln198_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln188_reg_594),8));
end behav;
