import numpy as np
import time
from pynq import Overlay, allocate

# Autonomous System Inference on PYNQ-Z2
# Assumes block design with 4 DMAs connected to MLP, CNN, BNN, and SVM IPs.

class AutonomousSystem:
    def __init__(self, bitfile="autonomous_system.bit"):
        print(f"Loading {bitfile} onto FPGA...")
        self.overlay = Overlay(bitfile)
        
        # Access DMAs (names depend on Vivado Block Design)
        # Assuming names like axi_dma_mlp, axi_dma_cnn, axi_dma_bnn, axi_dma_svm
        try:
            self.dma_mlp = self.overlay.axi_dma_mlp
            self.dma_cnn = self.overlay.axi_dma_cnn
            self.dma_bnn = self.overlay.axi_dma_bnn
            self.dma_svm = self.overlay.axi_dma_svm
        except AttributeError:
            print("Warning: DMAs not found. Please verify IP names in Vivado Block Design.")
            self.dma_mlp = None
            
    def run_mlp_router(self, metadata_features):
        """
        Sends metadata to MLP to decide which accelerator to use.
        Returns: 0 (CNN), 1 (BNN), or 2 (SVM)
        """
        if self.dma_mlp is None:
            return 0 # Mock fallback
            
        in_buffer = allocate(shape=(len(metadata_features),), dtype=np.uint32)
        out_buffer = allocate(shape=(1,), dtype=np.uint32)
        
        np.copyto(in_buffer, np.array(metadata_features, dtype=np.uint32))
        
        self.dma_mlp.sendchannel.transfer(in_buffer)
        self.dma_mlp.recvchannel.transfer(out_buffer)
        self.dma_mlp.sendchannel.wait()
        self.dma_mlp.recvchannel.wait()
        
        route = out_buffer[0]
        del in_buffer, out_buffer
        return route

    def run_cnn(self, image_data):
        print("Routing to CNN Accelerator (Images / Traffic Signs)...")
        # Pseudo-code for DMA transfer
        return "CNN Classification Result"

    def run_bnn(self, audio_data):
        print("Routing to BNN Accelerator (Audio / Ambulance)...")
        # Pseudo-code for DMA transfer
        return "BNN Classification Result"

    def run_svm(self, tabular_data):
        print("Routing to SVM Accelerator (Lane movement)...")
        # Pseudo-code for DMA transfer
        return "SVM Classification Result"

    def process_input(self, metadata, payload):
        """
        Main entry point.
        metadata: list of features for the MLP.
        payload: actual data for the sub-model.
        """
        route = self.run_mlp_router(metadata)
        
        if route == 0:
            return self.run_cnn(payload)
        elif route == 1:
            return self.run_bnn(payload)
        elif route == 2:
            return self.run_svm(payload)
        else:
            print("Invalid route generated by MLP!")
            return None

def main():
    print("Initializing Autonomous System on PYNQ...")
    # NOTE: This requires the actual bitstream to run.
    # We mock it by not instantiating if bitfile doesn't exist locally on laptop.
    import os
    if os.path.exists("autonomous_system.bit"):
        system = AutonomousSystem("autonomous_system.bit")
        
        # Test 1: Image Input
        print("\n--- Test 1: Receiving Image ---")
        meta_image = [0, 32, 32, 3, 1] # Metadata for MLP (e.g. Type=0)
        system.process_input(meta_image, np.random.rand(32, 32, 3))
        
        # Test 2: Audio Input
        print("\n--- Test 2: Receiving Audio ---")
        meta_audio = [1, 40, 1, 1, 1] # Metadata for MLP (e.g. Type=1)
        system.process_input(meta_audio, np.random.rand(40))
    else:
        print("\n[!] autonomous_system.bit not found. Please generate it using Vivado and copy to this directory.")

if __name__ == "__main__":
    main()
