#!/usr/bin/env python3
"""
mlp_inference_pynq.py -- Siren Classifier FPGA Inference on PYNQ-Z2
                          41->4->2 MLP  (ambulance vs firetruck)

Usage (JupyterLab on the PYNQ board, as root):
    Run each cell in mlp_inference_pynq.ipynb, OR:
    exec(open('mlp_inference_pynq.py').read())

The script:
  1. Loads the bitstream (.bit + .hwh) into the PL
  2. Extracts 41 audio features from a WAV file
  3. Standardises with checkpoint feature_mean / feature_std
  4. Encodes to Q4.12 fixed-point and sends 41 uint32 over AXI-DMA
  5. Receives 1 uint32 from FPGA (0 = ambulance, 1 = firetruck)
  6. Displays the result

Prerequisites on PYNQ board:
    pip install scipy  (if not already installed in pynq-venv)

Files expected in the same directory:
    mlp_accelerator.bit
    mlp_accelerator.hwh
    feature_stats.npz    (generated by generate_feature_stats.py below)

Feature extraction matches training exactly (41 dims):
  - 32 spectral band features (8 bands x 4 stats each)
  -  5 waveform stats
  -  4 band-energy means
"""

import os
import sys
import struct
import numpy as np

# ============================================================================
# Feature extraction (must match training pipeline exactly)
# ============================================================================

TARGET_SR = 16000
NPERSEG   = 512
NOVERLAP  = 256

# Frequency band boundaries (Hz)
SPEC_BANDS = [(0,500), (500,1000), (1000,2000), (2000,4000),
              (4000,6000), (6000,8000), (8000,10000), (10000,16000)]
ENERGY_BANDS = [(0,300), (300,1000), (1000,3000), (3000,8000)]


def extract_features_from_wav(wav_path):
    """Load WAV, extract 41-dim feature vector. Requires scipy."""
    from scipy.io import wavfile
    from scipy.signal import resample, spectrogram, hann

    sr, data = wavfile.read(wav_path)

    # Convert to float32 in [-1, 1]
    if data.dtype == np.int16:
        data = data.astype(np.float32) / 32768.0
    elif data.dtype == np.int32:
        data = data.astype(np.float32) / 2147483648.0
    else:
        data = data.astype(np.float32)

    # Stereo -> mono
    if data.ndim == 2:
        data = data.mean(axis=1)

    # Peak normalise
    peak = np.max(np.abs(data))
    if peak > 0:
        data = data / peak

    # Resample to TARGET_SR
    if sr != TARGET_SR:
        n_samples = int(len(data) * TARGET_SR / sr)
        data = resample(data, n_samples)
        sr = TARGET_SR

    # Spectrogram
    freqs, times, Sxx = spectrogram(
        data, fs=sr, window=hann(NPERSEG),
        nperseg=NPERSEG, noverlap=NOVERLAP,
        scaling='spectrum', mode='magnitude'
    )
    Sxx = np.log1p(Sxx)  # log1p compression

    features = []

    # 32 spectral band features (8 bands x 4 stats)
    for flo, fhi in SPEC_BANDS:
        mask = (freqs >= flo) & (freqs < fhi)
        band = Sxx[mask, :].flatten() if mask.any() else np.zeros(1)
        features.extend([
            float(np.mean(band)),
            float(np.std(band)),
            float(np.percentile(band, 25)),
            float(np.percentile(band, 75)),
        ])

    # 5 waveform stats
    abs_data = np.abs(data)
    features.extend([
        float(np.mean(data)),
        float(np.std(data)),
        float(np.mean(abs_data)),
        float(np.max(abs_data)),
        float(np.percentile(abs_data, 90)),
    ])

    # 4 band-energy means
    for flo, fhi in ENERGY_BANDS:
        mask = (freqs >= flo) & (freqs < fhi)
        band_e = Sxx[mask, :].mean(axis=0) if mask.any() else np.zeros(len(times))
        features.append(float(np.mean(band_e)))

    assert len(features) == 41, f"Expected 41 features, got {len(features)}"
    return np.array(features, dtype=np.float32)


# ============================================================================
# Q4.12 encoding / decoding
# ============================================================================
SCALE = 4096  # Q4.12

def encode_q412(x, scale=SCALE):
    """Float array -> list of uint32 (Q4.12 int16 in bits[15:0])."""
    out = []
    for v in x:
        q = int(round(float(v) * scale))
        q = max(-32768, min(32767, q))
        # pack as uint32 (sign-extend 16->32 via unsigned view)
        out.append(struct.unpack('<I', struct.pack('<h', q) + b'\x00\x00')[0])
    return out


# ============================================================================
# FPGA inference
# ============================================================================
CLASS_NAMES = ['ambulance', 'firetruck']

def run_fpga_inference(wav_path, overlay, feature_mean, feature_std,
                       verbose=True):
    """Full pipeline: WAV -> features -> FPGA -> class label."""

    # Step 1: Extract features
    if verbose:
        print(f"Extracting features from: {wav_path}")
    feats = extract_features_from_wav(wav_path)

    # Step 2: Standardise
    x_norm = (feats - feature_mean) / (feature_std + 1e-8)

    # Step 3: Q4.12 encode
    encoded = encode_q412(x_norm)
    assert len(encoded) == 41

    # Step 4: Set up DMA buffers
    import pynq
    from pynq import allocate
    in_buf  = allocate(shape=(41,),  dtype=np.uint32)
    out_buf = allocate(shape=(1,),   dtype=np.uint32)

    for i, v in enumerate(encoded):
        in_buf[i] = v

    # Step 5: DMA transfer
    dma = overlay.axi_dma_0
    dma.sendchannel.transfer(in_buf)
    dma.recvchannel.transfer(out_buf)
    dma.sendchannel.wait()
    dma.recvchannel.wait()

    # Step 6: Read result
    cls_idx = int(out_buf[0]) & 0x1   # clamp to 0 or 1

    in_buf.freebuffer()
    out_buf.freebuffer()

    if verbose:
        print(f"FPGA result: {cls_idx} -> {CLASS_NAMES[cls_idx].upper()}")

    return cls_idx, CLASS_NAMES[cls_idx]


# ============================================================================
# Interactive widget UI (for use in JupyterLab)
# ============================================================================

def run_interactive(overlay, feature_mean, feature_std):
    """Display file upload widget and run inference."""
    import ipywidgets as widgets
    from IPython.display import display, HTML, clear_output

    upload   = widgets.FileUpload(accept='.wav', multiple=False,
                                  description='Upload WAV')
    run_btn  = widgets.Button(description='Run FPGA Inference',
                              button_style='primary')
    out_area = widgets.Output()

    def on_run(_):
        with out_area:
            clear_output()
            # ipywidgets 7 vs 8 compatibility
            if not upload.value:
                print("Please upload a WAV file first.")
                return
            val = upload.value
            if isinstance(val, dict):
                # ipywidgets 7.x -- dict keyed by filename
                fname = list(val.keys())[0]
                data  = val[fname]['content']
            else:
                # ipywidgets 8.x -- list/tuple of objects
                item  = list(val)[0] if hasattr(val, '__iter__') else val[0]
                fname = item.get('name', 'audio.wav') if isinstance(item, dict) else getattr(item, 'name', 'audio.wav')
                data  = item.get('content', None)    if isinstance(item, dict) else getattr(item, 'content', None)
                if data is None:
                    data = bytes(item) if hasattr(item, '__bytes__') else bytes(item['content'])

            # Write to /tmp
            tmp = '/tmp/siren_input.wav'
            with open(tmp, 'wb') as f:
                f.write(bytes(data) if not isinstance(data, bytes) else data)

            try:
                cls_idx, cls_name = run_fpga_inference(
                    tmp, overlay, feature_mean, feature_std, verbose=True)
                emoji = '\U0001f691' if cls_idx == 0 else '\U0001f692'
                display(HTML(
                    f'<div style="font-size:2em;margin-top:10px">'
                    f'{emoji} <b>{cls_name.upper()}</b></div>'
                    f'<p>Uploaded: <code>{fname}</code> &nbsp; '
                    f'Class index: <code>{cls_idx}</code></p>'
                ))
            except Exception as e:
                print(f"ERROR: {e}")
                import traceback; traceback.print_exc()

    run_btn.on_click(on_run)
    display(widgets.VBox([upload, run_btn, out_area]))


# ============================================================================
# Main entry point (when run as a script)
# ============================================================================

def load_overlay_and_stats(bit_dir=None):
    """Load PYNQ overlay and feature stats."""
    from pynq import Overlay

    if bit_dir is None:
        bit_dir = os.path.dirname(os.path.abspath(__file__))

    bit = os.path.join(bit_dir, 'mlp_accelerator.bit')
    hwh = os.path.join(bit_dir, 'mlp_accelerator.hwh')

    if not os.path.exists(bit):
        raise FileNotFoundError(f"Bitstream not found: {bit}")
    if not os.path.exists(hwh):
        raise FileNotFoundError(f"HWH not found: {hwh}")

    print(f"Loading overlay: {bit}")
    ol = Overlay(bit)
    print("Overlay loaded.")

    # Load feature statistics
    stats_path = os.path.join(bit_dir, 'feature_stats.npz')
    if os.path.exists(stats_path):
        s = np.load(stats_path)
        feat_mean = s['mean'].astype(np.float32)
        feat_std  = s['std'].astype(np.float32)
        print(f"Feature stats loaded from {stats_path}")
    else:
        # Try to load from checkpoint if scipy and torch are available
        ckpt_path = os.path.join(bit_dir, 'best_model.pt')
        if os.path.exists(ckpt_path):
            try:
                import torch
                ckpt = torch.load(ckpt_path, weights_only=False, map_location='cpu')
                feat_mean = np.array(ckpt['feature_mean'], dtype=np.float32)
                feat_std  = np.array(ckpt['feature_std'],  dtype=np.float32)
                # Cache as npz for next time
                np.savez(stats_path, mean=feat_mean, std=feat_std)
                print(f"Feature stats extracted from checkpoint and cached.")
            except Exception as e:
                print(f"WARNING: Could not load feature stats from checkpoint: {e}")
                feat_mean = np.zeros(41, dtype=np.float32)
                feat_std  = np.ones(41,  dtype=np.float32)
        else:
            print("WARNING: feature_stats.npz not found -- using zero-mean/unit-std")
            feat_mean = np.zeros(41, dtype=np.float32)
            feat_std  = np.ones(41,  dtype=np.float32)

    return ol, feat_mean, feat_std


if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser(description='Siren FPGA inference')
    p.add_argument('wav', nargs='?', help='WAV file to classify')
    p.add_argument('--bit-dir', default=None, help='Directory with .bit/.hwh files')
    args = p.parse_args()

    overlay, feat_mean, feat_std = load_overlay_and_stats(args.bit_dir)

    if args.wav:
        run_fpga_inference(args.wav, overlay, feat_mean, feat_std)
    else:
        run_interactive(overlay, feat_mean, feat_std)
