// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlp_top_dense_relu_784_512_Pipeline_INNER (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_weights_0_AWVALID,
        m_axi_weights_0_AWREADY,
        m_axi_weights_0_AWADDR,
        m_axi_weights_0_AWID,
        m_axi_weights_0_AWLEN,
        m_axi_weights_0_AWSIZE,
        m_axi_weights_0_AWBURST,
        m_axi_weights_0_AWLOCK,
        m_axi_weights_0_AWCACHE,
        m_axi_weights_0_AWPROT,
        m_axi_weights_0_AWQOS,
        m_axi_weights_0_AWREGION,
        m_axi_weights_0_AWUSER,
        m_axi_weights_0_WVALID,
        m_axi_weights_0_WREADY,
        m_axi_weights_0_WDATA,
        m_axi_weights_0_WSTRB,
        m_axi_weights_0_WLAST,
        m_axi_weights_0_WID,
        m_axi_weights_0_WUSER,
        m_axi_weights_0_ARVALID,
        m_axi_weights_0_ARREADY,
        m_axi_weights_0_ARADDR,
        m_axi_weights_0_ARID,
        m_axi_weights_0_ARLEN,
        m_axi_weights_0_ARSIZE,
        m_axi_weights_0_ARBURST,
        m_axi_weights_0_ARLOCK,
        m_axi_weights_0_ARCACHE,
        m_axi_weights_0_ARPROT,
        m_axi_weights_0_ARQOS,
        m_axi_weights_0_ARREGION,
        m_axi_weights_0_ARUSER,
        m_axi_weights_0_RVALID,
        m_axi_weights_0_RREADY,
        m_axi_weights_0_RDATA,
        m_axi_weights_0_RLAST,
        m_axi_weights_0_RID,
        m_axi_weights_0_RFIFONUM,
        m_axi_weights_0_RUSER,
        m_axi_weights_0_RRESP,
        m_axi_weights_0_BVALID,
        m_axi_weights_0_BREADY,
        m_axi_weights_0_BRESP,
        m_axi_weights_0_BID,
        m_axi_weights_0_BUSER,
        sext_ln38,
        sext_ln37,
        in_act_0_address0,
        in_act_0_ce0,
        in_act_0_q0,
        in_act_1_address0,
        in_act_1_ce0,
        in_act_1_q0,
        in_act_2_address0,
        in_act_2_ce0,
        in_act_2_q0,
        in_act_3_address0,
        in_act_3_ce0,
        in_act_3_q0,
        in_act_4_address0,
        in_act_4_ce0,
        in_act_4_q0,
        in_act_5_address0,
        in_act_5_ce0,
        in_act_5_q0,
        in_act_6_address0,
        in_act_6_ce0,
        in_act_6_q0,
        in_act_7_address0,
        in_act_7_ce0,
        in_act_7_q0,
        acc_1_out,
        acc_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_weights_0_AWVALID;
input   m_axi_weights_0_AWREADY;
output  [63:0] m_axi_weights_0_AWADDR;
output  [0:0] m_axi_weights_0_AWID;
output  [31:0] m_axi_weights_0_AWLEN;
output  [2:0] m_axi_weights_0_AWSIZE;
output  [1:0] m_axi_weights_0_AWBURST;
output  [1:0] m_axi_weights_0_AWLOCK;
output  [3:0] m_axi_weights_0_AWCACHE;
output  [2:0] m_axi_weights_0_AWPROT;
output  [3:0] m_axi_weights_0_AWQOS;
output  [3:0] m_axi_weights_0_AWREGION;
output  [0:0] m_axi_weights_0_AWUSER;
output   m_axi_weights_0_WVALID;
input   m_axi_weights_0_WREADY;
output  [15:0] m_axi_weights_0_WDATA;
output  [1:0] m_axi_weights_0_WSTRB;
output   m_axi_weights_0_WLAST;
output  [0:0] m_axi_weights_0_WID;
output  [0:0] m_axi_weights_0_WUSER;
output   m_axi_weights_0_ARVALID;
input   m_axi_weights_0_ARREADY;
output  [63:0] m_axi_weights_0_ARADDR;
output  [0:0] m_axi_weights_0_ARID;
output  [31:0] m_axi_weights_0_ARLEN;
output  [2:0] m_axi_weights_0_ARSIZE;
output  [1:0] m_axi_weights_0_ARBURST;
output  [1:0] m_axi_weights_0_ARLOCK;
output  [3:0] m_axi_weights_0_ARCACHE;
output  [2:0] m_axi_weights_0_ARPROT;
output  [3:0] m_axi_weights_0_ARQOS;
output  [3:0] m_axi_weights_0_ARREGION;
output  [0:0] m_axi_weights_0_ARUSER;
input   m_axi_weights_0_RVALID;
output   m_axi_weights_0_RREADY;
input  [15:0] m_axi_weights_0_RDATA;
input   m_axi_weights_0_RLAST;
input  [0:0] m_axi_weights_0_RID;
input  [9:0] m_axi_weights_0_RFIFONUM;
input  [0:0] m_axi_weights_0_RUSER;
input  [1:0] m_axi_weights_0_RRESP;
input   m_axi_weights_0_BVALID;
output   m_axi_weights_0_BREADY;
input  [1:0] m_axi_weights_0_BRESP;
input  [0:0] m_axi_weights_0_BID;
input  [0:0] m_axi_weights_0_BUSER;
input  [25:0] sext_ln38;
input  [62:0] sext_ln37;
output  [6:0] in_act_0_address0;
output   in_act_0_ce0;
input  [15:0] in_act_0_q0;
output  [6:0] in_act_1_address0;
output   in_act_1_ce0;
input  [15:0] in_act_1_q0;
output  [6:0] in_act_2_address0;
output   in_act_2_ce0;
input  [15:0] in_act_2_q0;
output  [6:0] in_act_3_address0;
output   in_act_3_ce0;
input  [15:0] in_act_3_q0;
output  [6:0] in_act_4_address0;
output   in_act_4_ce0;
input  [15:0] in_act_4_q0;
output  [6:0] in_act_5_address0;
output   in_act_5_ce0;
input  [15:0] in_act_5_q0;
output  [6:0] in_act_6_address0;
output   in_act_6_ce0;
input  [15:0] in_act_6_q0;
output  [6:0] in_act_7_address0;
output   in_act_7_ce0;
input  [15:0] in_act_7_q0;
output  [31:0] acc_1_out;
output   acc_1_out_ap_vld;

reg ap_idle;
reg m_axi_weights_0_RREADY;
reg acc_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] icmp_ln41_reg_1939;
reg    ap_block_state3_pp0_stage2_iter0_grp2;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage2_subdone;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_pp0_stage7;
reg    ap_block_state8_pp0_stage7_iter0_grp7;
reg    ap_block_pp0_stage7_subdone;
reg    weights_blk_n_R;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_grp1;
wire    ap_block_pp0_stage2_grp2;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_grp3;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_grp4;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_grp5;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_grp6;
wire    ap_block_pp0_stage7_grp7;
wire    ap_block_pp0_stage0_grp8;
reg   [15:0] reg_246;
reg    ap_block_state2_pp0_stage1_iter0_grp1;
reg    ap_block_pp0_stage1_11001_grp1;
reg    ap_block_pp0_stage2_11001_grp2;
reg    ap_block_state4_pp0_stage3_iter0_grp3;
reg    ap_block_pp0_stage3_11001_grp3;
reg    ap_block_state5_pp0_stage4_iter0_grp4;
reg    ap_block_pp0_stage4_11001_grp4;
reg    ap_block_state6_pp0_stage5_iter0_grp5;
reg    ap_block_pp0_stage5_11001_grp5;
reg    ap_block_state7_pp0_stage6_iter0_grp6;
reg    ap_block_pp0_stage6_11001_grp6;
reg    ap_block_pp0_stage7_11001_grp7;
reg    ap_block_pp0_stage0_11001_grp8;
wire  signed [51:0] grp_fu_242_p2;
reg  signed [51:0] reg_250;
wire    ap_block_pp0_stage2_11001_grp0;
reg    ap_block_pp0_stage2_subdone_grp0_done_reg;
wire    ap_block_pp0_stage2_subdone_grp0;
wire    ap_block_pp0_stage3_11001_grp0;
reg    ap_block_pp0_stage3_subdone_grp0_done_reg;
wire    ap_block_pp0_stage3_subdone_grp0;
reg    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_11001_grp0;
reg    ap_block_pp0_stage4_subdone_grp0_done_reg;
wire    ap_block_pp0_stage4_subdone_grp0;
reg    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_11001_grp0;
reg    ap_block_pp0_stage5_subdone_grp0_done_reg;
wire    ap_block_pp0_stage5_subdone_grp0;
reg    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_11001_grp0;
reg    ap_block_pp0_stage6_subdone_grp0_done_reg;
wire    ap_block_pp0_stage6_subdone_grp0;
reg    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_11001_grp0;
reg    ap_block_pp0_stage7_subdone_grp0_done_reg;
wire    ap_block_pp0_stage7_subdone_grp0;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg    ap_block_pp0_stage0_subdone;
wire    ap_block_pp0_stage1_11001_grp0;
reg    ap_block_pp0_stage1_subdone_grp0_done_reg;
wire    ap_block_pp0_stage1_subdone_grp0;
reg    ap_block_pp0_stage1_subdone;
wire   [0:0] icmp_ln41_fu_275_p2;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] in_act_0_load_reg_1988;
reg   [15:0] in_act_1_load_reg_1993;
reg   [15:0] in_act_2_load_reg_1998;
reg   [15:0] in_act_3_load_reg_2003;
reg   [15:0] in_act_4_load_reg_2008;
reg   [15:0] in_act_5_load_reg_2013;
reg   [15:0] in_act_6_load_reg_2018;
reg   [15:0] in_act_7_load_reg_2023;
wire   [0:0] tmp_fu_376_p3;
reg   [0:0] tmp_reg_2028;
wire   [0:0] tmp_2_fu_402_p3;
reg   [0:0] tmp_2_reg_2033;
wire   [31:0] acc_2_fu_420_p2;
reg   [31:0] acc_2_reg_2038;
wire   [0:0] tmp_3_fu_426_p3;
reg   [0:0] tmp_3_reg_2043;
wire   [0:0] and_ln43_2_fu_470_p2;
reg   [0:0] and_ln43_2_reg_2049;
wire   [0:0] tmp_4_fu_574_p3;
reg   [0:0] tmp_4_reg_2055;
reg   [0:0] tmp_6_reg_2062;
wire   [31:0] acc_4_fu_618_p2;
reg   [31:0] acc_4_reg_2068;
reg   [0:0] tmp_7_reg_2073;
wire   [0:0] tmp_8_fu_769_p3;
reg   [0:0] tmp_8_reg_2081;
reg   [0:0] tmp_10_reg_2088;
wire   [31:0] acc_6_fu_813_p2;
reg   [31:0] acc_6_reg_2094;
reg   [0:0] tmp_11_reg_2099;
wire   [0:0] tmp_12_fu_964_p3;
reg   [0:0] tmp_12_reg_2107;
reg   [0:0] tmp_14_reg_2114;
wire   [31:0] acc_8_fu_1008_p2;
reg   [31:0] acc_8_reg_2120;
reg   [0:0] tmp_15_reg_2125;
wire   [0:0] tmp_16_fu_1159_p3;
reg   [0:0] tmp_16_reg_2133;
wire   [0:0] tmp_18_fu_1185_p3;
reg   [0:0] tmp_18_reg_2138;
wire   [31:0] acc_10_fu_1203_p2;
reg   [31:0] acc_10_reg_2143;
wire   [0:0] tmp_19_fu_1209_p3;
reg   [0:0] tmp_19_reg_2148;
wire   [0:0] and_ln43_18_fu_1253_p2;
reg   [0:0] and_ln43_18_reg_2154;
wire   [31:0] acc_12_fu_1401_p2;
reg   [31:0] acc_12_reg_2160;
wire   [0:0] and_ln43_22_fu_1463_p2;
reg   [0:0] and_ln43_22_reg_2165;
wire   [0:0] or_ln43_17_fu_1487_p2;
reg   [0:0] or_ln43_17_reg_2170;
wire   [31:0] select_ln43_13_fu_1728_p3;
reg   [31:0] select_ln43_13_reg_2175;
wire   [63:0] zext_ln38_fu_297_p1;
wire    ap_block_pp0_stage0;
reg   [31:0] acc_fu_106;
wire   [31:0] acc_17_fu_1907_p3;
wire  signed [31:0] sext_ln38_cast_fu_258_p1;
wire    ap_block_pp0_stage2_grp0;
wire    ap_loop_init;
wire    ap_block_pp0_stage3_grp0;
reg   [9:0] i_fu_110;
wire   [9:0] add_ln41_fu_309_p2;
reg   [9:0] ap_sig_allocacmp_i_2;
wire    ap_block_pp0_stage2_01001_grp0;
reg    in_act_0_ce0_local;
reg    in_act_1_ce0_local;
reg    in_act_2_ce0_local;
reg    in_act_3_ce0_local;
reg    in_act_4_ce0_local;
reg    in_act_5_ce0_local;
reg    in_act_6_ce0_local;
reg    in_act_7_ce0_local;
reg  signed [25:0] grp_fu_242_p0;
wire  signed [51:0] sext_ln43_1_fu_340_p1;
wire  signed [51:0] sext_ln43_5_fu_496_p1;
wire  signed [51:0] sext_ln43_9_fu_652_p1;
wire  signed [51:0] sext_ln43_13_fu_847_p1;
wire  signed [51:0] sext_ln43_17_fu_1042_p1;
wire  signed [51:0] sext_ln43_21_fu_1279_p1;
wire  signed [51:0] sext_ln43_25_fu_1513_p1;
wire  signed [51:0] sext_ln43_29_fu_1715_p1;
reg  signed [25:0] grp_fu_242_p1;
wire  signed [51:0] sext_ln43_fu_335_p1;
wire  signed [51:0] sext_ln43_4_fu_491_p1;
wire  signed [51:0] sext_ln43_8_fu_647_p1;
wire  signed [51:0] sext_ln43_12_fu_842_p1;
wire  signed [51:0] sext_ln43_16_fu_1037_p1;
wire  signed [51:0] sext_ln43_20_fu_1274_p1;
wire  signed [51:0] sext_ln43_24_fu_1508_p1;
wire  signed [51:0] sext_ln43_28_fu_1710_p1;
wire    ap_block_pp0_stage4_grp0;
wire    ap_block_pp0_stage5_grp0;
wire    ap_block_pp0_stage6_grp0;
wire    ap_block_pp0_stage7_grp0;
wire    ap_block_pp0_stage0_grp0;
wire    ap_block_pp0_stage1_grp0;
wire   [6:0] lshr_ln_fu_287_p4;
wire   [25:0] shl_ln_fu_320_p3;
wire   [25:0] shl_ln43_1_fu_328_p3;
wire  signed [51:0] shl_ln43_2_fu_348_p3;
wire  signed [52:0] sext_ln43_2_fu_356_p1;
wire  signed [52:0] sext_ln43_3_fu_360_p1;
wire   [52:0] add_ln43_fu_370_p2;
wire   [51:0] add_ln43_1_fu_364_p2;
wire   [0:0] tmp_1_fu_394_p3;
wire   [0:0] and_ln43_fu_410_p2;
wire   [31:0] acc_1_fu_384_p4;
wire   [31:0] zext_ln43_fu_416_p1;
wire   [0:0] xor_ln43_2_fu_434_p2;
wire   [0:0] or_ln43_fu_440_p2;
wire   [0:0] xor_ln43_4_fu_452_p2;
wire   [0:0] xor_ln43_3_fu_458_p2;
wire   [0:0] or_ln43_1_fu_464_p2;
wire   [0:0] xor_ln43_1_fu_446_p2;
wire   [25:0] shl_ln43_3_fu_476_p3;
wire   [25:0] shl_ln43_4_fu_484_p3;
wire   [0:0] xor_ln43_fu_501_p2;
wire   [0:0] and_ln43_1_fu_506_p2;
wire   [0:0] or_ln43_3_fu_511_p2;
wire   [0:0] xor_ln43_5_fu_516_p2;
wire   [0:0] and_ln43_3_fu_522_p2;
wire   [0:0] or_ln43_2_fu_527_p2;
wire   [31:0] select_ln43_fu_532_p3;
wire   [31:0] select_ln43_1_fu_539_p3;
wire  signed [51:0] shl_ln43_5_fu_546_p3;
wire  signed [52:0] sext_ln43_6_fu_554_p1;
wire  signed [52:0] sext_ln43_7_fu_558_p1;
wire   [52:0] add_ln43_2_fu_568_p2;
wire   [51:0] add_ln43_5_fu_562_p2;
wire   [0:0] tmp_5_fu_592_p3;
wire   [0:0] and_ln43_4_fu_608_p2;
wire   [31:0] acc_3_fu_582_p4;
wire   [31:0] zext_ln43_1_fu_614_p1;
wire   [25:0] shl_ln43_6_fu_632_p3;
wire   [25:0] shl_ln43_7_fu_640_p3;
wire   [0:0] xor_ln43_6_fu_657_p2;
wire   [0:0] xor_ln43_8_fu_667_p2;
wire   [0:0] or_ln43_6_fu_672_p2;
wire   [0:0] xor_ln43_10_fu_682_p2;
wire   [0:0] xor_ln43_9_fu_688_p2;
wire   [0:0] or_ln43_4_fu_693_p2;
wire   [0:0] xor_ln43_7_fu_677_p2;
wire   [0:0] and_ln43_5_fu_662_p2;
wire   [0:0] or_ln43_9_fu_704_p2;
wire   [0:0] xor_ln43_11_fu_709_p2;
wire   [0:0] and_ln43_6_fu_698_p2;
wire   [0:0] and_ln43_7_fu_715_p2;
wire   [0:0] or_ln43_5_fu_720_p2;
wire   [31:0] select_ln43_2_fu_726_p3;
wire   [31:0] select_ln43_3_fu_734_p3;
wire  signed [51:0] shl_ln43_8_fu_741_p3;
wire  signed [52:0] sext_ln43_10_fu_749_p1;
wire  signed [52:0] sext_ln43_11_fu_753_p1;
wire   [52:0] add_ln43_4_fu_763_p2;
wire   [51:0] add_ln43_9_fu_757_p2;
wire   [0:0] tmp_9_fu_787_p3;
wire   [0:0] and_ln43_8_fu_803_p2;
wire   [31:0] acc_5_fu_777_p4;
wire   [31:0] zext_ln43_2_fu_809_p1;
wire   [25:0] shl_ln43_9_fu_827_p3;
wire   [25:0] shl_ln43_s_fu_835_p3;
wire   [0:0] xor_ln43_12_fu_852_p2;
wire   [0:0] xor_ln43_14_fu_862_p2;
wire   [0:0] or_ln43_12_fu_867_p2;
wire   [0:0] xor_ln43_16_fu_877_p2;
wire   [0:0] xor_ln43_15_fu_883_p2;
wire   [0:0] or_ln43_7_fu_888_p2;
wire   [0:0] xor_ln43_13_fu_872_p2;
wire   [0:0] and_ln43_9_fu_857_p2;
wire   [0:0] or_ln43_15_fu_899_p2;
wire   [0:0] xor_ln43_17_fu_904_p2;
wire   [0:0] and_ln43_10_fu_893_p2;
wire   [0:0] and_ln43_11_fu_910_p2;
wire   [0:0] or_ln43_8_fu_915_p2;
wire   [31:0] select_ln43_4_fu_921_p3;
wire   [31:0] select_ln43_5_fu_929_p3;
wire  signed [51:0] shl_ln43_10_fu_936_p3;
wire  signed [52:0] sext_ln43_14_fu_944_p1;
wire  signed [52:0] sext_ln43_15_fu_948_p1;
wire   [52:0] add_ln43_6_fu_958_p2;
wire   [51:0] add_ln43_13_fu_952_p2;
wire   [0:0] tmp_13_fu_982_p3;
wire   [0:0] and_ln43_12_fu_998_p2;
wire   [31:0] acc_7_fu_972_p4;
wire   [31:0] zext_ln43_3_fu_1004_p1;
wire   [25:0] shl_ln43_11_fu_1022_p3;
wire   [25:0] shl_ln43_12_fu_1030_p3;
wire   [0:0] xor_ln43_18_fu_1047_p2;
wire   [0:0] xor_ln43_20_fu_1057_p2;
wire   [0:0] or_ln43_18_fu_1062_p2;
wire   [0:0] xor_ln43_22_fu_1072_p2;
wire   [0:0] xor_ln43_21_fu_1078_p2;
wire   [0:0] or_ln43_10_fu_1083_p2;
wire   [0:0] xor_ln43_19_fu_1067_p2;
wire   [0:0] and_ln43_13_fu_1052_p2;
wire   [0:0] or_ln43_21_fu_1094_p2;
wire   [0:0] xor_ln43_23_fu_1099_p2;
wire   [0:0] and_ln43_14_fu_1088_p2;
wire   [0:0] and_ln43_15_fu_1105_p2;
wire   [0:0] or_ln43_11_fu_1110_p2;
wire   [31:0] select_ln43_6_fu_1116_p3;
wire   [31:0] select_ln43_7_fu_1124_p3;
wire  signed [51:0] shl_ln43_13_fu_1131_p3;
wire  signed [52:0] sext_ln43_18_fu_1139_p1;
wire  signed [52:0] sext_ln43_19_fu_1143_p1;
wire   [52:0] add_ln43_8_fu_1153_p2;
wire   [51:0] add_ln43_16_fu_1147_p2;
wire   [0:0] tmp_17_fu_1177_p3;
wire   [0:0] and_ln43_16_fu_1193_p2;
wire   [31:0] acc_9_fu_1167_p4;
wire   [31:0] zext_ln43_4_fu_1199_p1;
wire   [0:0] xor_ln43_26_fu_1217_p2;
wire   [0:0] or_ln43_24_fu_1223_p2;
wire   [0:0] xor_ln43_28_fu_1235_p2;
wire   [0:0] xor_ln43_27_fu_1241_p2;
wire   [0:0] or_ln43_13_fu_1247_p2;
wire   [0:0] xor_ln43_25_fu_1229_p2;
wire   [25:0] shl_ln43_14_fu_1259_p3;
wire   [25:0] shl_ln43_15_fu_1267_p3;
wire   [0:0] xor_ln43_24_fu_1284_p2;
wire   [0:0] and_ln43_17_fu_1289_p2;
wire   [0:0] or_ln43_25_fu_1294_p2;
wire   [0:0] xor_ln43_29_fu_1299_p2;
wire   [0:0] and_ln43_19_fu_1305_p2;
wire   [0:0] or_ln43_14_fu_1310_p2;
wire   [31:0] select_ln43_8_fu_1315_p3;
wire   [31:0] select_ln43_9_fu_1322_p3;
wire  signed [51:0] shl_ln43_16_fu_1329_p3;
wire  signed [52:0] sext_ln43_22_fu_1337_p1;
wire  signed [52:0] sext_ln43_23_fu_1341_p1;
wire   [52:0] add_ln43_10_fu_1351_p2;
wire   [51:0] add_ln43_18_fu_1345_p2;
wire   [0:0] tmp_20_fu_1357_p3;
wire   [0:0] tmp_21_fu_1375_p3;
wire   [0:0] and_ln43_20_fu_1391_p2;
wire   [31:0] acc_11_fu_1365_p4;
wire   [31:0] zext_ln43_5_fu_1397_p1;
wire   [0:0] tmp_23_fu_1407_p3;
wire   [0:0] tmp_22_fu_1383_p3;
wire   [0:0] xor_ln43_30_fu_1415_p2;
wire   [0:0] xor_ln43_32_fu_1427_p2;
wire   [0:0] or_ln43_26_fu_1433_p2;
wire   [0:0] xor_ln43_34_fu_1445_p2;
wire   [0:0] xor_ln43_33_fu_1451_p2;
wire   [0:0] or_ln43_16_fu_1457_p2;
wire   [0:0] xor_ln43_31_fu_1439_p2;
wire   [0:0] and_ln43_21_fu_1421_p2;
wire   [0:0] or_ln43_27_fu_1469_p2;
wire   [0:0] xor_ln43_35_fu_1475_p2;
wire   [0:0] and_ln43_23_fu_1481_p2;
wire   [25:0] shl_ln43_17_fu_1493_p3;
wire   [25:0] shl_ln43_18_fu_1501_p3;
wire   [31:0] select_ln43_10_fu_1518_p3;
wire   [31:0] select_ln43_11_fu_1525_p3;
wire  signed [51:0] shl_ln43_19_fu_1531_p3;
wire  signed [52:0] sext_ln43_26_fu_1539_p1;
wire  signed [52:0] sext_ln43_27_fu_1543_p1;
wire   [52:0] add_ln43_12_fu_1553_p2;
wire   [51:0] add_ln43_20_fu_1547_p2;
wire   [0:0] tmp_24_fu_1559_p3;
wire   [0:0] tmp_25_fu_1577_p3;
wire   [0:0] and_ln43_24_fu_1593_p2;
wire   [31:0] acc_13_fu_1567_p4;
wire   [31:0] zext_ln43_6_fu_1599_p1;
wire   [31:0] acc_14_fu_1603_p2;
wire   [0:0] tmp_27_fu_1609_p3;
wire   [0:0] tmp_26_fu_1585_p3;
wire   [0:0] xor_ln43_36_fu_1617_p2;
wire   [0:0] xor_ln43_38_fu_1629_p2;
wire   [0:0] or_ln43_28_fu_1635_p2;
wire   [0:0] xor_ln43_40_fu_1647_p2;
wire   [0:0] xor_ln43_39_fu_1653_p2;
wire   [0:0] or_ln43_19_fu_1659_p2;
wire   [0:0] xor_ln43_37_fu_1641_p2;
wire   [0:0] and_ln43_25_fu_1623_p2;
wire   [0:0] or_ln43_29_fu_1671_p2;
wire   [0:0] xor_ln43_41_fu_1677_p2;
wire   [0:0] and_ln43_26_fu_1665_p2;
wire   [0:0] and_ln43_27_fu_1683_p2;
wire   [25:0] shl_ln43_20_fu_1695_p3;
wire   [25:0] shl_ln43_21_fu_1703_p3;
wire   [0:0] or_ln43_20_fu_1689_p2;
wire   [31:0] select_ln43_12_fu_1720_p3;
wire  signed [51:0] shl_ln43_22_fu_1736_p3;
wire  signed [52:0] sext_ln43_30_fu_1743_p1;
wire  signed [52:0] sext_ln43_31_fu_1747_p1;
wire   [52:0] add_ln43_14_fu_1757_p2;
wire   [51:0] add_ln43_22_fu_1751_p2;
wire   [0:0] tmp_28_fu_1763_p3;
wire   [0:0] tmp_29_fu_1781_p3;
wire   [0:0] and_ln43_28_fu_1797_p2;
wire   [31:0] acc_15_fu_1771_p4;
wire   [31:0] zext_ln43_7_fu_1803_p1;
wire   [31:0] acc_16_fu_1807_p2;
wire   [0:0] tmp_31_fu_1813_p3;
wire   [0:0] tmp_30_fu_1789_p3;
wire   [0:0] xor_ln43_42_fu_1821_p2;
wire   [0:0] xor_ln43_44_fu_1833_p2;
wire   [0:0] or_ln43_30_fu_1839_p2;
wire   [0:0] xor_ln43_46_fu_1851_p2;
wire   [0:0] xor_ln43_45_fu_1857_p2;
wire   [0:0] or_ln43_22_fu_1863_p2;
wire   [0:0] xor_ln43_43_fu_1845_p2;
wire   [0:0] and_ln43_29_fu_1827_p2;
wire   [0:0] or_ln43_31_fu_1875_p2;
wire   [0:0] xor_ln43_47_fu_1881_p2;
wire   [0:0] and_ln43_30_fu_1869_p2;
wire   [0:0] and_ln43_31_fu_1887_p2;
wire   [0:0] or_ln43_23_fu_1901_p2;
wire   [31:0] select_ln43_14_fu_1893_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_block_pp0_stage2_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage3_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage4_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage5_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage6_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage7_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 ap_block_pp0_stage1_subdone_grp0_done_reg = 1'b0;
#0 acc_fu_106 = 32'd0;
#0 i_fu_110 = 10'd0;
#0 ap_done_reg = 1'b0;
end

mlp_top_mul_26s_26s_52_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 26 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 52 ))
mul_26s_26s_52_1_1_U13(
    .din0(grp_fu_242_p0),
    .din1(grp_fu_242_p1),
    .dout(grp_fu_242_p2)
);

mlp_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
                ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage1)) begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage1_subdone_grp0)) begin
                ap_block_pp0_stage1_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage2)) begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone_grp0)) begin
                ap_block_pp0_stage2_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage3)) begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage3_subdone_grp0)) begin
                ap_block_pp0_stage3_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage4)) begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage4_subdone_grp0)) begin
                ap_block_pp0_stage4_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage5_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage5)) begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_block_pp0_stage5_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage5_subdone_grp0)) begin
                ap_block_pp0_stage5_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage6_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage6)) begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_block_pp0_stage6_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage6_subdone_grp0)) begin
                ap_block_pp0_stage6_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage7_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage7)) begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_block_pp0_stage7_subdone_grp0_done_reg <= 1'b0;
            end else if ((1'b0 == ap_block_pp0_stage7_subdone_grp0)) begin
                ap_block_pp0_stage7_subdone_grp0_done_reg <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter0_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        acc_fu_106 <= sext_ln38_cast_fu_258_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        acc_fu_106 <= acc_17_fu_1907_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln41_fu_275_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_110 <= add_ln41_fu_309_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_110 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage7_11001_grp0))) begin
        acc_10_reg_2143 <= acc_10_fu_1203_p2;
        and_ln43_18_reg_2154 <= and_ln43_18_fu_1253_p2;
        tmp_16_reg_2133 <= add_ln43_8_fu_1153_p2[32'd52];
        tmp_18_reg_2138 <= add_ln43_16_fu_1147_p2[32'd51];
        tmp_19_reg_2148 <= acc_10_fu_1203_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0))) begin
        acc_12_reg_2160 <= acc_12_fu_1401_p2;
        and_ln43_22_reg_2165 <= and_ln43_22_fu_1463_p2;
        or_ln43_17_reg_2170 <= or_ln43_17_fu_1487_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0))) begin
        acc_2_reg_2038 <= acc_2_fu_420_p2;
        and_ln43_2_reg_2049 <= and_ln43_2_fu_470_p2;
        tmp_2_reg_2033 <= add_ln43_1_fu_364_p2[32'd51];
        tmp_3_reg_2043 <= acc_2_fu_420_p2[32'd31];
        tmp_reg_2028 <= add_ln43_fu_370_p2[32'd52];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0))) begin
        acc_4_reg_2068 <= acc_4_fu_618_p2;
        tmp_4_reg_2055 <= add_ln43_2_fu_568_p2[32'd52];
        tmp_6_reg_2062 <= add_ln43_5_fu_562_p2[32'd51];
        tmp_7_reg_2073 <= acc_4_fu_618_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage5_11001_grp0))) begin
        acc_6_reg_2094 <= acc_6_fu_813_p2;
        tmp_10_reg_2088 <= add_ln43_9_fu_757_p2[32'd51];
        tmp_11_reg_2099 <= acc_6_fu_813_p2[32'd31];
        tmp_8_reg_2081 <= add_ln43_4_fu_763_p2[32'd52];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage6_11001_grp0))) begin
        acc_8_reg_2120 <= acc_8_fu_1008_p2;
        tmp_12_reg_2107 <= add_ln43_6_fu_958_p2[32'd52];
        tmp_14_reg_2114 <= add_ln43_13_fu_952_p2[32'd51];
        tmp_15_reg_2125 <= acc_8_fu_1008_p2[32'd31];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln41_reg_1939 <= icmp_ln41_fu_275_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0))) begin
        in_act_0_load_reg_1988 <= in_act_0_q0;
        in_act_1_load_reg_1993 <= in_act_1_q0;
        in_act_2_load_reg_1998 <= in_act_2_q0;
        in_act_3_load_reg_2003 <= in_act_3_q0;
        in_act_4_load_reg_2008 <= in_act_4_q0;
        in_act_5_load_reg_2013 <= in_act_5_q0;
        in_act_6_load_reg_2018 <= in_act_6_q0;
        in_act_7_load_reg_2023 <= in_act_7_q0;
        select_ln43_13_reg_2175 <= select_ln43_13_fu_1728_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001_grp7) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        reg_246 <= m_axi_weights_0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage1_11001_grp0)) | ((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage6_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage5_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage4_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | 
    ((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage3_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage7_11001_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1)))) begin
        reg_250 <= grp_fu_242_p2;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_1939 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage2_11001_grp0))) begin
        acc_1_out_ap_vld = 1'b1;
    end else begin
        acc_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_1939 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_110;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        grp_fu_242_p0 = sext_ln43_29_fu_1715_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        grp_fu_242_p0 = sext_ln43_25_fu_1513_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p0 = sext_ln43_21_fu_1279_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p0 = sext_ln43_17_fu_1042_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p0 = sext_ln43_13_fu_847_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p0 = sext_ln43_9_fu_652_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p0 = sext_ln43_5_fu_496_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p0 = sext_ln43_1_fu_340_p1;
    end else begin
        grp_fu_242_p0 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp0))) begin
        grp_fu_242_p1 = sext_ln43_28_fu_1710_p1;
    end else if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp0))) begin
        grp_fu_242_p1 = sext_ln43_24_fu_1508_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p1 = sext_ln43_20_fu_1274_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p1 = sext_ln43_16_fu_1037_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p1 = sext_ln43_12_fu_842_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p1 = sext_ln43_8_fu_647_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p1 = sext_ln43_4_fu_491_p1;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp0) & (ap_enable_reg_pp0_iter0_reg == 1'b1))) begin
        grp_fu_242_p1 = sext_ln43_fu_335_p1;
    end else begin
        grp_fu_242_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_0_ce0_local = 1'b1;
    end else begin
        in_act_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_1_ce0_local = 1'b1;
    end else begin
        in_act_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_2_ce0_local = 1'b1;
    end else begin
        in_act_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_3_ce0_local = 1'b1;
    end else begin
        in_act_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_4_ce0_local = 1'b1;
    end else begin
        in_act_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_5_ce0_local = 1'b1;
    end else begin
        in_act_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_6_ce0_local = 1'b1;
    end else begin
        in_act_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        in_act_7_ce0_local = 1'b1;
    end else begin
        in_act_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_11001_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001_grp7) & (ap_enable_reg_pp0_iter0_reg 
    == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001_grp8)))) begin
        m_axi_weights_0_RREADY = 1'b1;
    end else begin
        m_axi_weights_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage3) & (1'b0 == ap_block_pp0_stage3_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((icmp_ln41_reg_1939 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_grp7) & (ap_enable_reg_pp0_iter0_reg == 1'b1)) | ((ap_enable_reg_pp0_iter1 
    == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_grp8)))) begin
        weights_blk_n_R = m_axi_weights_0_RVALID;
    end else begin
        weights_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_10_fu_1203_p2 = (acc_9_fu_1167_p4 + zext_ln43_4_fu_1199_p1);

assign acc_11_fu_1365_p4 = {{add_ln43_18_fu_1345_p2[51:20]}};

assign acc_12_fu_1401_p2 = (acc_11_fu_1365_p4 + zext_ln43_5_fu_1397_p1);

assign acc_13_fu_1567_p4 = {{add_ln43_20_fu_1547_p2[51:20]}};

assign acc_14_fu_1603_p2 = (acc_13_fu_1567_p4 + zext_ln43_6_fu_1599_p1);

assign acc_15_fu_1771_p4 = {{add_ln43_22_fu_1751_p2[51:20]}};

assign acc_16_fu_1807_p2 = (acc_15_fu_1771_p4 + zext_ln43_7_fu_1803_p1);

assign acc_17_fu_1907_p3 = ((or_ln43_23_fu_1901_p2[0:0] == 1'b1) ? select_ln43_14_fu_1893_p3 : acc_16_fu_1807_p2);

assign acc_1_fu_384_p4 = {{add_ln43_1_fu_364_p2[51:20]}};

assign acc_1_out = acc_fu_106;

assign acc_2_fu_420_p2 = (acc_1_fu_384_p4 + zext_ln43_fu_416_p1);

assign acc_3_fu_582_p4 = {{add_ln43_5_fu_562_p2[51:20]}};

assign acc_4_fu_618_p2 = (acc_3_fu_582_p4 + zext_ln43_1_fu_614_p1);

assign acc_5_fu_777_p4 = {{add_ln43_9_fu_757_p2[51:20]}};

assign acc_6_fu_813_p2 = (acc_5_fu_777_p4 + zext_ln43_2_fu_809_p1);

assign acc_7_fu_972_p4 = {{add_ln43_13_fu_952_p2[51:20]}};

assign acc_8_fu_1008_p2 = (acc_7_fu_972_p4 + zext_ln43_3_fu_1004_p1);

assign acc_9_fu_1167_p4 = {{add_ln43_16_fu_1147_p2[51:20]}};

assign add_ln41_fu_309_p2 = (ap_sig_allocacmp_i_2 + 10'd8);

assign add_ln43_10_fu_1351_p2 = ($signed(sext_ln43_22_fu_1337_p1) + $signed(sext_ln43_23_fu_1341_p1));

assign add_ln43_12_fu_1553_p2 = ($signed(sext_ln43_26_fu_1539_p1) + $signed(sext_ln43_27_fu_1543_p1));

assign add_ln43_13_fu_952_p2 = ($signed(shl_ln43_10_fu_936_p3) + $signed(reg_250));

assign add_ln43_14_fu_1757_p2 = ($signed(sext_ln43_30_fu_1743_p1) + $signed(sext_ln43_31_fu_1747_p1));

assign add_ln43_16_fu_1147_p2 = ($signed(shl_ln43_13_fu_1131_p3) + $signed(reg_250));

assign add_ln43_18_fu_1345_p2 = ($signed(shl_ln43_16_fu_1329_p3) + $signed(reg_250));

assign add_ln43_1_fu_364_p2 = ($signed(shl_ln43_2_fu_348_p3) + $signed(reg_250));

assign add_ln43_20_fu_1547_p2 = ($signed(shl_ln43_19_fu_1531_p3) + $signed(reg_250));

assign add_ln43_22_fu_1751_p2 = ($signed(shl_ln43_22_fu_1736_p3) + $signed(reg_250));

assign add_ln43_2_fu_568_p2 = ($signed(sext_ln43_6_fu_554_p1) + $signed(sext_ln43_7_fu_558_p1));

assign add_ln43_4_fu_763_p2 = ($signed(sext_ln43_10_fu_749_p1) + $signed(sext_ln43_11_fu_753_p1));

assign add_ln43_5_fu_562_p2 = ($signed(shl_ln43_5_fu_546_p3) + $signed(reg_250));

assign add_ln43_6_fu_958_p2 = ($signed(sext_ln43_14_fu_944_p1) + $signed(sext_ln43_15_fu_948_p1));

assign add_ln43_8_fu_1153_p2 = ($signed(sext_ln43_18_fu_1139_p1) + $signed(sext_ln43_19_fu_1143_p1));

assign add_ln43_9_fu_757_p2 = ($signed(shl_ln43_8_fu_741_p3) + $signed(reg_250));

assign add_ln43_fu_370_p2 = ($signed(sext_ln43_2_fu_356_p1) + $signed(sext_ln43_3_fu_360_p1));

assign and_ln43_10_fu_893_p2 = (xor_ln43_13_fu_872_p2 & or_ln43_7_fu_888_p2);

assign and_ln43_11_fu_910_p2 = (xor_ln43_17_fu_904_p2 & tmp_8_reg_2081);

assign and_ln43_12_fu_998_p2 = (tmp_13_fu_982_p3 & tmp_12_fu_964_p3);

assign and_ln43_13_fu_1052_p2 = (xor_ln43_18_fu_1047_p2 & tmp_14_reg_2114);

assign and_ln43_14_fu_1088_p2 = (xor_ln43_19_fu_1067_p2 & or_ln43_10_fu_1083_p2);

assign and_ln43_15_fu_1105_p2 = (xor_ln43_23_fu_1099_p2 & tmp_12_reg_2107);

assign and_ln43_16_fu_1193_p2 = (tmp_17_fu_1177_p3 & tmp_16_fu_1159_p3);

assign and_ln43_17_fu_1289_p2 = (xor_ln43_24_fu_1284_p2 & tmp_18_reg_2138);

assign and_ln43_18_fu_1253_p2 = (xor_ln43_25_fu_1229_p2 & or_ln43_13_fu_1247_p2);

assign and_ln43_19_fu_1305_p2 = (xor_ln43_29_fu_1299_p2 & tmp_16_reg_2133);

assign and_ln43_1_fu_506_p2 = (xor_ln43_fu_501_p2 & tmp_2_reg_2033);

assign and_ln43_20_fu_1391_p2 = (tmp_21_fu_1375_p3 & tmp_20_fu_1357_p3);

assign and_ln43_21_fu_1421_p2 = (xor_ln43_30_fu_1415_p2 & tmp_22_fu_1383_p3);

assign and_ln43_22_fu_1463_p2 = (xor_ln43_31_fu_1439_p2 & or_ln43_16_fu_1457_p2);

assign and_ln43_23_fu_1481_p2 = (xor_ln43_35_fu_1475_p2 & tmp_20_fu_1357_p3);

assign and_ln43_24_fu_1593_p2 = (tmp_25_fu_1577_p3 & tmp_24_fu_1559_p3);

assign and_ln43_25_fu_1623_p2 = (xor_ln43_36_fu_1617_p2 & tmp_26_fu_1585_p3);

assign and_ln43_26_fu_1665_p2 = (xor_ln43_37_fu_1641_p2 & or_ln43_19_fu_1659_p2);

assign and_ln43_27_fu_1683_p2 = (xor_ln43_41_fu_1677_p2 & tmp_24_fu_1559_p3);

assign and_ln43_28_fu_1797_p2 = (tmp_29_fu_1781_p3 & tmp_28_fu_1763_p3);

assign and_ln43_29_fu_1827_p2 = (xor_ln43_42_fu_1821_p2 & tmp_30_fu_1789_p3);

assign and_ln43_2_fu_470_p2 = (xor_ln43_1_fu_446_p2 & or_ln43_1_fu_464_p2);

assign and_ln43_30_fu_1869_p2 = (xor_ln43_43_fu_1845_p2 & or_ln43_22_fu_1863_p2);

assign and_ln43_31_fu_1887_p2 = (xor_ln43_47_fu_1881_p2 & tmp_28_fu_1763_p3);

assign and_ln43_3_fu_522_p2 = (xor_ln43_5_fu_516_p2 & tmp_reg_2028);

assign and_ln43_4_fu_608_p2 = (tmp_5_fu_592_p3 & tmp_4_fu_574_p3);

assign and_ln43_5_fu_662_p2 = (xor_ln43_6_fu_657_p2 & tmp_6_reg_2062);

assign and_ln43_6_fu_698_p2 = (xor_ln43_7_fu_677_p2 & or_ln43_4_fu_693_p2);

assign and_ln43_7_fu_715_p2 = (xor_ln43_11_fu_709_p2 & tmp_4_reg_2055);

assign and_ln43_8_fu_803_p2 = (tmp_9_fu_787_p3 & tmp_8_fu_769_p3);

assign and_ln43_9_fu_857_p2 = (xor_ln43_12_fu_852_p2 & tmp_10_reg_2088);

assign and_ln43_fu_410_p2 = (tmp_fu_376_p3 & tmp_1_fu_394_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_weights_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001_grp8 = ((m_axi_weights_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_weights_0_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001_grp1 = ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = ((1'b1 == ap_block_state2_pp0_stage1_iter0_grp1) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage1_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_01001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_11001_grp2 = ((1'b1 == ap_block_state3_pp0_stage2_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage2_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_grp2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = ((1'b1 == ap_block_state3_pp0_stage2_iter0_grp2) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage2_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_11001_grp3 = ((1'b1 == ap_block_state4_pp0_stage3_iter0_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage3_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_grp3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = ((1'b1 == ap_block_state4_pp0_stage3_iter0_grp3) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage3_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_11001_grp4 = ((1'b1 == ap_block_state5_pp0_stage4_iter0_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage4_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_grp4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = ((1'b1 == ap_block_state5_pp0_stage4_iter0_grp4) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage4_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_11001_grp5 = ((1'b1 == ap_block_state6_pp0_stage5_iter0_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage5_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_grp5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = ((1'b1 == ap_block_state6_pp0_stage5_iter0_grp5) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage5_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_11001_grp6 = ((1'b1 == ap_block_state7_pp0_stage6_iter0_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage6_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_grp6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = ((1'b1 == ap_block_state7_pp0_stage6_iter0_grp6) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage6_subdone_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_11001_grp7 = ((1'b1 == ap_block_state8_pp0_stage7_iter0_grp7) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage7_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_grp7 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = ((1'b1 == ap_block_state8_pp0_stage7_iter0_grp7) & (ap_enable_reg_pp0_iter0_reg == 1'b1));
end

assign ap_block_pp0_stage7_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0_grp1 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage2_iter0_grp2 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_pp0_stage3_iter0_grp3 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage4_iter0_grp4 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state6_pp0_stage5_iter0_grp5 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state7_pp0_stage6_iter0_grp6 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state8_pp0_stage7_iter0_grp7 = ((icmp_ln41_reg_1939 == 1'd1) & (m_axi_weights_0_RVALID == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_ready = ap_ready_sig;

assign icmp_ln41_fu_275_p2 = ((ap_sig_allocacmp_i_2 < 10'd784) ? 1'b1 : 1'b0);

assign in_act_0_address0 = zext_ln38_fu_297_p1;

assign in_act_0_ce0 = in_act_0_ce0_local;

assign in_act_1_address0 = zext_ln38_fu_297_p1;

assign in_act_1_ce0 = in_act_1_ce0_local;

assign in_act_2_address0 = zext_ln38_fu_297_p1;

assign in_act_2_ce0 = in_act_2_ce0_local;

assign in_act_3_address0 = zext_ln38_fu_297_p1;

assign in_act_3_ce0 = in_act_3_ce0_local;

assign in_act_4_address0 = zext_ln38_fu_297_p1;

assign in_act_4_ce0 = in_act_4_ce0_local;

assign in_act_5_address0 = zext_ln38_fu_297_p1;

assign in_act_5_ce0 = in_act_5_ce0_local;

assign in_act_6_address0 = zext_ln38_fu_297_p1;

assign in_act_6_ce0 = in_act_6_ce0_local;

assign in_act_7_address0 = zext_ln38_fu_297_p1;

assign in_act_7_ce0 = in_act_7_ce0_local;

assign lshr_ln_fu_287_p4 = {{ap_sig_allocacmp_i_2[9:3]}};

assign m_axi_weights_0_ARADDR = 64'd0;

assign m_axi_weights_0_ARBURST = 2'd0;

assign m_axi_weights_0_ARCACHE = 4'd0;

assign m_axi_weights_0_ARID = 1'd0;

assign m_axi_weights_0_ARLEN = 32'd0;

assign m_axi_weights_0_ARLOCK = 2'd0;

assign m_axi_weights_0_ARPROT = 3'd0;

assign m_axi_weights_0_ARQOS = 4'd0;

assign m_axi_weights_0_ARREGION = 4'd0;

assign m_axi_weights_0_ARSIZE = 3'd0;

assign m_axi_weights_0_ARUSER = 1'd0;

assign m_axi_weights_0_ARVALID = 1'b0;

assign m_axi_weights_0_AWADDR = 64'd0;

assign m_axi_weights_0_AWBURST = 2'd0;

assign m_axi_weights_0_AWCACHE = 4'd0;

assign m_axi_weights_0_AWID = 1'd0;

assign m_axi_weights_0_AWLEN = 32'd0;

assign m_axi_weights_0_AWLOCK = 2'd0;

assign m_axi_weights_0_AWPROT = 3'd0;

assign m_axi_weights_0_AWQOS = 4'd0;

assign m_axi_weights_0_AWREGION = 4'd0;

assign m_axi_weights_0_AWSIZE = 3'd0;

assign m_axi_weights_0_AWUSER = 1'd0;

assign m_axi_weights_0_AWVALID = 1'b0;

assign m_axi_weights_0_BREADY = 1'b0;

assign m_axi_weights_0_WDATA = 16'd0;

assign m_axi_weights_0_WID = 1'd0;

assign m_axi_weights_0_WLAST = 1'b0;

assign m_axi_weights_0_WSTRB = 2'd0;

assign m_axi_weights_0_WUSER = 1'd0;

assign m_axi_weights_0_WVALID = 1'b0;

assign or_ln43_10_fu_1083_p2 = (xor_ln43_21_fu_1078_p2 | tmp_15_reg_2125);

assign or_ln43_11_fu_1110_p2 = (and_ln43_15_fu_1105_p2 | and_ln43_14_fu_1088_p2);

assign or_ln43_12_fu_867_p2 = (xor_ln43_14_fu_862_p2 | tmp_11_reg_2099);

assign or_ln43_13_fu_1247_p2 = (xor_ln43_27_fu_1241_p2 | tmp_19_fu_1209_p3);

assign or_ln43_14_fu_1310_p2 = (and_ln43_19_fu_1305_p2 | and_ln43_18_reg_2154);

assign or_ln43_15_fu_899_p2 = (tmp_11_reg_2099 | and_ln43_9_fu_857_p2);

assign or_ln43_16_fu_1457_p2 = (xor_ln43_33_fu_1451_p2 | tmp_23_fu_1407_p3);

assign or_ln43_17_fu_1487_p2 = (and_ln43_23_fu_1481_p2 | and_ln43_22_fu_1463_p2);

assign or_ln43_18_fu_1062_p2 = (xor_ln43_20_fu_1057_p2 | tmp_15_reg_2125);

assign or_ln43_19_fu_1659_p2 = (xor_ln43_39_fu_1653_p2 | tmp_27_fu_1609_p3);

assign or_ln43_1_fu_464_p2 = (xor_ln43_3_fu_458_p2 | tmp_3_fu_426_p3);

assign or_ln43_20_fu_1689_p2 = (and_ln43_27_fu_1683_p2 | and_ln43_26_fu_1665_p2);

assign or_ln43_21_fu_1094_p2 = (tmp_15_reg_2125 | and_ln43_13_fu_1052_p2);

assign or_ln43_22_fu_1863_p2 = (xor_ln43_45_fu_1857_p2 | tmp_31_fu_1813_p3);

assign or_ln43_23_fu_1901_p2 = (and_ln43_31_fu_1887_p2 | and_ln43_30_fu_1869_p2);

assign or_ln43_24_fu_1223_p2 = (xor_ln43_26_fu_1217_p2 | tmp_19_fu_1209_p3);

assign or_ln43_25_fu_1294_p2 = (tmp_19_reg_2148 | and_ln43_17_fu_1289_p2);

assign or_ln43_26_fu_1433_p2 = (xor_ln43_32_fu_1427_p2 | tmp_23_fu_1407_p3);

assign or_ln43_27_fu_1469_p2 = (tmp_23_fu_1407_p3 | and_ln43_21_fu_1421_p2);

assign or_ln43_28_fu_1635_p2 = (xor_ln43_38_fu_1629_p2 | tmp_27_fu_1609_p3);

assign or_ln43_29_fu_1671_p2 = (tmp_27_fu_1609_p3 | and_ln43_25_fu_1623_p2);

assign or_ln43_2_fu_527_p2 = (and_ln43_3_fu_522_p2 | and_ln43_2_reg_2049);

assign or_ln43_30_fu_1839_p2 = (xor_ln43_44_fu_1833_p2 | tmp_31_fu_1813_p3);

assign or_ln43_31_fu_1875_p2 = (tmp_31_fu_1813_p3 | and_ln43_29_fu_1827_p2);

assign or_ln43_3_fu_511_p2 = (tmp_3_reg_2043 | and_ln43_1_fu_506_p2);

assign or_ln43_4_fu_693_p2 = (xor_ln43_9_fu_688_p2 | tmp_7_reg_2073);

assign or_ln43_5_fu_720_p2 = (and_ln43_7_fu_715_p2 | and_ln43_6_fu_698_p2);

assign or_ln43_6_fu_672_p2 = (xor_ln43_8_fu_667_p2 | tmp_7_reg_2073);

assign or_ln43_7_fu_888_p2 = (xor_ln43_15_fu_883_p2 | tmp_11_reg_2099);

assign or_ln43_8_fu_915_p2 = (and_ln43_11_fu_910_p2 | and_ln43_10_fu_893_p2);

assign or_ln43_9_fu_704_p2 = (tmp_7_reg_2073 | and_ln43_5_fu_662_p2);

assign or_ln43_fu_440_p2 = (xor_ln43_2_fu_434_p2 | tmp_3_fu_426_p3);

assign select_ln43_10_fu_1518_p3 = ((and_ln43_22_reg_2165[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_11_fu_1525_p3 = ((or_ln43_17_reg_2170[0:0] == 1'b1) ? select_ln43_10_fu_1518_p3 : acc_12_reg_2160);

assign select_ln43_12_fu_1720_p3 = ((and_ln43_26_fu_1665_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_13_fu_1728_p3 = ((or_ln43_20_fu_1689_p2[0:0] == 1'b1) ? select_ln43_12_fu_1720_p3 : acc_14_fu_1603_p2);

assign select_ln43_14_fu_1893_p3 = ((and_ln43_30_fu_1869_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_1_fu_539_p3 = ((or_ln43_2_fu_527_p2[0:0] == 1'b1) ? select_ln43_fu_532_p3 : acc_2_reg_2038);

assign select_ln43_2_fu_726_p3 = ((and_ln43_6_fu_698_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_3_fu_734_p3 = ((or_ln43_5_fu_720_p2[0:0] == 1'b1) ? select_ln43_2_fu_726_p3 : acc_4_reg_2068);

assign select_ln43_4_fu_921_p3 = ((and_ln43_10_fu_893_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_5_fu_929_p3 = ((or_ln43_8_fu_915_p2[0:0] == 1'b1) ? select_ln43_4_fu_921_p3 : acc_6_reg_2094);

assign select_ln43_6_fu_1116_p3 = ((and_ln43_14_fu_1088_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_7_fu_1124_p3 = ((or_ln43_11_fu_1110_p2[0:0] == 1'b1) ? select_ln43_6_fu_1116_p3 : acc_8_reg_2120);

assign select_ln43_8_fu_1315_p3 = ((and_ln43_18_reg_2154[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln43_9_fu_1322_p3 = ((or_ln43_14_fu_1310_p2[0:0] == 1'b1) ? select_ln43_8_fu_1315_p3 : acc_10_reg_2143);

assign select_ln43_fu_532_p3 = ((and_ln43_2_reg_2049[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln38_cast_fu_258_p1 = $signed(sext_ln38);

assign sext_ln43_10_fu_749_p1 = shl_ln43_8_fu_741_p3;

assign sext_ln43_11_fu_753_p1 = reg_250;

assign sext_ln43_12_fu_842_p1 = $signed(shl_ln43_9_fu_827_p3);

assign sext_ln43_13_fu_847_p1 = $signed(shl_ln43_s_fu_835_p3);

assign sext_ln43_14_fu_944_p1 = shl_ln43_10_fu_936_p3;

assign sext_ln43_15_fu_948_p1 = reg_250;

assign sext_ln43_16_fu_1037_p1 = $signed(shl_ln43_11_fu_1022_p3);

assign sext_ln43_17_fu_1042_p1 = $signed(shl_ln43_12_fu_1030_p3);

assign sext_ln43_18_fu_1139_p1 = shl_ln43_13_fu_1131_p3;

assign sext_ln43_19_fu_1143_p1 = reg_250;

assign sext_ln43_1_fu_340_p1 = $signed(shl_ln43_1_fu_328_p3);

assign sext_ln43_20_fu_1274_p1 = $signed(shl_ln43_14_fu_1259_p3);

assign sext_ln43_21_fu_1279_p1 = $signed(shl_ln43_15_fu_1267_p3);

assign sext_ln43_22_fu_1337_p1 = shl_ln43_16_fu_1329_p3;

assign sext_ln43_23_fu_1341_p1 = reg_250;

assign sext_ln43_24_fu_1508_p1 = $signed(shl_ln43_17_fu_1493_p3);

assign sext_ln43_25_fu_1513_p1 = $signed(shl_ln43_18_fu_1501_p3);

assign sext_ln43_26_fu_1539_p1 = shl_ln43_19_fu_1531_p3;

assign sext_ln43_27_fu_1543_p1 = reg_250;

assign sext_ln43_28_fu_1710_p1 = $signed(shl_ln43_20_fu_1695_p3);

assign sext_ln43_29_fu_1715_p1 = $signed(shl_ln43_21_fu_1703_p3);

assign sext_ln43_2_fu_356_p1 = shl_ln43_2_fu_348_p3;

assign sext_ln43_30_fu_1743_p1 = shl_ln43_22_fu_1736_p3;

assign sext_ln43_31_fu_1747_p1 = reg_250;

assign sext_ln43_3_fu_360_p1 = reg_250;

assign sext_ln43_4_fu_491_p1 = $signed(shl_ln43_3_fu_476_p3);

assign sext_ln43_5_fu_496_p1 = $signed(shl_ln43_4_fu_484_p3);

assign sext_ln43_6_fu_554_p1 = shl_ln43_5_fu_546_p3;

assign sext_ln43_7_fu_558_p1 = reg_250;

assign sext_ln43_8_fu_647_p1 = $signed(shl_ln43_6_fu_632_p3);

assign sext_ln43_9_fu_652_p1 = $signed(shl_ln43_7_fu_640_p3);

assign sext_ln43_fu_335_p1 = $signed(shl_ln_fu_320_p3);

assign shl_ln43_10_fu_936_p3 = {{select_ln43_5_fu_929_p3}, {20'd0}};

assign shl_ln43_11_fu_1022_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_12_fu_1030_p3 = {{in_act_4_load_reg_2008}, {10'd0}};

assign shl_ln43_13_fu_1131_p3 = {{select_ln43_7_fu_1124_p3}, {20'd0}};

assign shl_ln43_14_fu_1259_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_15_fu_1267_p3 = {{in_act_5_load_reg_2013}, {10'd0}};

assign shl_ln43_16_fu_1329_p3 = {{select_ln43_9_fu_1322_p3}, {20'd0}};

assign shl_ln43_17_fu_1493_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_18_fu_1501_p3 = {{in_act_6_load_reg_2018}, {10'd0}};

assign shl_ln43_19_fu_1531_p3 = {{select_ln43_11_fu_1525_p3}, {20'd0}};

assign shl_ln43_1_fu_328_p3 = {{in_act_0_load_reg_1988}, {10'd0}};

assign shl_ln43_20_fu_1695_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_21_fu_1703_p3 = {{in_act_7_load_reg_2023}, {10'd0}};

assign shl_ln43_22_fu_1736_p3 = {{select_ln43_13_reg_2175}, {20'd0}};

assign shl_ln43_2_fu_348_p3 = {{acc_fu_106}, {20'd0}};

assign shl_ln43_3_fu_476_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_4_fu_484_p3 = {{in_act_1_load_reg_1993}, {10'd0}};

assign shl_ln43_5_fu_546_p3 = {{select_ln43_1_fu_539_p3}, {20'd0}};

assign shl_ln43_6_fu_632_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_7_fu_640_p3 = {{in_act_2_load_reg_1998}, {10'd0}};

assign shl_ln43_8_fu_741_p3 = {{select_ln43_3_fu_734_p3}, {20'd0}};

assign shl_ln43_9_fu_827_p3 = {{reg_246}, {10'd0}};

assign shl_ln43_s_fu_835_p3 = {{in_act_3_load_reg_2003}, {10'd0}};

assign shl_ln_fu_320_p3 = {{reg_246}, {10'd0}};

assign tmp_12_fu_964_p3 = add_ln43_6_fu_958_p2[32'd52];

assign tmp_13_fu_982_p3 = reg_250[32'd19];

assign tmp_16_fu_1159_p3 = add_ln43_8_fu_1153_p2[32'd52];

assign tmp_17_fu_1177_p3 = reg_250[32'd19];

assign tmp_18_fu_1185_p3 = add_ln43_16_fu_1147_p2[32'd51];

assign tmp_19_fu_1209_p3 = acc_10_fu_1203_p2[32'd31];

assign tmp_1_fu_394_p3 = reg_250[32'd19];

assign tmp_20_fu_1357_p3 = add_ln43_10_fu_1351_p2[32'd52];

assign tmp_21_fu_1375_p3 = reg_250[32'd19];

assign tmp_22_fu_1383_p3 = add_ln43_18_fu_1345_p2[32'd51];

assign tmp_23_fu_1407_p3 = acc_12_fu_1401_p2[32'd31];

assign tmp_24_fu_1559_p3 = add_ln43_12_fu_1553_p2[32'd52];

assign tmp_25_fu_1577_p3 = reg_250[32'd19];

assign tmp_26_fu_1585_p3 = add_ln43_20_fu_1547_p2[32'd51];

assign tmp_27_fu_1609_p3 = acc_14_fu_1603_p2[32'd31];

assign tmp_28_fu_1763_p3 = add_ln43_14_fu_1757_p2[32'd52];

assign tmp_29_fu_1781_p3 = reg_250[32'd19];

assign tmp_2_fu_402_p3 = add_ln43_1_fu_364_p2[32'd51];

assign tmp_30_fu_1789_p3 = add_ln43_22_fu_1751_p2[32'd51];

assign tmp_31_fu_1813_p3 = acc_16_fu_1807_p2[32'd31];

assign tmp_3_fu_426_p3 = acc_2_fu_420_p2[32'd31];

assign tmp_4_fu_574_p3 = add_ln43_2_fu_568_p2[32'd52];

assign tmp_5_fu_592_p3 = reg_250[32'd19];

assign tmp_8_fu_769_p3 = add_ln43_4_fu_763_p2[32'd52];

assign tmp_9_fu_787_p3 = reg_250[32'd19];

assign tmp_fu_376_p3 = add_ln43_fu_370_p2[32'd52];

assign xor_ln43_10_fu_682_p2 = (or_ln43_6_fu_672_p2 ^ 1'd1);

assign xor_ln43_11_fu_709_p2 = (or_ln43_9_fu_704_p2 ^ 1'd1);

assign xor_ln43_12_fu_852_p2 = (tmp_11_reg_2099 ^ 1'd1);

assign xor_ln43_13_fu_872_p2 = (tmp_8_reg_2081 ^ 1'd1);

assign xor_ln43_14_fu_862_p2 = (tmp_10_reg_2088 ^ 1'd1);

assign xor_ln43_15_fu_883_p2 = (xor_ln43_16_fu_877_p2 ^ tmp_8_reg_2081);

assign xor_ln43_16_fu_877_p2 = (or_ln43_12_fu_867_p2 ^ 1'd1);

assign xor_ln43_17_fu_904_p2 = (or_ln43_15_fu_899_p2 ^ 1'd1);

assign xor_ln43_18_fu_1047_p2 = (tmp_15_reg_2125 ^ 1'd1);

assign xor_ln43_19_fu_1067_p2 = (tmp_12_reg_2107 ^ 1'd1);

assign xor_ln43_1_fu_446_p2 = (tmp_fu_376_p3 ^ 1'd1);

assign xor_ln43_20_fu_1057_p2 = (tmp_14_reg_2114 ^ 1'd1);

assign xor_ln43_21_fu_1078_p2 = (xor_ln43_22_fu_1072_p2 ^ tmp_12_reg_2107);

assign xor_ln43_22_fu_1072_p2 = (or_ln43_18_fu_1062_p2 ^ 1'd1);

assign xor_ln43_23_fu_1099_p2 = (or_ln43_21_fu_1094_p2 ^ 1'd1);

assign xor_ln43_24_fu_1284_p2 = (tmp_19_reg_2148 ^ 1'd1);

assign xor_ln43_25_fu_1229_p2 = (tmp_16_fu_1159_p3 ^ 1'd1);

assign xor_ln43_26_fu_1217_p2 = (tmp_18_fu_1185_p3 ^ 1'd1);

assign xor_ln43_27_fu_1241_p2 = (xor_ln43_28_fu_1235_p2 ^ tmp_16_fu_1159_p3);

assign xor_ln43_28_fu_1235_p2 = (or_ln43_24_fu_1223_p2 ^ 1'd1);

assign xor_ln43_29_fu_1299_p2 = (or_ln43_25_fu_1294_p2 ^ 1'd1);

assign xor_ln43_2_fu_434_p2 = (tmp_2_fu_402_p3 ^ 1'd1);

assign xor_ln43_30_fu_1415_p2 = (tmp_23_fu_1407_p3 ^ 1'd1);

assign xor_ln43_31_fu_1439_p2 = (tmp_20_fu_1357_p3 ^ 1'd1);

assign xor_ln43_32_fu_1427_p2 = (tmp_22_fu_1383_p3 ^ 1'd1);

assign xor_ln43_33_fu_1451_p2 = (xor_ln43_34_fu_1445_p2 ^ tmp_20_fu_1357_p3);

assign xor_ln43_34_fu_1445_p2 = (or_ln43_26_fu_1433_p2 ^ 1'd1);

assign xor_ln43_35_fu_1475_p2 = (or_ln43_27_fu_1469_p2 ^ 1'd1);

assign xor_ln43_36_fu_1617_p2 = (tmp_27_fu_1609_p3 ^ 1'd1);

assign xor_ln43_37_fu_1641_p2 = (tmp_24_fu_1559_p3 ^ 1'd1);

assign xor_ln43_38_fu_1629_p2 = (tmp_26_fu_1585_p3 ^ 1'd1);

assign xor_ln43_39_fu_1653_p2 = (xor_ln43_40_fu_1647_p2 ^ tmp_24_fu_1559_p3);

assign xor_ln43_3_fu_458_p2 = (xor_ln43_4_fu_452_p2 ^ tmp_fu_376_p3);

assign xor_ln43_40_fu_1647_p2 = (or_ln43_28_fu_1635_p2 ^ 1'd1);

assign xor_ln43_41_fu_1677_p2 = (or_ln43_29_fu_1671_p2 ^ 1'd1);

assign xor_ln43_42_fu_1821_p2 = (tmp_31_fu_1813_p3 ^ 1'd1);

assign xor_ln43_43_fu_1845_p2 = (tmp_28_fu_1763_p3 ^ 1'd1);

assign xor_ln43_44_fu_1833_p2 = (tmp_30_fu_1789_p3 ^ 1'd1);

assign xor_ln43_45_fu_1857_p2 = (xor_ln43_46_fu_1851_p2 ^ tmp_28_fu_1763_p3);

assign xor_ln43_46_fu_1851_p2 = (or_ln43_30_fu_1839_p2 ^ 1'd1);

assign xor_ln43_47_fu_1881_p2 = (or_ln43_31_fu_1875_p2 ^ 1'd1);

assign xor_ln43_4_fu_452_p2 = (or_ln43_fu_440_p2 ^ 1'd1);

assign xor_ln43_5_fu_516_p2 = (or_ln43_3_fu_511_p2 ^ 1'd1);

assign xor_ln43_6_fu_657_p2 = (tmp_7_reg_2073 ^ 1'd1);

assign xor_ln43_7_fu_677_p2 = (tmp_4_reg_2055 ^ 1'd1);

assign xor_ln43_8_fu_667_p2 = (tmp_6_reg_2062 ^ 1'd1);

assign xor_ln43_9_fu_688_p2 = (xor_ln43_10_fu_682_p2 ^ tmp_4_reg_2055);

assign xor_ln43_fu_501_p2 = (tmp_3_reg_2043 ^ 1'd1);

assign zext_ln38_fu_297_p1 = lshr_ln_fu_287_p4;

assign zext_ln43_1_fu_614_p1 = and_ln43_4_fu_608_p2;

assign zext_ln43_2_fu_809_p1 = and_ln43_8_fu_803_p2;

assign zext_ln43_3_fu_1004_p1 = and_ln43_12_fu_998_p2;

assign zext_ln43_4_fu_1199_p1 = and_ln43_16_fu_1193_p2;

assign zext_ln43_5_fu_1397_p1 = and_ln43_20_fu_1391_p2;

assign zext_ln43_6_fu_1599_p1 = and_ln43_24_fu_1593_p2;

assign zext_ln43_7_fu_1803_p1 = and_ln43_28_fu_1797_p2;

assign zext_ln43_fu_416_p1 = and_ln43_fu_410_p2;

endmodule //mlp_top_dense_relu_784_512_Pipeline_INNER
