// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module mlp_top_dense_relu_256_128_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_act_0_address0,
        in_act_0_ce0,
        in_act_0_q0,
        in_act_0_address1,
        in_act_0_ce1,
        in_act_0_q1,
        in_act_1_address0,
        in_act_1_ce0,
        in_act_1_q0,
        in_act_1_address1,
        in_act_1_ce1,
        in_act_1_q1,
        in_act_2_address0,
        in_act_2_ce0,
        in_act_2_q0,
        in_act_2_address1,
        in_act_2_ce1,
        in_act_2_q1,
        in_act_3_address0,
        in_act_3_ce0,
        in_act_3_q0,
        in_act_3_address1,
        in_act_3_ce1,
        in_act_3_q1,
        out_act_0_address0,
        out_act_0_ce0,
        out_act_0_we0,
        out_act_0_d0,
        out_act_1_address0,
        out_act_1_ce0,
        out_act_1_we0,
        out_act_1_d0,
        out_act_2_address0,
        out_act_2_ce0,
        out_act_2_we0,
        out_act_2_d0,
        out_act_3_address0,
        out_act_3_ce0,
        out_act_3_we0,
        out_act_3_d0
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] in_act_0_address0;
output   in_act_0_ce0;
input  [14:0] in_act_0_q0;
output  [5:0] in_act_0_address1;
output   in_act_0_ce1;
input  [14:0] in_act_0_q1;
output  [5:0] in_act_1_address0;
output   in_act_1_ce0;
input  [14:0] in_act_1_q0;
output  [5:0] in_act_1_address1;
output   in_act_1_ce1;
input  [14:0] in_act_1_q1;
output  [5:0] in_act_2_address0;
output   in_act_2_ce0;
input  [14:0] in_act_2_q0;
output  [5:0] in_act_2_address1;
output   in_act_2_ce1;
input  [14:0] in_act_2_q1;
output  [5:0] in_act_3_address0;
output   in_act_3_ce0;
input  [14:0] in_act_3_q0;
output  [5:0] in_act_3_address1;
output   in_act_3_ce1;
input  [14:0] in_act_3_q1;
output  [4:0] out_act_0_address0;
output   out_act_0_ce0;
output   out_act_0_we0;
output  [14:0] out_act_0_d0;
output  [4:0] out_act_1_address0;
output   out_act_1_ce0;
output   out_act_1_we0;
output  [14:0] out_act_1_d0;
output  [4:0] out_act_2_address0;
output   out_act_2_ce0;
output   out_act_2_we0;
output  [14:0] out_act_2_d0;
output  [4:0] out_act_3_address0;
output   out_act_3_ce0;
output   out_act_3_we0;
output  [14:0] out_act_3_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] bias_37_address0;
wire   [10:0] bias_37_q0;
wire   [7:0] add_ln19_fu_206_p2;
reg   [7:0] add_ln19_reg_418;
wire    ap_CS_fsm_state2;
wire   [6:0] trunc_ln19_fu_217_p1;
reg   [6:0] trunc_ln19_reg_428;
wire    ap_CS_fsm_state3;
wire   [1:0] trunc_ln19_2_fu_221_p1;
reg   [1:0] trunc_ln19_2_reg_433;
wire   [20:0] acc_fu_224_p3;
reg   [20:0] acc_reg_438;
reg   [4:0] lshr_ln3_reg_443;
wire   [30:0] trunc_ln23_fu_245_p1;
reg   [30:0] trunc_ln23_reg_448;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln29_fu_249_p2;
reg   [0:0] icmp_ln29_reg_453;
wire   [14:0] select_ln30_fu_371_p3;
reg   [14:0] select_ln30_reg_458;
wire    ap_CS_fsm_state6;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_done;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_idle;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_ready;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_address0;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_ce0;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_address1;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_ce1;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_address0;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_ce0;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_address1;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_ce1;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_address0;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_ce0;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_address1;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_ce1;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_address0;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_ce0;
wire   [5:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_address1;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_ce1;
wire   [31:0] grp_dense_relu_256_128_Pipeline_INNER_fu_169_acc_01_out;
wire    grp_dense_relu_256_128_Pipeline_INNER_fu_169_acc_01_out_ap_vld;
reg    grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [63:0] zext_ln19_fu_212_p1;
wire   [0:0] icmp_ln19_fu_200_p2;
wire   [63:0] zext_ln19_3_fu_379_p1;
wire    ap_CS_fsm_state7;
reg   [7:0] o_fu_96;
reg    bias_37_ce0_local;
reg    out_act_2_we0_local;
reg    out_act_2_ce0_local;
reg    out_act_1_we0_local;
reg    out_act_1_ce0_local;
reg    out_act_0_we0_local;
reg    out_act_0_ce0_local;
reg    out_act_3_we0_local;
reg    out_act_3_ce0_local;
wire   [30:0] result_fu_255_p3;
wire   [8:0] trunc_ln30_fu_279_p1;
wire   [0:0] icmp_ln30_fu_283_p2;
wire   [0:0] tmp_fu_271_p3;
wire   [0:0] and_ln30_fu_297_p2;
wire   [15:0] trunc_ln6_fu_261_p4;
wire   [15:0] zext_ln30_fu_303_p1;
wire   [15:0] add_ln30_fu_307_p2;
wire   [4:0] tmp_s_fu_325_p4;
wire   [0:0] tmp_100_fu_289_p3;
wire   [0:0] tmp_101_fu_317_p3;
wire   [0:0] xor_ln30_fu_341_p2;
wire   [0:0] icmp_ln30_5_fu_335_p2;
wire   [0:0] or_ln30_fu_347_p2;
wire   [0:0] and_ln30_3_fu_353_p2;
wire   [0:0] xor_ln30_3_fu_359_p2;
wire   [0:0] or_ln30_3_fu_365_p2;
wire   [14:0] trunc_ln30_3_fu_313_p1;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start_reg = 1'b0;
#0 o_fu_96 = 8'd0;
end

mlp_top_dense_relu_256_128_s_bias_37_ROM_AUTO_1R #(
    .DataWidth( 11 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
bias_37_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(bias_37_address0),
    .ce0(bias_37_ce0_local),
    .q0(bias_37_q0)
);

mlp_top_dense_relu_256_128_Pipeline_INNER grp_dense_relu_256_128_Pipeline_INNER_fu_169(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start),
    .ap_done(grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_done),
    .ap_idle(grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_idle),
    .ap_ready(grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_ready),
    .sext_ln20(acc_reg_438),
    .o(trunc_ln19_reg_428),
    .in_act_0_address0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_address0),
    .in_act_0_ce0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_ce0),
    .in_act_0_q0(in_act_0_q0),
    .in_act_0_address1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_address1),
    .in_act_0_ce1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_ce1),
    .in_act_0_q1(in_act_0_q1),
    .in_act_1_address0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_address0),
    .in_act_1_ce0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_ce0),
    .in_act_1_q0(in_act_1_q0),
    .in_act_1_address1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_address1),
    .in_act_1_ce1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_ce1),
    .in_act_1_q1(in_act_1_q1),
    .in_act_2_address0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_address0),
    .in_act_2_ce0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_ce0),
    .in_act_2_q0(in_act_2_q0),
    .in_act_2_address1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_address1),
    .in_act_2_ce1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_ce1),
    .in_act_2_q1(in_act_2_q1),
    .in_act_3_address0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_address0),
    .in_act_3_ce0(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_ce0),
    .in_act_3_q0(in_act_3_q0),
    .in_act_3_address1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_address1),
    .in_act_3_ce1(grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_ce1),
    .in_act_3_q1(in_act_3_q1),
    .acc_01_out(grp_dense_relu_256_128_Pipeline_INNER_fu_169_acc_01_out),
    .acc_01_out_ap_vld(grp_dense_relu_256_128_Pipeline_INNER_fu_169_acc_01_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start_reg <= 1'b1;
        end else if ((grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_ready == 1'b1)) begin
            grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_fu_96 <= 8'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        o_fu_96 <= add_ln19_reg_418;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        acc_reg_438[20 : 10] <= acc_fu_224_p3[20 : 10];
        lshr_ln3_reg_443 <= {{o_fu_96[6:2]}};
        trunc_ln19_2_reg_433 <= trunc_ln19_2_fu_221_p1;
        trunc_ln19_reg_428 <= trunc_ln19_fu_217_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln19_reg_418 <= add_ln19_fu_206_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln29_reg_453 <= icmp_ln29_fu_249_p2;
        trunc_ln23_reg_448 <= trunc_ln23_fu_245_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        select_ln30_reg_458 <= select_ln30_fu_371_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln19_fu_200_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_200_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        bias_37_ce0_local = 1'b1;
    end else begin
        bias_37_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_act_0_ce0_local = 1'b1;
    end else begin
        out_act_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln19_2_reg_433 == 2'd0))) begin
        out_act_0_we0_local = 1'b1;
    end else begin
        out_act_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_act_1_ce0_local = 1'b1;
    end else begin
        out_act_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln19_2_reg_433 == 2'd1))) begin
        out_act_1_we0_local = 1'b1;
    end else begin
        out_act_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_act_2_ce0_local = 1'b1;
    end else begin
        out_act_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln19_2_reg_433 == 2'd2))) begin
        out_act_2_we0_local = 1'b1;
    end else begin
        out_act_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        out_act_3_ce0_local = 1'b1;
    end else begin
        out_act_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (trunc_ln19_2_reg_433 == 2'd3))) begin
        out_act_3_we0_local = 1'b1;
    end else begin
        out_act_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln19_fu_200_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_fu_224_p3 = {{bias_37_q0}, {10'd0}};

assign add_ln19_fu_206_p2 = (o_fu_96 + 8'd1);

assign add_ln30_fu_307_p2 = (trunc_ln6_fu_261_p4 + zext_ln30_fu_303_p1);

assign and_ln30_3_fu_353_p2 = (or_ln30_fu_347_p2 & icmp_ln30_5_fu_335_p2);

assign and_ln30_fu_297_p2 = (tmp_fu_271_p3 & icmp_ln30_fu_283_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign bias_37_address0 = zext_ln19_fu_212_p1;

assign grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start = grp_dense_relu_256_128_Pipeline_INNER_fu_169_ap_start_reg;

assign icmp_ln19_fu_200_p2 = ((o_fu_96 == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln29_fu_249_p2 = (($signed(grp_dense_relu_256_128_Pipeline_INNER_fu_169_acc_01_out) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln30_5_fu_335_p2 = ((tmp_s_fu_325_p4 == 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln30_fu_283_p2 = ((trunc_ln30_fu_279_p1 != 9'd0) ? 1'b1 : 1'b0);

assign in_act_0_address0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_address0;

assign in_act_0_address1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_address1;

assign in_act_0_ce0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_ce0;

assign in_act_0_ce1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_0_ce1;

assign in_act_1_address0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_address0;

assign in_act_1_address1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_address1;

assign in_act_1_ce0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_ce0;

assign in_act_1_ce1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_1_ce1;

assign in_act_2_address0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_address0;

assign in_act_2_address1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_address1;

assign in_act_2_ce0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_ce0;

assign in_act_2_ce1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_2_ce1;

assign in_act_3_address0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_address0;

assign in_act_3_address1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_address1;

assign in_act_3_ce0 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_ce0;

assign in_act_3_ce1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_in_act_3_ce1;

assign or_ln30_3_fu_365_p2 = (xor_ln30_3_fu_359_p2 | tmp_101_fu_317_p3);

assign or_ln30_fu_347_p2 = (xor_ln30_fu_341_p2 | tmp_101_fu_317_p3);

assign out_act_0_address0 = zext_ln19_3_fu_379_p1;

assign out_act_0_ce0 = out_act_0_ce0_local;

assign out_act_0_d0 = select_ln30_reg_458;

assign out_act_0_we0 = out_act_0_we0_local;

assign out_act_1_address0 = zext_ln19_3_fu_379_p1;

assign out_act_1_ce0 = out_act_1_ce0_local;

assign out_act_1_d0 = select_ln30_reg_458;

assign out_act_1_we0 = out_act_1_we0_local;

assign out_act_2_address0 = zext_ln19_3_fu_379_p1;

assign out_act_2_ce0 = out_act_2_ce0_local;

assign out_act_2_d0 = select_ln30_reg_458;

assign out_act_2_we0 = out_act_2_we0_local;

assign out_act_3_address0 = zext_ln19_3_fu_379_p1;

assign out_act_3_ce0 = out_act_3_ce0_local;

assign out_act_3_d0 = select_ln30_reg_458;

assign out_act_3_we0 = out_act_3_we0_local;

assign result_fu_255_p3 = ((icmp_ln29_reg_453[0:0] == 1'b1) ? trunc_ln23_reg_448 : 31'd0);

assign select_ln30_fu_371_p3 = ((or_ln30_3_fu_365_p2[0:0] == 1'b1) ? 15'd32767 : trunc_ln30_3_fu_313_p1);

assign tmp_100_fu_289_p3 = result_fu_255_p3[32'd25];

assign tmp_101_fu_317_p3 = add_ln30_fu_307_p2[32'd15];

assign tmp_fu_271_p3 = result_fu_255_p3[32'd9];

assign tmp_s_fu_325_p4 = {{result_fu_255_p3[30:26]}};

assign trunc_ln19_2_fu_221_p1 = o_fu_96[1:0];

assign trunc_ln19_fu_217_p1 = o_fu_96[6:0];

assign trunc_ln23_fu_245_p1 = grp_dense_relu_256_128_Pipeline_INNER_fu_169_acc_01_out[30:0];

assign trunc_ln30_3_fu_313_p1 = add_ln30_fu_307_p2[14:0];

assign trunc_ln30_fu_279_p1 = result_fu_255_p3[8:0];

assign trunc_ln6_fu_261_p4 = {{result_fu_255_p3[25:10]}};

assign xor_ln30_3_fu_359_p2 = (1'd1 ^ and_ln30_3_fu_353_p2);

assign xor_ln30_fu_341_p2 = (tmp_100_fu_289_p3 ^ 1'd1);

assign zext_ln19_3_fu_379_p1 = lshr_ln3_reg_443;

assign zext_ln19_fu_212_p1 = o_fu_96;

assign zext_ln30_fu_303_p1 = and_ln30_fu_297_p2;

always @ (posedge ap_clk) begin
    acc_reg_438[9:0] <= 10'b0000000000;
end

endmodule //mlp_top_dense_relu_256_128_s
