// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="mlp_top_mlp_top,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=64.035333,HLS_SYN_LAT=80287,HLS_SYN_TPT=none,HLS_SYN_MEM=363,HLS_SYN_DSP=0,HLS_SYN_FF=1509,HLS_SYN_LUT=10065,HLS_VERSION=2025_1}" *)

module mlp_top (
        ap_clk,
        ap_rst_n,
        s_axis_input_TDATA,
        s_axis_input_TVALID,
        s_axis_input_TREADY,
        s_axis_input_TKEEP,
        s_axis_input_TSTRB,
        s_axis_input_TUSER,
        s_axis_input_TLAST,
        s_axis_input_TID,
        s_axis_input_TDEST,
        m_axis_output_TDATA,
        m_axis_output_TVALID,
        m_axis_output_TREADY,
        m_axis_output_TKEEP,
        m_axis_output_TSTRB,
        m_axis_output_TUSER,
        m_axis_output_TLAST,
        m_axis_output_TID,
        m_axis_output_TDEST,
        s_axi_ctrl_AWVALID,
        s_axi_ctrl_AWREADY,
        s_axi_ctrl_AWADDR,
        s_axi_ctrl_WVALID,
        s_axi_ctrl_WREADY,
        s_axi_ctrl_WDATA,
        s_axi_ctrl_WSTRB,
        s_axi_ctrl_ARVALID,
        s_axi_ctrl_ARREADY,
        s_axi_ctrl_ARADDR,
        s_axi_ctrl_RVALID,
        s_axi_ctrl_RREADY,
        s_axi_ctrl_RDATA,
        s_axi_ctrl_RRESP,
        s_axi_ctrl_BVALID,
        s_axi_ctrl_BREADY,
        s_axi_ctrl_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [31:0] s_axis_input_TDATA;
input   s_axis_input_TVALID;
output   s_axis_input_TREADY;
input  [3:0] s_axis_input_TKEEP;
input  [3:0] s_axis_input_TSTRB;
input  [0:0] s_axis_input_TUSER;
input  [0:0] s_axis_input_TLAST;
input  [0:0] s_axis_input_TID;
input  [0:0] s_axis_input_TDEST;
output  [31:0] m_axis_output_TDATA;
output   m_axis_output_TVALID;
input   m_axis_output_TREADY;
output  [3:0] m_axis_output_TKEEP;
output  [3:0] m_axis_output_TSTRB;
output  [0:0] m_axis_output_TUSER;
output  [0:0] m_axis_output_TLAST;
output  [0:0] m_axis_output_TID;
output  [0:0] m_axis_output_TDEST;
input   s_axi_ctrl_AWVALID;
output   s_axi_ctrl_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_AWADDR;
input   s_axi_ctrl_WVALID;
output   s_axi_ctrl_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_ctrl_WSTRB;
input   s_axi_ctrl_ARVALID;
output   s_axi_ctrl_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_ctrl_ARADDR;
output   s_axi_ctrl_RVALID;
input   s_axi_ctrl_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_ctrl_RDATA;
output  [1:0] s_axi_ctrl_RRESP;
output   s_axi_ctrl_BVALID;
input   s_axi_ctrl_BREADY;
output  [1:0] s_axi_ctrl_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [6:0] act1_address0;
reg    act1_ce0;
reg    act1_we0;
wire   [14:0] act1_q0;
reg    act1_ce1;
wire   [14:0] act1_q1;
reg   [6:0] act1_1_address0;
reg    act1_1_ce0;
reg    act1_1_we0;
wire   [14:0] act1_1_q0;
reg    act1_1_ce1;
wire   [14:0] act1_1_q1;
reg   [6:0] act1_2_address0;
reg    act1_2_ce0;
reg    act1_2_we0;
wire   [14:0] act1_2_q0;
reg    act1_2_ce1;
wire   [14:0] act1_2_q1;
reg   [6:0] act1_3_address0;
reg    act1_3_ce0;
reg    act1_3_we0;
wire   [14:0] act1_3_q0;
reg    act1_3_ce1;
wire   [14:0] act1_3_q1;
reg   [5:0] act2_address0;
reg    act2_ce0;
reg    act2_we0;
wire   [14:0] act2_q0;
reg    act2_ce1;
wire   [14:0] act2_q1;
reg   [5:0] act2_1_address0;
reg    act2_1_ce0;
reg    act2_1_we0;
wire   [14:0] act2_1_q0;
reg    act2_1_ce1;
wire   [14:0] act2_1_q1;
reg   [5:0] act2_2_address0;
reg    act2_2_ce0;
reg    act2_2_we0;
wire   [14:0] act2_2_q0;
reg    act2_2_ce1;
wire   [14:0] act2_2_q1;
reg   [5:0] act2_3_address0;
reg    act2_3_ce0;
reg    act2_3_we0;
wire   [14:0] act2_3_q0;
reg    act2_3_ce1;
wire   [14:0] act2_3_q1;
reg   [4:0] act3_address0;
reg    act3_ce0;
reg    act3_we0;
wire   [14:0] act3_q0;
reg    act3_ce1;
wire   [14:0] act3_q1;
reg   [4:0] act3_1_address0;
reg    act3_1_ce0;
reg    act3_1_we0;
wire   [14:0] act3_1_q0;
reg    act3_1_ce1;
wire   [14:0] act3_1_q1;
reg   [4:0] act3_2_address0;
reg    act3_2_ce0;
reg    act3_2_we0;
wire   [14:0] act3_2_q0;
reg    act3_2_ce1;
wire   [14:0] act3_2_q1;
reg   [4:0] act3_3_address0;
reg    act3_3_ce0;
reg    act3_3_we0;
wire   [14:0] act3_3_q0;
reg    act3_3_ce1;
wire   [14:0] act3_3_q1;
reg   [3:0] act4_address0;
reg    act4_ce0;
reg    act4_we0;
wire   [15:0] act4_q0;
reg   [7:0] input_address0;
reg    input_ce0;
reg    input_we0;
wire   [15:0] input_q0;
reg    input_ce1;
wire   [15:0] input_q1;
reg   [7:0] input_1_address0;
reg    input_1_ce0;
reg    input_1_we0;
wire   [15:0] input_1_q0;
reg    input_1_ce1;
wire   [15:0] input_1_q1;
reg   [7:0] input_2_address0;
reg    input_2_ce0;
reg    input_2_we0;
wire   [15:0] input_2_q0;
reg    input_2_ce1;
wire   [15:0] input_2_q1;
reg   [7:0] input_3_address0;
reg    input_3_ce0;
reg    input_3_we0;
wire   [15:0] input_3_q0;
reg    input_3_ce1;
wire   [15:0] input_3_q1;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_done;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_idle;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_ready;
wire   [7:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_address0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_ce0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_we0;
wire   [15:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_d0;
wire   [7:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_address0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_ce0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_we0;
wire   [15:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_d0;
wire   [7:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_address0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_ce0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_we0;
wire   [15:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_d0;
wire   [7:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_address0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_ce0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_we0;
wire   [15:0] grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_d0;
wire    grp_mlp_top_Pipeline_READ_INPUT_fu_180_s_axis_input_TREADY;
wire    grp_dense_relu_784_512_s_fu_202_ap_start;
wire    grp_dense_relu_784_512_s_fu_202_ap_done;
wire    grp_dense_relu_784_512_s_fu_202_ap_idle;
wire    grp_dense_relu_784_512_s_fu_202_ap_ready;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_0_address0;
wire    grp_dense_relu_784_512_s_fu_202_in_act_0_ce0;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_0_address1;
wire    grp_dense_relu_784_512_s_fu_202_in_act_0_ce1;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_1_address0;
wire    grp_dense_relu_784_512_s_fu_202_in_act_1_ce0;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_1_address1;
wire    grp_dense_relu_784_512_s_fu_202_in_act_1_ce1;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_2_address0;
wire    grp_dense_relu_784_512_s_fu_202_in_act_2_ce0;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_2_address1;
wire    grp_dense_relu_784_512_s_fu_202_in_act_2_ce1;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_3_address0;
wire    grp_dense_relu_784_512_s_fu_202_in_act_3_ce0;
wire   [7:0] grp_dense_relu_784_512_s_fu_202_in_act_3_address1;
wire    grp_dense_relu_784_512_s_fu_202_in_act_3_ce1;
wire   [6:0] grp_dense_relu_784_512_s_fu_202_out_act_0_address0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_0_ce0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_0_we0;
wire   [14:0] grp_dense_relu_784_512_s_fu_202_out_act_0_d0;
wire   [6:0] grp_dense_relu_784_512_s_fu_202_out_act_1_address0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_1_ce0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_1_we0;
wire   [14:0] grp_dense_relu_784_512_s_fu_202_out_act_1_d0;
wire   [6:0] grp_dense_relu_784_512_s_fu_202_out_act_2_address0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_2_ce0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_2_we0;
wire   [14:0] grp_dense_relu_784_512_s_fu_202_out_act_2_d0;
wire   [6:0] grp_dense_relu_784_512_s_fu_202_out_act_3_address0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_3_ce0;
wire    grp_dense_relu_784_512_s_fu_202_out_act_3_we0;
wire   [14:0] grp_dense_relu_784_512_s_fu_202_out_act_3_d0;
wire    grp_dense_relu_512_256_s_fu_224_ap_start;
wire    grp_dense_relu_512_256_s_fu_224_ap_done;
wire    grp_dense_relu_512_256_s_fu_224_ap_idle;
wire    grp_dense_relu_512_256_s_fu_224_ap_ready;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_0_address0;
wire    grp_dense_relu_512_256_s_fu_224_in_act_0_ce0;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_0_address1;
wire    grp_dense_relu_512_256_s_fu_224_in_act_0_ce1;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_1_address0;
wire    grp_dense_relu_512_256_s_fu_224_in_act_1_ce0;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_1_address1;
wire    grp_dense_relu_512_256_s_fu_224_in_act_1_ce1;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_2_address0;
wire    grp_dense_relu_512_256_s_fu_224_in_act_2_ce0;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_2_address1;
wire    grp_dense_relu_512_256_s_fu_224_in_act_2_ce1;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_3_address0;
wire    grp_dense_relu_512_256_s_fu_224_in_act_3_ce0;
wire   [6:0] grp_dense_relu_512_256_s_fu_224_in_act_3_address1;
wire    grp_dense_relu_512_256_s_fu_224_in_act_3_ce1;
wire   [5:0] grp_dense_relu_512_256_s_fu_224_out_act_0_address0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_0_ce0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_0_we0;
wire   [14:0] grp_dense_relu_512_256_s_fu_224_out_act_0_d0;
wire   [5:0] grp_dense_relu_512_256_s_fu_224_out_act_1_address0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_1_ce0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_1_we0;
wire   [14:0] grp_dense_relu_512_256_s_fu_224_out_act_1_d0;
wire   [5:0] grp_dense_relu_512_256_s_fu_224_out_act_2_address0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_2_ce0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_2_we0;
wire   [14:0] grp_dense_relu_512_256_s_fu_224_out_act_2_d0;
wire   [5:0] grp_dense_relu_512_256_s_fu_224_out_act_3_address0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_3_ce0;
wire    grp_dense_relu_512_256_s_fu_224_out_act_3_we0;
wire   [14:0] grp_dense_relu_512_256_s_fu_224_out_act_3_d0;
wire    grp_dense_relu_256_128_s_fu_246_ap_start;
wire    grp_dense_relu_256_128_s_fu_246_ap_done;
wire    grp_dense_relu_256_128_s_fu_246_ap_idle;
wire    grp_dense_relu_256_128_s_fu_246_ap_ready;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_0_address0;
wire    grp_dense_relu_256_128_s_fu_246_in_act_0_ce0;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_0_address1;
wire    grp_dense_relu_256_128_s_fu_246_in_act_0_ce1;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_1_address0;
wire    grp_dense_relu_256_128_s_fu_246_in_act_1_ce0;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_1_address1;
wire    grp_dense_relu_256_128_s_fu_246_in_act_1_ce1;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_2_address0;
wire    grp_dense_relu_256_128_s_fu_246_in_act_2_ce0;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_2_address1;
wire    grp_dense_relu_256_128_s_fu_246_in_act_2_ce1;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_3_address0;
wire    grp_dense_relu_256_128_s_fu_246_in_act_3_ce0;
wire   [5:0] grp_dense_relu_256_128_s_fu_246_in_act_3_address1;
wire    grp_dense_relu_256_128_s_fu_246_in_act_3_ce1;
wire   [4:0] grp_dense_relu_256_128_s_fu_246_out_act_0_address0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_0_ce0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_0_we0;
wire   [14:0] grp_dense_relu_256_128_s_fu_246_out_act_0_d0;
wire   [4:0] grp_dense_relu_256_128_s_fu_246_out_act_1_address0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_1_ce0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_1_we0;
wire   [14:0] grp_dense_relu_256_128_s_fu_246_out_act_1_d0;
wire   [4:0] grp_dense_relu_256_128_s_fu_246_out_act_2_address0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_2_ce0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_2_we0;
wire   [14:0] grp_dense_relu_256_128_s_fu_246_out_act_2_d0;
wire   [4:0] grp_dense_relu_256_128_s_fu_246_out_act_3_address0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_3_ce0;
wire    grp_dense_relu_256_128_s_fu_246_out_act_3_we0;
wire   [14:0] grp_dense_relu_256_128_s_fu_246_out_act_3_d0;
wire    grp_dense_relu_128_10_s_fu_268_ap_start;
wire    grp_dense_relu_128_10_s_fu_268_ap_done;
wire    grp_dense_relu_128_10_s_fu_268_ap_idle;
wire    grp_dense_relu_128_10_s_fu_268_ap_ready;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_0_address0;
wire    grp_dense_relu_128_10_s_fu_268_in_act_0_ce0;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_0_address1;
wire    grp_dense_relu_128_10_s_fu_268_in_act_0_ce1;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_1_address0;
wire    grp_dense_relu_128_10_s_fu_268_in_act_1_ce0;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_1_address1;
wire    grp_dense_relu_128_10_s_fu_268_in_act_1_ce1;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_2_address0;
wire    grp_dense_relu_128_10_s_fu_268_in_act_2_ce0;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_2_address1;
wire    grp_dense_relu_128_10_s_fu_268_in_act_2_ce1;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_3_address0;
wire    grp_dense_relu_128_10_s_fu_268_in_act_3_ce0;
wire   [4:0] grp_dense_relu_128_10_s_fu_268_in_act_3_address1;
wire    grp_dense_relu_128_10_s_fu_268_in_act_3_ce1;
wire   [3:0] grp_dense_relu_128_10_s_fu_268_out_act_address0;
wire    grp_dense_relu_128_10_s_fu_268_out_act_ce0;
wire    grp_dense_relu_128_10_s_fu_268_out_act_we0;
wire   [15:0] grp_dense_relu_128_10_s_fu_268_out_act_d0;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_done;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_idle;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_ready;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TREADY;
wire   [3:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_act4_address0;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_act4_ce0;
wire   [31:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDATA;
wire    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID;
wire   [3:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TKEEP;
wire   [3:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TSTRB;
wire   [0:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TUSER;
wire   [0:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TLAST;
wire   [0:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TID;
wire   [0:0] grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDEST;
reg    grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_dense_relu_784_512_s_fu_202_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_dense_relu_512_256_s_fu_224_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_dense_relu_256_128_s_fu_246_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_dense_relu_128_10_s_fu_268_ap_start_reg;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start_reg;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
reg   [31:0] m_axis_output_TDATA_reg;
reg   [3:0] m_axis_output_TKEEP_reg;
reg   [3:0] m_axis_output_TSTRB_reg;
reg   [0:0] m_axis_output_TUSER_reg;
reg   [0:0] m_axis_output_TLAST_reg;
reg   [0:0] m_axis_output_TID_reg;
reg   [0:0] m_axis_output_TDEST_reg;
wire    ap_CS_fsm_state14;
wire    regslice_both_m_axis_output_V_data_V_U_apdone_blk;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    regslice_both_s_axis_input_V_data_V_U_apdone_blk;
wire   [31:0] s_axis_input_TDATA_int_regslice;
wire    s_axis_input_TVALID_int_regslice;
reg    s_axis_input_TREADY_int_regslice;
wire    regslice_both_s_axis_input_V_data_V_U_ack_in;
wire    regslice_both_s_axis_input_V_keep_V_U_apdone_blk;
wire   [3:0] s_axis_input_TKEEP_int_regslice;
wire    regslice_both_s_axis_input_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_input_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_input_V_strb_V_U_apdone_blk;
wire   [3:0] s_axis_input_TSTRB_int_regslice;
wire    regslice_both_s_axis_input_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_input_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_input_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_input_TUSER_int_regslice;
wire    regslice_both_s_axis_input_V_user_V_U_vld_out;
wire    regslice_both_s_axis_input_V_user_V_U_ack_in;
wire    regslice_both_s_axis_input_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_input_TLAST_int_regslice;
wire    regslice_both_s_axis_input_V_last_V_U_vld_out;
wire    regslice_both_s_axis_input_V_last_V_U_ack_in;
wire    regslice_both_s_axis_input_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_input_TID_int_regslice;
wire    regslice_both_s_axis_input_V_id_V_U_vld_out;
wire    regslice_both_s_axis_input_V_id_V_U_ack_in;
wire    regslice_both_s_axis_input_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_input_TDEST_int_regslice;
wire    regslice_both_s_axis_input_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_input_V_dest_V_U_ack_in;
reg   [31:0] m_axis_output_TDATA_int_regslice;
wire    m_axis_output_TVALID_int_regslice;
wire    m_axis_output_TREADY_int_regslice;
wire    regslice_both_m_axis_output_V_data_V_U_vld_out;
wire    regslice_both_m_axis_output_V_keep_V_U_apdone_blk;
reg   [3:0] m_axis_output_TKEEP_int_regslice;
wire    regslice_both_m_axis_output_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_output_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_output_V_strb_V_U_apdone_blk;
reg   [3:0] m_axis_output_TSTRB_int_regslice;
wire    regslice_both_m_axis_output_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_output_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_output_V_user_V_U_apdone_blk;
reg   [0:0] m_axis_output_TUSER_int_regslice;
wire    regslice_both_m_axis_output_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_output_V_user_V_U_vld_out;
wire    regslice_both_m_axis_output_V_last_V_U_apdone_blk;
reg   [0:0] m_axis_output_TLAST_int_regslice;
wire    regslice_both_m_axis_output_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_output_V_last_V_U_vld_out;
wire    regslice_both_m_axis_output_V_id_V_U_apdone_blk;
reg   [0:0] m_axis_output_TID_int_regslice;
wire    regslice_both_m_axis_output_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_output_V_id_V_U_vld_out;
wire    regslice_both_m_axis_output_V_dest_V_U_apdone_blk;
reg   [0:0] m_axis_output_TDEST_int_regslice;
wire    regslice_both_m_axis_output_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_output_V_dest_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start_reg = 1'b0;
#0 grp_dense_relu_784_512_s_fu_202_ap_start_reg = 1'b0;
#0 grp_dense_relu_512_256_s_fu_224_ap_start_reg = 1'b0;
#0 grp_dense_relu_256_128_s_fu_246_ap_start_reg = 1'b0;
#0 grp_dense_relu_128_10_s_fu_268_ap_start_reg = 1'b0;
#0 grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start_reg = 1'b0;
end

mlp_top_act1_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
act1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act1_address0),
    .ce0(act1_ce0),
    .we0(act1_we0),
    .d0(grp_dense_relu_784_512_s_fu_202_out_act_0_d0),
    .q0(act1_q0),
    .address1(grp_dense_relu_512_256_s_fu_224_in_act_0_address1),
    .ce1(act1_ce1),
    .q1(act1_q1)
);

mlp_top_act1_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
act1_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act1_1_address0),
    .ce0(act1_1_ce0),
    .we0(act1_1_we0),
    .d0(grp_dense_relu_784_512_s_fu_202_out_act_1_d0),
    .q0(act1_1_q0),
    .address1(grp_dense_relu_512_256_s_fu_224_in_act_1_address1),
    .ce1(act1_1_ce1),
    .q1(act1_1_q1)
);

mlp_top_act1_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
act1_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act1_2_address0),
    .ce0(act1_2_ce0),
    .we0(act1_2_we0),
    .d0(grp_dense_relu_784_512_s_fu_202_out_act_2_d0),
    .q0(act1_2_q0),
    .address1(grp_dense_relu_512_256_s_fu_224_in_act_2_address1),
    .ce1(act1_2_ce1),
    .q1(act1_2_q1)
);

mlp_top_act1_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
act1_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act1_3_address0),
    .ce0(act1_3_ce0),
    .we0(act1_3_we0),
    .d0(grp_dense_relu_784_512_s_fu_202_out_act_3_d0),
    .q0(act1_3_q0),
    .address1(grp_dense_relu_512_256_s_fu_224_in_act_3_address1),
    .ce1(act1_3_ce1),
    .q1(act1_3_q1)
);

mlp_top_act2_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
act2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act2_address0),
    .ce0(act2_ce0),
    .we0(act2_we0),
    .d0(grp_dense_relu_512_256_s_fu_224_out_act_0_d0),
    .q0(act2_q0),
    .address1(grp_dense_relu_256_128_s_fu_246_in_act_0_address1),
    .ce1(act2_ce1),
    .q1(act2_q1)
);

mlp_top_act2_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
act2_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act2_1_address0),
    .ce0(act2_1_ce0),
    .we0(act2_1_we0),
    .d0(grp_dense_relu_512_256_s_fu_224_out_act_1_d0),
    .q0(act2_1_q0),
    .address1(grp_dense_relu_256_128_s_fu_246_in_act_1_address1),
    .ce1(act2_1_ce1),
    .q1(act2_1_q1)
);

mlp_top_act2_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
act2_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act2_2_address0),
    .ce0(act2_2_ce0),
    .we0(act2_2_we0),
    .d0(grp_dense_relu_512_256_s_fu_224_out_act_2_d0),
    .q0(act2_2_q0),
    .address1(grp_dense_relu_256_128_s_fu_246_in_act_2_address1),
    .ce1(act2_2_ce1),
    .q1(act2_2_q1)
);

mlp_top_act2_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
act2_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act2_3_address0),
    .ce0(act2_3_ce0),
    .we0(act2_3_we0),
    .d0(grp_dense_relu_512_256_s_fu_224_out_act_3_d0),
    .q0(act2_3_q0),
    .address1(grp_dense_relu_256_128_s_fu_246_in_act_3_address1),
    .ce1(act2_3_ce1),
    .q1(act2_3_q1)
);

mlp_top_act3_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
act3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act3_address0),
    .ce0(act3_ce0),
    .we0(act3_we0),
    .d0(grp_dense_relu_256_128_s_fu_246_out_act_0_d0),
    .q0(act3_q0),
    .address1(grp_dense_relu_128_10_s_fu_268_in_act_0_address1),
    .ce1(act3_ce1),
    .q1(act3_q1)
);

mlp_top_act3_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
act3_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act3_1_address0),
    .ce0(act3_1_ce0),
    .we0(act3_1_we0),
    .d0(grp_dense_relu_256_128_s_fu_246_out_act_1_d0),
    .q0(act3_1_q0),
    .address1(grp_dense_relu_128_10_s_fu_268_in_act_1_address1),
    .ce1(act3_1_ce1),
    .q1(act3_1_q1)
);

mlp_top_act3_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
act3_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act3_2_address0),
    .ce0(act3_2_ce0),
    .we0(act3_2_we0),
    .d0(grp_dense_relu_256_128_s_fu_246_out_act_2_d0),
    .q0(act3_2_q0),
    .address1(grp_dense_relu_128_10_s_fu_268_in_act_2_address1),
    .ce1(act3_2_ce1),
    .q1(act3_2_q1)
);

mlp_top_act3_RAM_AUTO_1R1W #(
    .DataWidth( 15 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
act3_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act3_3_address0),
    .ce0(act3_3_ce0),
    .we0(act3_3_we0),
    .d0(grp_dense_relu_256_128_s_fu_246_out_act_3_d0),
    .q0(act3_3_q0),
    .address1(grp_dense_relu_128_10_s_fu_268_in_act_3_address1),
    .ce1(act3_3_ce1),
    .q1(act3_3_q1)
);

mlp_top_act4_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 10 ),
    .AddressWidth( 4 ))
act4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(act4_address0),
    .ce0(act4_ce0),
    .we0(act4_we0),
    .d0(grp_dense_relu_128_10_s_fu_268_out_act_d0),
    .q0(act4_q0)
);

mlp_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 196 ),
    .AddressWidth( 8 ))
input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_address0),
    .ce0(input_ce0),
    .we0(input_we0),
    .d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_d0),
    .q0(input_q0),
    .address1(grp_dense_relu_784_512_s_fu_202_in_act_0_address1),
    .ce1(input_ce1),
    .q1(input_q1)
);

mlp_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 196 ),
    .AddressWidth( 8 ))
input_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_1_address0),
    .ce0(input_1_ce0),
    .we0(input_1_we0),
    .d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_d0),
    .q0(input_1_q0),
    .address1(grp_dense_relu_784_512_s_fu_202_in_act_1_address1),
    .ce1(input_1_ce1),
    .q1(input_1_q1)
);

mlp_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 196 ),
    .AddressWidth( 8 ))
input_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_2_address0),
    .ce0(input_2_ce0),
    .we0(input_2_we0),
    .d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_d0),
    .q0(input_2_q0),
    .address1(grp_dense_relu_784_512_s_fu_202_in_act_2_address1),
    .ce1(input_2_ce1),
    .q1(input_2_q1)
);

mlp_top_input_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 196 ),
    .AddressWidth( 8 ))
input_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(input_3_address0),
    .ce0(input_3_ce0),
    .we0(input_3_we0),
    .d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_d0),
    .q0(input_3_q0),
    .address1(grp_dense_relu_784_512_s_fu_202_in_act_3_address1),
    .ce1(input_3_ce1),
    .q1(input_3_q1)
);

mlp_top_mlp_top_Pipeline_READ_INPUT grp_mlp_top_Pipeline_READ_INPUT_fu_180(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start),
    .ap_done(grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_done),
    .ap_idle(grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_idle),
    .ap_ready(grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_ready),
    .s_axis_input_TVALID(s_axis_input_TVALID_int_regslice),
    .input_3_address0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_address0),
    .input_3_ce0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_ce0),
    .input_3_we0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_we0),
    .input_3_d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_d0),
    .input_2_address0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_address0),
    .input_2_ce0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_ce0),
    .input_2_we0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_we0),
    .input_2_d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_d0),
    .input_1_address0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_address0),
    .input_1_ce0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_ce0),
    .input_1_we0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_we0),
    .input_1_d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_d0),
    .input_r_address0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_address0),
    .input_r_ce0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_ce0),
    .input_r_we0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_we0),
    .input_r_d0(grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_d0),
    .s_axis_input_TDATA(s_axis_input_TDATA_int_regslice),
    .s_axis_input_TREADY(grp_mlp_top_Pipeline_READ_INPUT_fu_180_s_axis_input_TREADY),
    .s_axis_input_TKEEP(s_axis_input_TKEEP_int_regslice),
    .s_axis_input_TSTRB(s_axis_input_TSTRB_int_regslice),
    .s_axis_input_TUSER(s_axis_input_TUSER_int_regslice),
    .s_axis_input_TLAST(s_axis_input_TLAST_int_regslice),
    .s_axis_input_TID(s_axis_input_TID_int_regslice),
    .s_axis_input_TDEST(s_axis_input_TDEST_int_regslice)
);

mlp_top_dense_relu_784_512_s grp_dense_relu_784_512_s_fu_202(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dense_relu_784_512_s_fu_202_ap_start),
    .ap_done(grp_dense_relu_784_512_s_fu_202_ap_done),
    .ap_idle(grp_dense_relu_784_512_s_fu_202_ap_idle),
    .ap_ready(grp_dense_relu_784_512_s_fu_202_ap_ready),
    .in_act_0_address0(grp_dense_relu_784_512_s_fu_202_in_act_0_address0),
    .in_act_0_ce0(grp_dense_relu_784_512_s_fu_202_in_act_0_ce0),
    .in_act_0_q0(input_q0),
    .in_act_0_address1(grp_dense_relu_784_512_s_fu_202_in_act_0_address1),
    .in_act_0_ce1(grp_dense_relu_784_512_s_fu_202_in_act_0_ce1),
    .in_act_0_q1(input_q1),
    .in_act_1_address0(grp_dense_relu_784_512_s_fu_202_in_act_1_address0),
    .in_act_1_ce0(grp_dense_relu_784_512_s_fu_202_in_act_1_ce0),
    .in_act_1_q0(input_1_q0),
    .in_act_1_address1(grp_dense_relu_784_512_s_fu_202_in_act_1_address1),
    .in_act_1_ce1(grp_dense_relu_784_512_s_fu_202_in_act_1_ce1),
    .in_act_1_q1(input_1_q1),
    .in_act_2_address0(grp_dense_relu_784_512_s_fu_202_in_act_2_address0),
    .in_act_2_ce0(grp_dense_relu_784_512_s_fu_202_in_act_2_ce0),
    .in_act_2_q0(input_2_q0),
    .in_act_2_address1(grp_dense_relu_784_512_s_fu_202_in_act_2_address1),
    .in_act_2_ce1(grp_dense_relu_784_512_s_fu_202_in_act_2_ce1),
    .in_act_2_q1(input_2_q1),
    .in_act_3_address0(grp_dense_relu_784_512_s_fu_202_in_act_3_address0),
    .in_act_3_ce0(grp_dense_relu_784_512_s_fu_202_in_act_3_ce0),
    .in_act_3_q0(input_3_q0),
    .in_act_3_address1(grp_dense_relu_784_512_s_fu_202_in_act_3_address1),
    .in_act_3_ce1(grp_dense_relu_784_512_s_fu_202_in_act_3_ce1),
    .in_act_3_q1(input_3_q1),
    .out_act_0_address0(grp_dense_relu_784_512_s_fu_202_out_act_0_address0),
    .out_act_0_ce0(grp_dense_relu_784_512_s_fu_202_out_act_0_ce0),
    .out_act_0_we0(grp_dense_relu_784_512_s_fu_202_out_act_0_we0),
    .out_act_0_d0(grp_dense_relu_784_512_s_fu_202_out_act_0_d0),
    .out_act_1_address0(grp_dense_relu_784_512_s_fu_202_out_act_1_address0),
    .out_act_1_ce0(grp_dense_relu_784_512_s_fu_202_out_act_1_ce0),
    .out_act_1_we0(grp_dense_relu_784_512_s_fu_202_out_act_1_we0),
    .out_act_1_d0(grp_dense_relu_784_512_s_fu_202_out_act_1_d0),
    .out_act_2_address0(grp_dense_relu_784_512_s_fu_202_out_act_2_address0),
    .out_act_2_ce0(grp_dense_relu_784_512_s_fu_202_out_act_2_ce0),
    .out_act_2_we0(grp_dense_relu_784_512_s_fu_202_out_act_2_we0),
    .out_act_2_d0(grp_dense_relu_784_512_s_fu_202_out_act_2_d0),
    .out_act_3_address0(grp_dense_relu_784_512_s_fu_202_out_act_3_address0),
    .out_act_3_ce0(grp_dense_relu_784_512_s_fu_202_out_act_3_ce0),
    .out_act_3_we0(grp_dense_relu_784_512_s_fu_202_out_act_3_we0),
    .out_act_3_d0(grp_dense_relu_784_512_s_fu_202_out_act_3_d0)
);

mlp_top_dense_relu_512_256_s grp_dense_relu_512_256_s_fu_224(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dense_relu_512_256_s_fu_224_ap_start),
    .ap_done(grp_dense_relu_512_256_s_fu_224_ap_done),
    .ap_idle(grp_dense_relu_512_256_s_fu_224_ap_idle),
    .ap_ready(grp_dense_relu_512_256_s_fu_224_ap_ready),
    .in_act_0_address0(grp_dense_relu_512_256_s_fu_224_in_act_0_address0),
    .in_act_0_ce0(grp_dense_relu_512_256_s_fu_224_in_act_0_ce0),
    .in_act_0_q0(act1_q0),
    .in_act_0_address1(grp_dense_relu_512_256_s_fu_224_in_act_0_address1),
    .in_act_0_ce1(grp_dense_relu_512_256_s_fu_224_in_act_0_ce1),
    .in_act_0_q1(act1_q1),
    .in_act_1_address0(grp_dense_relu_512_256_s_fu_224_in_act_1_address0),
    .in_act_1_ce0(grp_dense_relu_512_256_s_fu_224_in_act_1_ce0),
    .in_act_1_q0(act1_1_q0),
    .in_act_1_address1(grp_dense_relu_512_256_s_fu_224_in_act_1_address1),
    .in_act_1_ce1(grp_dense_relu_512_256_s_fu_224_in_act_1_ce1),
    .in_act_1_q1(act1_1_q1),
    .in_act_2_address0(grp_dense_relu_512_256_s_fu_224_in_act_2_address0),
    .in_act_2_ce0(grp_dense_relu_512_256_s_fu_224_in_act_2_ce0),
    .in_act_2_q0(act1_2_q0),
    .in_act_2_address1(grp_dense_relu_512_256_s_fu_224_in_act_2_address1),
    .in_act_2_ce1(grp_dense_relu_512_256_s_fu_224_in_act_2_ce1),
    .in_act_2_q1(act1_2_q1),
    .in_act_3_address0(grp_dense_relu_512_256_s_fu_224_in_act_3_address0),
    .in_act_3_ce0(grp_dense_relu_512_256_s_fu_224_in_act_3_ce0),
    .in_act_3_q0(act1_3_q0),
    .in_act_3_address1(grp_dense_relu_512_256_s_fu_224_in_act_3_address1),
    .in_act_3_ce1(grp_dense_relu_512_256_s_fu_224_in_act_3_ce1),
    .in_act_3_q1(act1_3_q1),
    .out_act_0_address0(grp_dense_relu_512_256_s_fu_224_out_act_0_address0),
    .out_act_0_ce0(grp_dense_relu_512_256_s_fu_224_out_act_0_ce0),
    .out_act_0_we0(grp_dense_relu_512_256_s_fu_224_out_act_0_we0),
    .out_act_0_d0(grp_dense_relu_512_256_s_fu_224_out_act_0_d0),
    .out_act_1_address0(grp_dense_relu_512_256_s_fu_224_out_act_1_address0),
    .out_act_1_ce0(grp_dense_relu_512_256_s_fu_224_out_act_1_ce0),
    .out_act_1_we0(grp_dense_relu_512_256_s_fu_224_out_act_1_we0),
    .out_act_1_d0(grp_dense_relu_512_256_s_fu_224_out_act_1_d0),
    .out_act_2_address0(grp_dense_relu_512_256_s_fu_224_out_act_2_address0),
    .out_act_2_ce0(grp_dense_relu_512_256_s_fu_224_out_act_2_ce0),
    .out_act_2_we0(grp_dense_relu_512_256_s_fu_224_out_act_2_we0),
    .out_act_2_d0(grp_dense_relu_512_256_s_fu_224_out_act_2_d0),
    .out_act_3_address0(grp_dense_relu_512_256_s_fu_224_out_act_3_address0),
    .out_act_3_ce0(grp_dense_relu_512_256_s_fu_224_out_act_3_ce0),
    .out_act_3_we0(grp_dense_relu_512_256_s_fu_224_out_act_3_we0),
    .out_act_3_d0(grp_dense_relu_512_256_s_fu_224_out_act_3_d0)
);

mlp_top_dense_relu_256_128_s grp_dense_relu_256_128_s_fu_246(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dense_relu_256_128_s_fu_246_ap_start),
    .ap_done(grp_dense_relu_256_128_s_fu_246_ap_done),
    .ap_idle(grp_dense_relu_256_128_s_fu_246_ap_idle),
    .ap_ready(grp_dense_relu_256_128_s_fu_246_ap_ready),
    .in_act_0_address0(grp_dense_relu_256_128_s_fu_246_in_act_0_address0),
    .in_act_0_ce0(grp_dense_relu_256_128_s_fu_246_in_act_0_ce0),
    .in_act_0_q0(act2_q0),
    .in_act_0_address1(grp_dense_relu_256_128_s_fu_246_in_act_0_address1),
    .in_act_0_ce1(grp_dense_relu_256_128_s_fu_246_in_act_0_ce1),
    .in_act_0_q1(act2_q1),
    .in_act_1_address0(grp_dense_relu_256_128_s_fu_246_in_act_1_address0),
    .in_act_1_ce0(grp_dense_relu_256_128_s_fu_246_in_act_1_ce0),
    .in_act_1_q0(act2_1_q0),
    .in_act_1_address1(grp_dense_relu_256_128_s_fu_246_in_act_1_address1),
    .in_act_1_ce1(grp_dense_relu_256_128_s_fu_246_in_act_1_ce1),
    .in_act_1_q1(act2_1_q1),
    .in_act_2_address0(grp_dense_relu_256_128_s_fu_246_in_act_2_address0),
    .in_act_2_ce0(grp_dense_relu_256_128_s_fu_246_in_act_2_ce0),
    .in_act_2_q0(act2_2_q0),
    .in_act_2_address1(grp_dense_relu_256_128_s_fu_246_in_act_2_address1),
    .in_act_2_ce1(grp_dense_relu_256_128_s_fu_246_in_act_2_ce1),
    .in_act_2_q1(act2_2_q1),
    .in_act_3_address0(grp_dense_relu_256_128_s_fu_246_in_act_3_address0),
    .in_act_3_ce0(grp_dense_relu_256_128_s_fu_246_in_act_3_ce0),
    .in_act_3_q0(act2_3_q0),
    .in_act_3_address1(grp_dense_relu_256_128_s_fu_246_in_act_3_address1),
    .in_act_3_ce1(grp_dense_relu_256_128_s_fu_246_in_act_3_ce1),
    .in_act_3_q1(act2_3_q1),
    .out_act_0_address0(grp_dense_relu_256_128_s_fu_246_out_act_0_address0),
    .out_act_0_ce0(grp_dense_relu_256_128_s_fu_246_out_act_0_ce0),
    .out_act_0_we0(grp_dense_relu_256_128_s_fu_246_out_act_0_we0),
    .out_act_0_d0(grp_dense_relu_256_128_s_fu_246_out_act_0_d0),
    .out_act_1_address0(grp_dense_relu_256_128_s_fu_246_out_act_1_address0),
    .out_act_1_ce0(grp_dense_relu_256_128_s_fu_246_out_act_1_ce0),
    .out_act_1_we0(grp_dense_relu_256_128_s_fu_246_out_act_1_we0),
    .out_act_1_d0(grp_dense_relu_256_128_s_fu_246_out_act_1_d0),
    .out_act_2_address0(grp_dense_relu_256_128_s_fu_246_out_act_2_address0),
    .out_act_2_ce0(grp_dense_relu_256_128_s_fu_246_out_act_2_ce0),
    .out_act_2_we0(grp_dense_relu_256_128_s_fu_246_out_act_2_we0),
    .out_act_2_d0(grp_dense_relu_256_128_s_fu_246_out_act_2_d0),
    .out_act_3_address0(grp_dense_relu_256_128_s_fu_246_out_act_3_address0),
    .out_act_3_ce0(grp_dense_relu_256_128_s_fu_246_out_act_3_ce0),
    .out_act_3_we0(grp_dense_relu_256_128_s_fu_246_out_act_3_we0),
    .out_act_3_d0(grp_dense_relu_256_128_s_fu_246_out_act_3_d0)
);

mlp_top_dense_relu_128_10_s grp_dense_relu_128_10_s_fu_268(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_dense_relu_128_10_s_fu_268_ap_start),
    .ap_done(grp_dense_relu_128_10_s_fu_268_ap_done),
    .ap_idle(grp_dense_relu_128_10_s_fu_268_ap_idle),
    .ap_ready(grp_dense_relu_128_10_s_fu_268_ap_ready),
    .in_act_0_address0(grp_dense_relu_128_10_s_fu_268_in_act_0_address0),
    .in_act_0_ce0(grp_dense_relu_128_10_s_fu_268_in_act_0_ce0),
    .in_act_0_q0(act3_q0),
    .in_act_0_address1(grp_dense_relu_128_10_s_fu_268_in_act_0_address1),
    .in_act_0_ce1(grp_dense_relu_128_10_s_fu_268_in_act_0_ce1),
    .in_act_0_q1(act3_q1),
    .in_act_1_address0(grp_dense_relu_128_10_s_fu_268_in_act_1_address0),
    .in_act_1_ce0(grp_dense_relu_128_10_s_fu_268_in_act_1_ce0),
    .in_act_1_q0(act3_1_q0),
    .in_act_1_address1(grp_dense_relu_128_10_s_fu_268_in_act_1_address1),
    .in_act_1_ce1(grp_dense_relu_128_10_s_fu_268_in_act_1_ce1),
    .in_act_1_q1(act3_1_q1),
    .in_act_2_address0(grp_dense_relu_128_10_s_fu_268_in_act_2_address0),
    .in_act_2_ce0(grp_dense_relu_128_10_s_fu_268_in_act_2_ce0),
    .in_act_2_q0(act3_2_q0),
    .in_act_2_address1(grp_dense_relu_128_10_s_fu_268_in_act_2_address1),
    .in_act_2_ce1(grp_dense_relu_128_10_s_fu_268_in_act_2_ce1),
    .in_act_2_q1(act3_2_q1),
    .in_act_3_address0(grp_dense_relu_128_10_s_fu_268_in_act_3_address0),
    .in_act_3_ce0(grp_dense_relu_128_10_s_fu_268_in_act_3_ce0),
    .in_act_3_q0(act3_3_q0),
    .in_act_3_address1(grp_dense_relu_128_10_s_fu_268_in_act_3_address1),
    .in_act_3_ce1(grp_dense_relu_128_10_s_fu_268_in_act_3_ce1),
    .in_act_3_q1(act3_3_q1),
    .out_act_address0(grp_dense_relu_128_10_s_fu_268_out_act_address0),
    .out_act_ce0(grp_dense_relu_128_10_s_fu_268_out_act_ce0),
    .out_act_we0(grp_dense_relu_128_10_s_fu_268_out_act_we0),
    .out_act_d0(grp_dense_relu_128_10_s_fu_268_out_act_d0)
);

mlp_top_mlp_top_Pipeline_WRITE_OUTPUT grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start),
    .ap_done(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_done),
    .ap_idle(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_idle),
    .ap_ready(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_ready),
    .m_axis_output_TREADY(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TREADY),
    .act4_address0(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_act4_address0),
    .act4_ce0(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_act4_ce0),
    .act4_q0(act4_q0),
    .m_axis_output_TDATA(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDATA),
    .m_axis_output_TVALID(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .m_axis_output_TKEEP(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TKEEP),
    .m_axis_output_TSTRB(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TSTRB),
    .m_axis_output_TUSER(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TUSER),
    .m_axis_output_TLAST(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TLAST),
    .m_axis_output_TID(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TID),
    .m_axis_output_TDEST(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDEST)
);

mlp_top_ctrl_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
ctrl_s_axi_U(
    .AWVALID(s_axi_ctrl_AWVALID),
    .AWREADY(s_axi_ctrl_AWREADY),
    .AWADDR(s_axi_ctrl_AWADDR),
    .WVALID(s_axi_ctrl_WVALID),
    .WREADY(s_axi_ctrl_WREADY),
    .WDATA(s_axi_ctrl_WDATA),
    .WSTRB(s_axi_ctrl_WSTRB),
    .ARVALID(s_axi_ctrl_ARVALID),
    .ARREADY(s_axi_ctrl_ARREADY),
    .ARADDR(s_axi_ctrl_ARADDR),
    .RVALID(s_axi_ctrl_RVALID),
    .RREADY(s_axi_ctrl_RREADY),
    .RDATA(s_axi_ctrl_RDATA),
    .RRESP(s_axi_ctrl_RRESP),
    .BVALID(s_axi_ctrl_BVALID),
    .BREADY(s_axi_ctrl_BREADY),
    .BRESP(s_axi_ctrl_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

mlp_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_axis_input_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TDATA),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_data_V_U_ack_in),
    .data_out(s_axis_input_TDATA_int_regslice),
    .vld_out(s_axis_input_TVALID_int_regslice),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_data_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_input_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TKEEP),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_keep_V_U_ack_in),
    .data_out(s_axis_input_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_input_V_keep_V_U_vld_out),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_keep_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_axis_input_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TSTRB),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_strb_V_U_ack_in),
    .data_out(s_axis_input_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_input_V_strb_V_U_vld_out),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_strb_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_input_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TUSER),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_user_V_U_ack_in),
    .data_out(s_axis_input_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_input_V_user_V_U_vld_out),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_user_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_input_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TLAST),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_last_V_U_ack_in),
    .data_out(s_axis_input_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_input_V_last_V_U_vld_out),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_last_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_input_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TID),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_id_V_U_ack_in),
    .data_out(s_axis_input_TID_int_regslice),
    .vld_out(regslice_both_s_axis_input_V_id_V_U_vld_out),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_id_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_input_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_input_TDEST),
    .vld_in(s_axis_input_TVALID),
    .ack_in(regslice_both_s_axis_input_V_dest_V_U_ack_in),
    .data_out(s_axis_input_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_input_V_dest_V_U_vld_out),
    .ack_out(s_axis_input_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_input_V_dest_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 32 ))
regslice_both_m_axis_output_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TDATA_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(m_axis_output_TREADY_int_regslice),
    .data_out(m_axis_output_TDATA),
    .vld_out(regslice_both_m_axis_output_V_data_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_data_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_output_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TKEEP_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(regslice_both_m_axis_output_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_output_TKEEP),
    .vld_out(regslice_both_m_axis_output_V_keep_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_keep_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 4 ))
regslice_both_m_axis_output_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TSTRB_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(regslice_both_m_axis_output_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_output_TSTRB),
    .vld_out(regslice_both_m_axis_output_V_strb_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_strb_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_output_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TUSER_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(regslice_both_m_axis_output_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_output_TUSER),
    .vld_out(regslice_both_m_axis_output_V_user_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_user_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_output_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TLAST_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(regslice_both_m_axis_output_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_output_TLAST),
    .vld_out(regslice_both_m_axis_output_V_last_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_last_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_output_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TID_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(regslice_both_m_axis_output_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_output_TID),
    .vld_out(regslice_both_m_axis_output_V_id_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_id_V_U_apdone_blk)
);

mlp_top_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_output_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_output_TDEST_int_regslice),
    .vld_in(grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID),
    .ack_in(regslice_both_m_axis_output_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_output_TDEST),
    .vld_out(regslice_both_m_axis_output_V_dest_V_U_vld_out),
    .ack_out(m_axis_output_TREADY),
    .apdone_blk(regslice_both_m_axis_output_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dense_relu_128_10_s_fu_268_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_dense_relu_128_10_s_fu_268_ap_start_reg <= 1'b1;
        end else if ((grp_dense_relu_128_10_s_fu_268_ap_ready == 1'b1)) begin
            grp_dense_relu_128_10_s_fu_268_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dense_relu_256_128_s_fu_246_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_dense_relu_256_128_s_fu_246_ap_start_reg <= 1'b1;
        end else if ((grp_dense_relu_256_128_s_fu_246_ap_ready == 1'b1)) begin
            grp_dense_relu_256_128_s_fu_246_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dense_relu_512_256_s_fu_224_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_dense_relu_512_256_s_fu_224_ap_start_reg <= 1'b1;
        end else if ((grp_dense_relu_512_256_s_fu_224_ap_ready == 1'b1)) begin
            grp_dense_relu_512_256_s_fu_224_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_dense_relu_784_512_s_fu_202_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dense_relu_784_512_s_fu_202_ap_start_reg <= 1'b1;
        end else if ((grp_dense_relu_784_512_s_fu_202_ap_ready == 1'b1)) begin
            grp_dense_relu_784_512_s_fu_202_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_ready == 1'b1)) begin
            grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state12)) begin
            grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start_reg <= 1'b1;
        end else if ((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_ready == 1'b1)) begin
            grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TDATA_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDATA;
        m_axis_output_TDEST_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDEST;
        m_axis_output_TID_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TID;
        m_axis_output_TKEEP_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TKEEP;
        m_axis_output_TLAST_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TLAST;
        m_axis_output_TSTRB_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TSTRB;
        m_axis_output_TUSER_reg <= grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TUSER;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_1_address0 = grp_dense_relu_512_256_s_fu_224_in_act_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_1_address0 = grp_dense_relu_784_512_s_fu_202_out_act_1_address0;
    end else begin
        act1_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_1_ce0 = grp_dense_relu_512_256_s_fu_224_in_act_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_1_ce0 = grp_dense_relu_784_512_s_fu_202_out_act_1_ce0;
    end else begin
        act1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_1_ce1 = grp_dense_relu_512_256_s_fu_224_in_act_1_ce1;
    end else begin
        act1_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_1_we0 = grp_dense_relu_784_512_s_fu_202_out_act_1_we0;
    end else begin
        act1_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_2_address0 = grp_dense_relu_512_256_s_fu_224_in_act_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_2_address0 = grp_dense_relu_784_512_s_fu_202_out_act_2_address0;
    end else begin
        act1_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_2_ce0 = grp_dense_relu_512_256_s_fu_224_in_act_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_2_ce0 = grp_dense_relu_784_512_s_fu_202_out_act_2_ce0;
    end else begin
        act1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_2_ce1 = grp_dense_relu_512_256_s_fu_224_in_act_2_ce1;
    end else begin
        act1_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_2_we0 = grp_dense_relu_784_512_s_fu_202_out_act_2_we0;
    end else begin
        act1_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_3_address0 = grp_dense_relu_512_256_s_fu_224_in_act_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_3_address0 = grp_dense_relu_784_512_s_fu_202_out_act_3_address0;
    end else begin
        act1_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_3_ce0 = grp_dense_relu_512_256_s_fu_224_in_act_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_3_ce0 = grp_dense_relu_784_512_s_fu_202_out_act_3_ce0;
    end else begin
        act1_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_3_ce1 = grp_dense_relu_512_256_s_fu_224_in_act_3_ce1;
    end else begin
        act1_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_3_we0 = grp_dense_relu_784_512_s_fu_202_out_act_3_we0;
    end else begin
        act1_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_address0 = grp_dense_relu_512_256_s_fu_224_in_act_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_address0 = grp_dense_relu_784_512_s_fu_202_out_act_0_address0;
    end else begin
        act1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_ce0 = grp_dense_relu_512_256_s_fu_224_in_act_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_ce0 = grp_dense_relu_784_512_s_fu_202_out_act_0_ce0;
    end else begin
        act1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act1_ce1 = grp_dense_relu_512_256_s_fu_224_in_act_0_ce1;
    end else begin
        act1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        act1_we0 = grp_dense_relu_784_512_s_fu_202_out_act_0_we0;
    end else begin
        act1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_1_address0 = grp_dense_relu_256_128_s_fu_246_in_act_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_1_address0 = grp_dense_relu_512_256_s_fu_224_out_act_1_address0;
    end else begin
        act2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_1_ce0 = grp_dense_relu_256_128_s_fu_246_in_act_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_1_ce0 = grp_dense_relu_512_256_s_fu_224_out_act_1_ce0;
    end else begin
        act2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_1_ce1 = grp_dense_relu_256_128_s_fu_246_in_act_1_ce1;
    end else begin
        act2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_1_we0 = grp_dense_relu_512_256_s_fu_224_out_act_1_we0;
    end else begin
        act2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_2_address0 = grp_dense_relu_256_128_s_fu_246_in_act_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_2_address0 = grp_dense_relu_512_256_s_fu_224_out_act_2_address0;
    end else begin
        act2_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_2_ce0 = grp_dense_relu_256_128_s_fu_246_in_act_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_2_ce0 = grp_dense_relu_512_256_s_fu_224_out_act_2_ce0;
    end else begin
        act2_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_2_ce1 = grp_dense_relu_256_128_s_fu_246_in_act_2_ce1;
    end else begin
        act2_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_2_we0 = grp_dense_relu_512_256_s_fu_224_out_act_2_we0;
    end else begin
        act2_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_3_address0 = grp_dense_relu_256_128_s_fu_246_in_act_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_3_address0 = grp_dense_relu_512_256_s_fu_224_out_act_3_address0;
    end else begin
        act2_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_3_ce0 = grp_dense_relu_256_128_s_fu_246_in_act_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_3_ce0 = grp_dense_relu_512_256_s_fu_224_out_act_3_ce0;
    end else begin
        act2_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_3_ce1 = grp_dense_relu_256_128_s_fu_246_in_act_3_ce1;
    end else begin
        act2_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_3_we0 = grp_dense_relu_512_256_s_fu_224_out_act_3_we0;
    end else begin
        act2_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_address0 = grp_dense_relu_256_128_s_fu_246_in_act_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_address0 = grp_dense_relu_512_256_s_fu_224_out_act_0_address0;
    end else begin
        act2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_ce0 = grp_dense_relu_256_128_s_fu_246_in_act_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_ce0 = grp_dense_relu_512_256_s_fu_224_out_act_0_ce0;
    end else begin
        act2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act2_ce1 = grp_dense_relu_256_128_s_fu_246_in_act_0_ce1;
    end else begin
        act2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        act2_we0 = grp_dense_relu_512_256_s_fu_224_out_act_0_we0;
    end else begin
        act2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_1_address0 = grp_dense_relu_128_10_s_fu_268_in_act_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_1_address0 = grp_dense_relu_256_128_s_fu_246_out_act_1_address0;
    end else begin
        act3_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_1_ce0 = grp_dense_relu_128_10_s_fu_268_in_act_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_1_ce0 = grp_dense_relu_256_128_s_fu_246_out_act_1_ce0;
    end else begin
        act3_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_1_ce1 = grp_dense_relu_128_10_s_fu_268_in_act_1_ce1;
    end else begin
        act3_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_1_we0 = grp_dense_relu_256_128_s_fu_246_out_act_1_we0;
    end else begin
        act3_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_2_address0 = grp_dense_relu_128_10_s_fu_268_in_act_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_2_address0 = grp_dense_relu_256_128_s_fu_246_out_act_2_address0;
    end else begin
        act3_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_2_ce0 = grp_dense_relu_128_10_s_fu_268_in_act_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_2_ce0 = grp_dense_relu_256_128_s_fu_246_out_act_2_ce0;
    end else begin
        act3_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_2_ce1 = grp_dense_relu_128_10_s_fu_268_in_act_2_ce1;
    end else begin
        act3_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_2_we0 = grp_dense_relu_256_128_s_fu_246_out_act_2_we0;
    end else begin
        act3_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_3_address0 = grp_dense_relu_128_10_s_fu_268_in_act_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_3_address0 = grp_dense_relu_256_128_s_fu_246_out_act_3_address0;
    end else begin
        act3_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_3_ce0 = grp_dense_relu_128_10_s_fu_268_in_act_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_3_ce0 = grp_dense_relu_256_128_s_fu_246_out_act_3_ce0;
    end else begin
        act3_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_3_ce1 = grp_dense_relu_128_10_s_fu_268_in_act_3_ce1;
    end else begin
        act3_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_3_we0 = grp_dense_relu_256_128_s_fu_246_out_act_3_we0;
    end else begin
        act3_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_address0 = grp_dense_relu_128_10_s_fu_268_in_act_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_address0 = grp_dense_relu_256_128_s_fu_246_out_act_0_address0;
    end else begin
        act3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_ce0 = grp_dense_relu_128_10_s_fu_268_in_act_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_ce0 = grp_dense_relu_256_128_s_fu_246_out_act_0_ce0;
    end else begin
        act3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act3_ce1 = grp_dense_relu_128_10_s_fu_268_in_act_0_ce1;
    end else begin
        act3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        act3_we0 = grp_dense_relu_256_128_s_fu_246_out_act_0_we0;
    end else begin
        act3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        act4_address0 = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_act4_address0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        act4_address0 = grp_dense_relu_128_10_s_fu_268_out_act_address0;
    end else begin
        act4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        act4_ce0 = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_act4_ce0;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        act4_ce0 = grp_dense_relu_128_10_s_fu_268_out_act_ce0;
    end else begin
        act4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        act4_we0 = grp_dense_relu_128_10_s_fu_268_out_act_we0;
    end else begin
        act4_we0 = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_relu_128_10_s_fu_268_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_m_axis_output_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_relu_784_512_s_fu_202_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_relu_512_256_s_fu_224_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_relu_256_128_s_fu_246_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_output_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_output_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_1_address0 = grp_dense_relu_784_512_s_fu_202_in_act_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_1_address0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_address0;
    end else begin
        input_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_1_ce0 = grp_dense_relu_784_512_s_fu_202_in_act_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_1_ce0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_ce0;
    end else begin
        input_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_1_ce1 = grp_dense_relu_784_512_s_fu_202_in_act_1_ce1;
    end else begin
        input_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_1_we0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_1_we0;
    end else begin
        input_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_2_address0 = grp_dense_relu_784_512_s_fu_202_in_act_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_2_address0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_address0;
    end else begin
        input_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_2_ce0 = grp_dense_relu_784_512_s_fu_202_in_act_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_2_ce0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_ce0;
    end else begin
        input_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_2_ce1 = grp_dense_relu_784_512_s_fu_202_in_act_2_ce1;
    end else begin
        input_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_2_we0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_2_we0;
    end else begin
        input_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_3_address0 = grp_dense_relu_784_512_s_fu_202_in_act_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_3_address0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_address0;
    end else begin
        input_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_3_ce0 = grp_dense_relu_784_512_s_fu_202_in_act_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_3_ce0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_ce0;
    end else begin
        input_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_3_ce1 = grp_dense_relu_784_512_s_fu_202_in_act_3_ce1;
    end else begin
        input_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_3_we0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_3_we0;
    end else begin
        input_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_address0 = grp_dense_relu_784_512_s_fu_202_in_act_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_address0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_address0;
    end else begin
        input_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_ce0 = grp_dense_relu_784_512_s_fu_202_in_act_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        input_ce0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_ce0;
    end else begin
        input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        input_ce1 = grp_dense_relu_784_512_s_fu_202_in_act_0_ce1;
    end else begin
        input_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_we0 = grp_mlp_top_Pipeline_READ_INPUT_fu_180_input_r_we0;
    end else begin
        input_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TDATA_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDATA;
    end else begin
        m_axis_output_TDATA_int_regslice = m_axis_output_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TDEST_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TDEST;
    end else begin
        m_axis_output_TDEST_int_regslice = m_axis_output_TDEST_reg;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TID_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TID;
    end else begin
        m_axis_output_TID_int_regslice = m_axis_output_TID_reg;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TKEEP_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TKEEP;
    end else begin
        m_axis_output_TKEEP_int_regslice = m_axis_output_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TLAST_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TLAST;
    end else begin
        m_axis_output_TLAST_int_regslice = m_axis_output_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TSTRB_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TSTRB;
    end else begin
        m_axis_output_TSTRB_int_regslice = m_axis_output_TSTRB_reg;
    end
end

always @ (*) begin
    if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axis_output_TUSER_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TUSER;
    end else begin
        m_axis_output_TUSER_int_regslice = m_axis_output_TUSER_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_input_TREADY_int_regslice = grp_mlp_top_Pipeline_READ_INPUT_fu_180_s_axis_input_TREADY;
    end else begin
        s_axis_input_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((grp_dense_relu_784_512_s_fu_202_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_dense_relu_512_256_s_fu_224_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_dense_relu_256_128_s_fu_246_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_dense_relu_128_10_s_fu_268_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((regslice_both_m_axis_output_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_dense_relu_128_10_s_fu_268_ap_start = grp_dense_relu_128_10_s_fu_268_ap_start_reg;

assign grp_dense_relu_256_128_s_fu_246_ap_start = grp_dense_relu_256_128_s_fu_246_ap_start_reg;

assign grp_dense_relu_512_256_s_fu_224_ap_start = grp_dense_relu_512_256_s_fu_224_ap_start_reg;

assign grp_dense_relu_784_512_s_fu_202_ap_start = grp_dense_relu_784_512_s_fu_202_ap_start_reg;

assign grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start = grp_mlp_top_Pipeline_READ_INPUT_fu_180_ap_start_reg;

assign grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_ap_start_reg;

assign grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TREADY = (m_axis_output_TREADY_int_regslice & ap_CS_fsm_state13);

assign m_axis_output_TVALID = regslice_both_m_axis_output_V_data_V_U_vld_out;

assign m_axis_output_TVALID_int_regslice = grp_mlp_top_Pipeline_WRITE_OUTPUT_fu_287_m_axis_output_TVALID;

assign s_axis_input_TREADY = regslice_both_s_axis_input_V_data_V_U_ack_in;


reg find_kernel_block = 0;
// synthesis translate_off
`include "mlp_top_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //mlp_top

